(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/A1.jpg", id:"A1"},
		{src:"images/A2.jpg", id:"A2"},
		{src:"images/A3.jpg", id:"A3"},
		{src:"images/Copiadecamioneta.png", id:"Copiadecamioneta"}
	]
};



// symbols:



(lib.A1 = function() {
	this.initialize(img.A1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,242,90);


(lib.A2 = function() {
	this.initialize(img.A2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,242,90);


(lib.A3 = function() {
	this.initialize(img.A3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,242,90);


(lib.Copiadecamioneta = function() {
	this.initialize(img.Copiadecamioneta);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,292,245);


(lib.TROCC = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.Copiadecamioneta();
	this.instance.setTransform(-146,-123.2);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-146,-123.2,292,245);


(lib.Symbolc = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.A3();
	this.instance.setTransform(-124,-45,1.009,1);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-124,-45,244.1,90);


(lib.Symbolb = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.A2();
	this.instance.setTransform(-122,-45,1.009,1);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-122,-45,244.1,90);


(lib.Symbola = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.A1();
	this.instance.setTransform(-122,-45,1.009,1);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-122,-45,244.1,90);


(lib.Más = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEE32B").s().p("AFBAdQgPgBgEgKQgEgKAFgMQAFgPALgHQAKgHARAAQAUAAAIALQAGAJgGAOQgFAPgKAHQgKAHgQAAQgEAKANAAIAIgBIgDALIgJABQgZAAAIgWgAFJgRQgGAFgEAKQgIAVAVAAQAKAAAGgFQAGgEAEgKQAIgVgWAAQgJAAgGAEgAGBAWQgGgGAFgNIANgjIAQAAIgNAjQgFAPAQAAQAHAAAEgCQAFgEADgJIAOgjIARAAIgOAjQgFAQgKAGQgIAGgQgBQgQABgHgJgACEAaIAEgNQANAGAMAAQAPAAADgHQACgHgJgCIgKgBQgUgDAGgQQAFgQAaAAQAPAAANAFIgEAMQgKgGgOAAQgNAAgCAHQAAAAgBABQAAABAAAAQAAABAAAAQABABAAAAQABACAFABIAKACQAUAEgGAQQgGARgZgBQgTAAgMgEgAjAAUQgIgKAHgPQAKgcAiAAQANAAAKAEIgEAMQgIgEgLAAQgWABgHATQgHATAZAAQAKAAAJgCIgEAMQgHADgNgBQgTABgIgLgAkSAUQgHgKAGgOQAGgPAKgHQAKgHARAAQAVAAAHALQAGAJgGAOQgFAQgKAGQgKAIgRgBQgVAAgHgKgAj5gRQgGAFgEAKQgHAVAVAAQAKAAAGgFQAGgEADgKQAIgVgVAAQgKAAgGAEgAm4AUQgHgKAGgOQAGgPAKgHQAKgHARAAQAVAAAHALQAGAJgFAOQgGAPgKAHQgKAIgRgBQgVAAgHgKgAmfgRQgGAFgDAKQgJAVAWAAQAKAAAGgFQAGgEAEgKQAHgVgVAAQgKAAgGAEgAn6AUQgIgKAGgPQALgcAiAAQANAAAKAEIgEAMQgIgEgLAAQgWABgHATQgHATAZAAQAKAAAJgCIgEAMQgHADgNgBQgTABgIgLgAHEAdIAXg9IARAAIgXA9gAETAdIAAgNIgfAAIgJANIgRAAIAqg2QAEgHAGAAIASAAIADA9gAD9AEIAVAAIAAgcgABwAdIAAgNIgfAAIgJANIgRAAIApg2QAEgHAHAAIASAAIADA9gABZAEIAWAAIAAgcgAAcAdIATgwIgnAwIgOAAIgDgxIgSAxIgPAAIAXg9IARAAQAFAAABAIIACAkIAjgsIAbAAIgXA9gAiFAdIAXg9IA3AAIgEALIgnAAIgFAPIAjAAIgEAJIgjAAIgFAPIAmAAIgEALgAlDAdIgMgwIgSAwIgPAAIAXg9IAQAAQAHABAAAGIAMAqIASgxIAPAAIgWA9gAHdgkIARgOIARAAIgTAOgABrgkIARgOIARAAIgUAOg");
	this.shape.setTransform(1.3,1.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("AorBtIAAjZIRXAAIAADZgAFLgPQgKAIgGANQgFANAEAKQAFAKAOACQgIAWAZgBIAJAAIADgLIgIABQgMAAAEgKQAQgBAJgGQAKgHAGgQQAFgOgGgIQgHgMgVAAQgRABgKAGgAGMAPQgFAMAHAHQAGAIARAAQAPAAAJgGQAJgFAGgQIANgjIgRAAIgNAjQgDAJgFADQgEACgHAAQgRAAAFgOIAOgjIgRAAgACRAlQALAFATAAQAaAAAGgQQAGgSgUgFIgLgCQgFgBgBAAQAAAAAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQACgGAOAAQANAAAKAFIAEgMQgNgEgOgBQgaAAgFAQQgGAPATAEIALACQAJACgDAHQgDAHgOgBQgNABgMgGgAi1AFQgGAQAHALQAIAKATAAQANAAAHgDIAFgMQgJACgLAAQgYABAHgWQAGgRAWAAQALAAAJADIAEgLQgLgFgNAAQghAAgLAbgAj2gPQgLAIgFANQgGAQAGAKQAHAKAVAAQARAAAKgHQAKgHAGgQQAGgOgGgIQgIgMgUAAQgRABgKAGgAmcgPQgLAIgFANQgGAQAGAKQAIAKAUAAQARAAAKgHQALgHAFgQQAGgOgGgIQgIgMgUAAQgRABgKAGgAnvAFQgGARAHAKQAIAKATAAQANAAAHgDIAFgMQgKACgKAAQgZABAIgWQAGgRAWAAQALAAAJADIAEgLQgLgFgNAAQgiAAgKAbgAHRApIARAAIAWg9IgQAAgAEfAbIABAOIAPAAIgCg9IgTAAQgGAAgEAGIgqA3IASAAIAJgOgAB8AbIAAAOIAQAAIgCg9IgTAAQgGAAgEAGIgqA3IARAAIAKgOgAApApIARAAIAWg9IgaAAIgjAsIgDgkQAAgIgIAAIgPAAIgWA9IAPAAIAQgxIADAxIAPAAIAngxgAh4ApIA3AAIAEgMIgnAAIAFgOIAjAAIAEgMIgiAAIAFgMIAnAAIADgLIg3AAgAk2ApIAXAAIAXg9IgPAAIgTAwIgLgqQgBgGgGAAIgRAAIgWA9IAOAAIASgxgAHqgZIAOAAIAUgNIgRAAgAB3gZIAPAAIATgNIgRAAgAFLAIQAEgJAGgFQAGgDAKAAQAVAAgHATQgEALgGAFQgGAEgKAAQgVAAAHgWgAj2AIQAEgJAGgFQAGgDAJAAQAWAAgIATQgEALgGAFQgGAEgKAAQgVAAAIgWgAmcAIQAEgJAGgFQAGgDAJAAQAWAAgIATQgEALgGAFQgGAEgJAAQgWAAAIgWgAEJAQIAVgdIABAdgABmAQIAVgdIABAdg");

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-55.6,-10.9,111.4,21.9);


(lib.LOGOO = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AhVDZQgPgBgKgOQgGgHABgFQAAgEAFgHQALgOAFgJIAFgKQgKgKgBgMIAAgDQAAgHADgFQACgEAEgDQgDgOADgIQAFgNAKgFIADgHQgEgKACgLQABgLAHgIQgGgRAMgNQgFgLAEgPQgEgFgBgIQgRgCgKgOQgKgCgIgHQgJgIgCgMQgOgKACgSQgDgFABgHQABgHAEgEQgMgJgDgJQgDgIAAgSQgEgHABgDQAAgDAEgCQAAgEAGgCQAFgCAFAEQAJgDAKARQACgEAEAAQAGgBAEAFQAFAEgDAFQgBABAAAEIACAIQAEAGgBAHQAJAFACAIQAGAEADAFIAJADQAJgBAJAEIAAAAQANgEALAAQgGgHAAgKQAAgJAGgHQgBgKAGgJQAFgKAKgDQABgHALgBQAMgBADAIQAKADAFAIQAGAIgBAJQAHAGABAKQABAKgFAIQAOACAKAGQAMABAJAJQAMALgEAPQAJAHABAMIAAACQAAAHgCAHQAJAJgBALQAKAFAEAJQAEAKgFALQAAACAFADQAGAEADACQAFAGACAGQACAGgCADQABAHgIADQgHADgFgEIgIAFQgEADgFgEQgDgDAAgDQgDgCgBgDQgJgHAEgIIgBgEQgOAAgHgIQADANgJANQAGAUgQAPQADAIgDAIQALAPgQAUIAAAAQABAHgDAIIAAACQgFALgLAGQADAKACADIABAAQABACAIAFQAPAIAAALQACADgDAGQgEAIgQADQgOADgHgDQgGgCgEgHIgHgLQgKgKgCgDQgCgGABgHQABgIAGgIQgJgFgCgKIAAgBQgDgHABgIIACgHIgEgGQgCgFAAgEQgBAEgDAFQACAHgCAGIgCAHIgGAIIgIAGQgBAJgGAIQgGAGgIADIgEABQgFAOAAAEIADAMQACAKgBAEQgCAQgaAAIgDAAgAhcCpIgMAQQgGAHAGAIQAFAGAIADQAJADAHgCIAAgBQgSABgIgMIABgBQAJAHALAAQAKABAGgEQAEgCgBgDIgEgUQgBgGAFgOQgQAAgEgGQgFAKgGAJgAAKCYQgCAIABADQACAHAJAJIAGAIQADAFAGADQAGADAMgDQAMgCACgFIgBAAQgGAFgKABQgJAAgCgCIABgBQARABAHgHQAHgHgKgHQgMgGgDgDIgNACIgCgFIALgCIgCgFIgLACIgCgFIAMgCIgBgDQgMADgKgEQgFAGgBADgAhbCCQAFAOANAFQAQAFALgHQAIgFACgKQgjAIgQgfQgIAHAEAOgAAICEQAHAIAMAAQARABAHgMQAEgIgBgHQgKAIgOgBQgRAAgKgNQgDAPAIAJgAhTBoQAGARAOAFQAXAIANgNQALgLgDgKQgJAGgMAAQgJAAgGgDQgUgLgCgUQgNANAHATgAACBlQAKAPASAAQAUAAAJgNQAIgMgFgKQgMAQgWgDQgXgDgFgSQgGANAIAPgAhEBUQAFAKAJAEQARAHAMgIQAMgHgBgKQghAIgUgbQgHALAGAMgAAEBEQACAKAJAGQAIAFALABQAMAAAIgIQAJgIgDgMQgMAIgOgBQgOAAgLgIgAg8A9QANARATgBQAggCAEgeQgRAKgWgGQgWgHgKgUQgMAVAPASgAAOApQAAAHgDAJQAQANAWgIQAYgJgCgZQgLALgQADQgPACgNgEgAg5AWQAJARAUAFQAUAFANgIQAPgIgBgOQgSAAgQgEQgbgHgOgRQgKANAJASgAAaATQAAAJgGAIQAVAGARgKQATgKgBgWQgRARghACgAB5AdQAAAAAAAAQABAAAAAAQABAAABAAQAAAAABAAIAFgEIgDgEQgJADADAFgAB6ALQADABAAAEIAIAEQAEAFADABQABAAABAAQAAAAABAAQAAAAABAAQAAgBAAAAQADgCgCgDIgGgHIgFgGIgDgGQAAgBAAAAQABAAAAAAQAAAAABABQAAAAABABQACAFAKAJQgCgIgGgFIgGgDQgDAAgDgEQgFAEgKACIACAFIAEADIACAAIADABgAB0ASQAAAGACgBIAFgEIgBgDQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBAAAAAAIgBgBQAAAAgBABQAAAAAAABQAAAAgBABQAAABAAABgABvALQgDAEAEADIACgGIgCgCIgBABgAgeADQAWALAbgBQAjgBAQgNQAMgMgCgOQgZAUgrgDQgqgCgYgXQgFAaAdAMgABXgSQgCAJAIAGQAKAEAMgDQALgFABgMQACgNgNgGQgGARgXADgAg6g3QACAPAXAMQAYANAcgBQAtAAASgWQAOgSgKgQQgQASgpAEQgpAEgYgTQgIAIgOACgABfgzQgCAKgHAIIABAKQAOgBAIgMQAIgNgMgLQgDAHgHACgAgghGQARAOAeAAQAlABAWgPQAYgRgSgZQgKAMghAFQgkAGgagLQACAOgJAQgABahOQAGAHAAALQALgHgBgNQgCgKgEgEQgEAJgGAHgAg1hYQgKARgUAAQAMANASgFQAVgFABgXQACghgbgGQAOAYgLASgAhdhOQASAFANgOQALgMgGgRQgFgQgHgBQAEAUgQAMQgPANgSgIQAFANAQAFgABSh3QAKAGACASQAGgLgGgKQgFgHgHgCQACAEgCACgAhrhjQAOADAKgJQAHgHACgJQABgJgEgHIgEgFQgDAOgPAIQgQAIgMgJQAEASAQAEgAgniCQAJAIAEAPQARAIAVAAQAbAAASgHQASgGABgJQACgGgLgFQgJgEgPgBQgEAEgDAAQgEAAADgBQAGgDgEgGQAJgCABgNQAAgKgJgHIAAgBIABgBQABgJgGgGQgFgHgLgCIAAgBQABAAAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBgCgFAAQgGgBgDADQAAAAAAAAQAAABAAAAQAAAAABAAQABABABAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAgBAAQgHAAgFAGQgJAHABANIAGAAQABAAAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAQgLABgBANQgBANANAGQAAAAAAAAQAAAAAAAAQAAAAAAABQAAAAgBAAIgCADQAAAAAAABQAAAAAAAAQABABAAAAQAAABABAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAgBAAQgEgDgHAAQgHAAgKADgAh+h+QAKAJAOgHQAOgGABgMQABgMgKgDQgCACAAAIQAAAAAAABQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAIAAgEQACgDgBgCQgBgDACgDQACgFAAgDIgEgMQgDgJAEgHQgEgEgDAEQgEAHAEAKQgDAAgCAFIgBACIgCAAQAAgDACgGQgBgCgBgJQgCgGgEgFQgEgFgDgBIALAUQAAAAAAABQAAABAAAAQAAABgBAAQAAAAgBABQgIgRgGgGQgGgGgBAEIAEADQAEAFAJATIgCABQgCgBgDgHQgDgHgGgHQgDgDgCACIADAHQACAAADACQADACAAACQACANACACIgDACQgCgDgCgNQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQgBgBAAAAQAAAAAAABQgBAAAAAAQAAAAAAABQgBAPADAGQADAHANAKQADACACAFQADAFAFAAIABACQgCACgEgBQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAIgEgGQgJAKAJAKgAhWCuIAAgFQAKAAAGADIgBAEIgPgCgAhUCkIAAgFQAKABAHACIgCAEQgIgCgHAAgAAOiTIgFgEQgCgCgEAAIgCACQAAgBgBAAQAAAAABgBQAAAAAAgBQABgBAAgBIACgBQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAJgCQAHgBAHACIACgBQABgBAAABQAAAAAAAAQAAABAAABQABABAAABIgDAAQAAAAgBAAQAAAAAAAAQgBABgBAAQAAABgBABIgEAEIgDAAIgEgBgAAKiZIAFADQADACACgBIAGgFIgHgBIgJACgAACilQgCgDAAgHQgBgGABgEQACgDAEgBQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABQAFADAAAHQAAANgIABQgDAAgCgCgAACipIgBgDQAAgIAFgBQAFAAAAAIIAAACIABgGQAAgFgDgDQgBgBAAAAQAAAAgBAAQAAgBAAAAQgBAAAAABQgGAAAAAKIACAHgAAXimQgEgDAAgHQgBgFACgEQACgEAEAAQAAgBABAAQABABAAAAQABAAAAAAQABABAAAAQAEADABAHQABANgIABQgBAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAgAAfiuIAAAEQACgDgBgEQAAgGgDgDIgDgBQgFAAAAALIAAABQABgGAEgBQAFAAAAAIgAh8ipIgFgCQAAAAAAgBQAAAAABAAQAAAAABAAQABAAABAAIAFABIABAEg");
	this.shape.setTransform(-43.1,2.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FAE22B").s().p("Al+AHQADgHgBgGIO4AAIgGANgAnRAHIAHgHIACgGIAIAAQgBAGADAHgAo7AHIAAgNIAeAAQgDAFgBAFIAAADg");
	this.shape_1.setTransform(1.4,13.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Aw4HXIFXuvIcaAAIAAOxgAotBvIAAAPIAAAgIAhAAQgGAJgLAOQgFAHAAAEQAAAFAFAHQAKANAQABQAcABACgQQABgEgCgLIgCgLQgBgEAFgOIAEgBIA1AAQgBAHADAGQABACALALIAGALQAEAHAGACQAIACANgCQARgEADgIQADgGgCgCQABgLgPgJQgJgEgBgCIAAAAITJAAIAAjsIyJAAIAAgBQgCgMgIgHQADgQgLgKQgKgJgMgBQgJgGgPgCQAGgIgCgLQAAgJgIgHQABgIgFgJQgGgHgKgEQgDgHgMAAQgMACgCAGQgJAEgGAKQgGAJACAKQgHAGAAAKQABAKAFAGQgLAAgNAFIAAAAQgIgEgKABIgJgEQgDgEgGgEQgBgIgKgFQABgHgEgHIgCgIQAAgEABAAQADgFgFgEQgEgFgGAAQgEABgCAEQgJgRgKACQgFgDgFACQgGABAAAFQgEACAAACQgBAEAEAHQAAASADAIQADAJAMAJQgEADgBAIQgBAGADAGQgCASAOAKQACALAKAIIgPAAgAoJDSQgJgCgFgHQgGgHAGgHIAMgQQAHgKAEgJQAEAGAQAAQgFAOABAGIAEATQABAEgDACQgHADgKAAQgLgBgJgGIgBAAQAIANASgCIAAACIgGAAQgEAAgFgCgAoFCwIAPACIABgFQgGgCgKAAgAoCCmQAGAAAIACIACgFQgHgCgJAAgAmKDFQgGgDgDgFIgGgJQgJgJgCgGQgBgEACgHQABgEAFgGQALAFALgEIABAEIgMACIACAFIAMgCIABAFIgKACIABAEIANgCQADADAMAHQAKAGgHAIQgHAHgRgCIAAACQABACAKAAQAKgCAFgFIABABQgCAEgMADIgKABQgFAAgDgBgAn4CXQgNgFgEgOQgFgOAIgIQARAgAigIQgCAKgIAFQgGAEgIAAQgGAAgHgCgAmSCOQgMgBgHgHQgIgKADgPQAKANASABQANAAAKgHQABAGgDAJQgHALgPAAIgDAAgAnuB/QgNgEgHgRQgHgTANgNQACATAUAMQAGADAJAAQAMAAAJgHQAEALgMALQgIAIgMAAQgHAAgJgEgAmrBnQgJgPAHgOQAGATAWADQAWACAMgPQAFAKgIAMQgJANgUAAQgRAAgLgPgAnlBkQgJgEgFgKQgGgMAHgLQAUAbAhgJQABALgMAHQgGAEgIAAQgHAAgIgDgAmeBWQgJgHgBgJIAEgIQALAJAOAAQAPAAAMgIQACANgJAIQgIAHgMAAQgKAAgJgFgAAjBLQgTgKAAgSQgBgcAagTQATgPAdgHQAkgGAeAIIgPAjQgEgLgRAAQgNAAgOAGQgNAGgFANQgEAOAPAGQAIADANgBIAXgEIgMAhQgRADgVABIgDAAQgZAAgQgJgAKyBRIAChKIgbBKIgrAAIAnhoIA7AAIADABQAEACACACQAFAFAAALIgDAyIAbhHIAqAAIgmBogAIdBRIAohoIAzAAIgnBogAGqBRIAnhoIAyAAIgaBFIAyAAIgNAjgAElBRIAnhoIBrAAIgKAaIg7AAIgEAMIA4AAIgKAaIg4AAIgEAMIA8AAIgLAcgADYBRIAMgkIgZAAIgOAkIgwAAIAnhoIAwAAIgNAlIAaAAIANglIAxAAIgnBogAhHBRIAnhoIAxAAIglBogAiTBRIAchKIgzBKIgqAAIAGhMIgbBMIgvAAIAnhoIA8AAQANAAAAAVIgDAjIAlg4IBIAAIgmBogAnrA+QgPgRAMgVQAKAUAXAHQAVAGATgKQgEAeghACIgDAAQgRAAgNgRgAmiA7QAEgJAAgHIABgBQANAEAPgCQAQgDALgLQACAZgXAJQgJADgHAAQgMAAgLgIgAnKAuQgVgGgIgQQgKgTALgMQANARAbAHQASAEASgBQABAOgOAJQgKAFgLAAQgHAAgHgCgAmZAmQAGgJAAgJQAhgCARgRQABAXgSAKQgLAGgNAAQgHAAgIgCgAk0AeQgDgEAJgDIAEAEIgGADIgCABIgCgBgAkgAbQgEAAgEgFIgIgFQAAgDgDgCQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAgBAAIgDgDIgCgFQAJgDAFgDQADACAEABIAFAEQAGAFACAHQgJgJgDgEQgBgBAAAAQgBgBAAAAQAAAAAAAAQAAAAAAABIACAGIAFAGIAGAGQACADgDADIgBABIgCgBgAk5AUQABgGACACQABAAAAAAQAAAAABAAQAAABAAAAQABABAAAAIABADIgFAEIAAAAQgCAAAAgFgAk+AMQAAAAABAAQAAAAABAAQAAAAABABQAAAAABABIgCAFQgFgCADgFgAnNAFQgcgMAEgbQAZAYArACQArADAZgUQACAOgMALQgQANgjACIgEAAQgaAAgVgKgAlPgBQgJgHACgIQAYgDAFgRQANAGgCANQAAALgMAGQgFAAgFAAQgGAAgFgBgAnQgaQgXgMgCgPQAPgDAHgHQAYATArgFQApgEARgSQAJAQgOATQgSAVgtABIgCAAQgcAAgYgMgAlXggQAIgHABgLQAHgCAEgGQALALgIANQgIAMgOABgAmeg2QgfgBgSgOQAJgPgCgOQAcAKAkgFQAhgGAKgLQATAYgZARQgUAPgjAAIgEAAgAlThNQAHgGADgJQAEADACAKQACAOgLAGQAAgKgHgIgAoChFQAVAAAJgRQALgSgNgYQAbAGgCAhQgCAXgVAFIgJABQgMAAgJgJgAoLhMQgRgFgFgOQATAJAOgNQAQgMgEgVQAHACAGAPQAFASgLALQgJALgNAAIgIgBgAlbh1QACgCgCgFQAHACAFAIQAGAJgGAMQgCgSgKgGgAoahiQgQgDgEgSQANAIAPgHQAPgIADgPIAEAGQAFAHgCAJQgBAIgIAHQgHAHgKAAIgHgBgAnJhqQgEgOgIgIQASgGAKAGQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAABAAIABgDQABAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAgBQgNgGACgNQAAgMALgBQABAAAAAAQAAAAAAAAQAAgBAAAAQAAAAgBAAIgGAAQgBgNAJgIQAGgFAIAAQABAAAAgBQAAAAAAAAQAAAAAAAAQAAAAgBAAQgBAAgBgBQAAAAgBAAQAAAAAAgBQAAAAABgBQADgCAFAAQAGABAAACQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIAAABQALACAFAHQAGAGgBAIIgBABIAAACQAKAGgBALQAAANgKABQAEAHgGACQgDACAEAAQADAAAEgEQAPABAKAEQAKAFgBAGQgCAIgRAHQgTAGgaAAQgYABgRgJgAmkiWIAGAFQADACADgBIAEgFQABAAABgBQAAAAABgBQAAAAABAAQAAgBAAAAIADABQAAgBAAgBQAAgBgBgBQAAAAAAAAQAAgBAAABIgDABQgHgCgGABIgKACQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgCABQAAABgBABQAAABAAAAQAAABAAAAQAAAAAAAAIADgBQADAAACABgAmni7QgEABgCADQgDAEABAGQAAAGAEAEQACACADAAQAIgBAAgNQAAgHgFgEQAAAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAIgBAAgAmTi8QgDABgDAEQgBADAAAFQAAAIAFADQAAAAAAABQABAAAAAAQABAAABAAQAAABABAAQAIgBgBgNQgBgHgDgDQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBAAAAIgBAAgAoth9QgJgJAJgKIAEAGQABAAAAABQABAAAAAAQABAAABABQAAAAABAAQAEAAADgBIgCgDQgFABgDgFQgCgFgDgCQgMgKgEgHQgDgGABgPQAAgBABAAQAAAAAAAAQAAgBAAAAQABAAAAABQABAAAAAAQABAAAAABQABAAAAABQAAAAAAAAQACAOACADIADgCQgBgCgDgNQAAgCgCgDQgEgBgCAAIgDgHQACgCADADQAGAHADAGQAEAIACAAIABAAQgJgTgEgGIgEgCQACgEAFAFQAGAHAIARQABgBAAAAQABAAAAgBQAAAAAAgBQAAgBAAgBIgLgTQADAAAEAGQAEAFACAGQABAIABADQgCAGAAADIACAAIABgCQACgGAEAAQgFgJAFgIQACgEAEAEQgEAIAEAIIADANQAAADgCAEQgCAEABACQABADgBADIgBADQAAABABAAQAAAAAAAAQABAAAAAAQABgBABAAQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBgBAAQAAgJACgBQAKADgBAMQgBAMgNAGQgHADgFAAQgHAAgGgGgAowipIAFABIAGADIgBgEIgGgBQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAABAAAAgAmdiUIgGgEQAIgCAIACIgGAFIgBAAIgDgBgAmtiuQAAgLAGAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAAAQAEAEAAAFIgCAGIAAgCQABgIgGAAQgFABAAAIIABACIgCgGgAmNisQgBgIgFAAQgDABgBAGIgBgCQAAgKAFAAIADABQADADABAFQAAAFgCADg");
	this.shape_2.setTransform(0,2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1960A6").s().p("AoLB2QgCgDgEgKQALgFAFgMIABgBIOzAAIAGgPIu4AAIAAgBQAQgTgLgPQADgJgCgIQAPgPgFgSQAIgMgDgQQAHAKAOAAIACAEQgEAJAIAGQACAEACABQAAADADAEQAFABAEgBIAIgFQAFAFAHgEQAIgCgBgIQACgDgCgGQgBgGgGgGQgDgEgGgEQgEgCgBgDQAGgLgFgKQgEgJgKgEQACgMgKgJQACgHABgHISJAAIAADrgAg1g9QgdAGgTAQQgaAVABAaQAAASATAKQARAJAbAAQAVgCARgDIAMggIgXADQgNABgIgDQgPgFAEgMQAFgOANgFQAOgHANAAQARAAAEALIANglQgOgEgSAAQgQAAgQADgAIiAqIBIAAIAmhoIgqAAIgbBHIADgzQAAgKgFgGQgCgCgEgBIgDgBIg7AAIgnBoIArAAIAbhJgAGNAqIA0AAIAnhoIgzAAgAEaAqIBkAAIANgjIgyAAIAahFIgyAAgACVAqIBsAAIALgdIg8AAIAEgMIA4AAIAKgYIg4AAIAEgLIA7AAIAKgcIhrAAgABUAGIgMAkIAwAAIAnhoIgxAAIgNAmIgaAAIANgmIgxAAIgkBoIAuAAIAOgkgAjXAqIAzAAIAnhoIgzAAgAkjAqIAvAAIAmhoIhIAAIglA5IADglQAAgUgNAAIg8AAIgnBoIAvAAIAbhLIgGBLIAqAAIAzhJgApwB2QAIgDAGgGQAGgHABgKIAIgFIATAAIAAABQADAJAJAFQgGAJgBAHgAq9B2IAAgfIAaAAQABALAKAKIgEAKgApKBIQABgHgCgHQADgEABgFQAAAFACAEIAFAGIgCAIgAq9BIIAAi9IAPAAQAHAHAKACQAKAOASADQABAHADAFQgDAPAEAMQgLANAFASQgGAJgCALQgCAIAFALIgEAHQgKAEgFANQgDAJADANQgEAEgCAEg");
	this.shape_3.setTransform(14.4,6);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-108.2,-45.3,216.4,94.7);


(lib._24 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AUuB4QgRgEgNgEQgOgFgKgIQgKgHgGgKQgHgIgDgMQgDgLgBgMQAAgMACgNQAEgOAEgNIAMgbQAGgNAHgKQAIgLAJgIQAIgIALgHQAJgGAMgFQAMgEANgDQARgFAqgBQAWAAARACQARADANAFQANAGALAGQAKAIAGAJQAGAJAEALQADALAAANQAAAMgCAOQgCAMgGAOIgLAbQgHAMgIALQgGAKgKAIQgJAJgKAGQgJAGgMAFQgLAFgOADQgkAGgWAAQgWAAgRgCgAVqg9QgLAEgIAGQgJAGgHAMQgHAMgGAQQgGAPgBANQgCAOAFAJQAEAKAKADQAKAFAQABQANAAAJgDQAMgDAHgHQAKgHAGgLQAHgMAHgRQAFgPABgNQACgNgFgKQgEgJgKgDQgJgGgQAAQgOABgJACgADhB4QgOgCgLgEQgMgEgJgFQgJgFgGgGQgGgIgEgIQgDgJgBgJQgBgKACgKQABgLAEgMIAviEIBZAAIgwCHQgEALAAAJQgBAHAEAGQAEAFAGADQAHABALAAIAQgBQAGgBAGgEQAHgGAFgIQAGgJAEgMIAwiIIBZAAIg7CgIgNAXQgHAKgIAIQgIAIgJAGQgJAGgLAEQgKAEgMACQgjAGgUAAQgRAAgPgCgAgRB4QgRgEgNgDQgOgFgKgHQgKgIgIgJQgGgJgFgLQgDgLgBgNQAAgNACgPQACgMAGgRQAFgPAIgNQAGgMAJgKIASgSQAKgIALgHQAPgHAggJQARgEAmgBQAZAAAYAEQAXAFAVAGIgVA7QgNgGgTgEQgUgEgSAAQgQAAgNADQgPACgKAIQgMAGgIAMQgIAMgFASQgGAPABAMQABANAHAHQAHAIAMAEQANADATAAQASAAATgDQASgBAPgFIgWA9QgQAFgUACQgQABgWAAQgSAAgRgCgAlDB1QgSgCgfgLIATg2QAQAHAXAFQAXAFAWABQAZgBALgEQAMgDADgKQAEgKgEgEQgDgGgLgCIgigGQgVgEgNgHQgOgIgGgIQgGgKAAgOQAAgNAGgPQAFgRALgNQALgLAQgJQAPgHAVgEQAUgDAZAAQAWAAAiAFQAYADAWAJIgSA2QgPgHgUgEQgegGgQABQgVgBgKAEQgJADgDAIQgDAKADAEQADADAJADIAjAGQAOADAVAIQAOAIAGAKQAHAKgBAOQgBAPgFAQIgJARIgJANQgMANgQAHQgPAIgUADQgTADgZAAQgtgCgTgDgAQRB0IA8isIhEAAIAUg7IDgAAIgUA7IhDAAIg+CsgAMwB0IgPipIg7CpIhNAAIBSjnIBgAAQAIAAAFACQAGADAEAEQAEAEACAIQABAFAAAJIAOCIIA8irIBOAAIhSDngAGeB0IBSjnIDYAAIgSA2IiAAAIgNAjIBzAAIgTA0IhzAAIgMAkIB/AAIgTA2gAprB0IBSjnIDZAAIgTA2IiAAAIgMAjIByAAIgTA0IhzAAIgNAkICAAAIgSA2gAuPB0IBSjnIBtAAQAUAAARADQAQACANAEQAOAFAJAIQAKAGAFAKQAHAIACALQAEAKAAAMQAAAMgCANIgHAZQgFAOgGANQgHAMgHAJQgHAKgKAIQgIAIgKAGQgKAGgKAEIgXAHQgiAFgTAAgAsiA7IAjAAQANAAAKgCQALgEAJgGQAJgGAGgMQAHgLAGgQQAFgOABgLQABgMgEgJQgDgHgJgEQgJgFgNABIgiAAgAzgB0IBSjnIDYAAIgTA2IiAAAIgMAjIBzAAIgTA0IhzAAIgNAkICAAAIgSA2gA4DB0IBRjnIBtAAQAUAAARADQAQACANAEQAOAFAJAIQAJAGAHAKQAFAIAEALQADAKAAAMQAAAMgCANQgDAMgFANQgEAOgHANQgGAMgIAJQgHAKgJAIQgIAIgKAGQgJAGgMAEIgXAHQghAFgTAAgA2YA7IAjAAQAOAAAKgCQAMgEAHgGQAJgGAHgMQAGgLAHgQQAEgOABgLQABgMgDgJQgDgHgJgEQgIgFgOABIgiAAg");
	this.shape.setTransform(-11.7,-1.9);

	// Layer 1 copy
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AUuB3QgRgDgNgEQgOgGgKgHQgJgIgIgJQgGgIgDgMQgDgKAAgNQgBgMADgOQACgNAGgNIALgcQAGgMAIgKQAHgLAJgIQAJgIAJgHQALgGAMgEQALgFANgDQARgFAqgBQAVAAARADQASADAOAEQANAFAJAIQAKAGAHAKQAGAJADAMQAEAKABAMQAAANgEANQgBANgGAOIgMAbQgGANgHAKQgIAKgJAIQgIAJgKAGQgLAHgKAFQgMAEgNADQglAGgXAAQgVAAgRgDgAVqg9QgLAEgJAGQgIAGgHAMQgHALgGARQgGAQgCANQgBANAFAJQAEAJAKAFQAKAEAPAAQAOABAKgDQALgDAIgHQAJgHAHgLQAGgMAGgRQAGgPABgNQABgNgDgJQgFgJgKgFQgKgEgPAAQgNAAgKACgADiB4QgPgBgLgEQgMgFgIgEQgKgGgGgHQgGgGgDgJQgEgJgCgJQgBgKACgLQACgKAEgMIAviEIBZAAIgwCHQgEALAAAIQAAAJADAFQAEAFAHADQAGABALABIAPgBQAHgDAHgEQAFgFAGgHQAFgKAEgNIAxiHIBYAAIg6CgIgNAXQgHAKgIAHQgIAJgJAGQgJAGgLAEQgKAFgMACQgjAFgVAAQgQAAgOgCgAgRB3QgRgCgOgFQgNgEgKgIQgKgHgHgJQgIgJgEgLQgDgMgBgNQgBgMADgPQACgMAGgQQAFgQAIgMQAGgNAJgLIASgSQAKgHALgGQAPgJAggIQARgEAmgBQAZAAAYAEQAYAFATAGIgUA6QgNgGgTgDQgUgEgSAAQgRAAgMACQgPADgLAHQgLAIgIAKQgIANgGASQgFAPABANQABALAHAIQAHAIAMADQANAEATAAQASAAATgCQASgDAPgDIgWA8QgQAEgUACQgRACgUAAQgTAAgRgDgAlCB1QgTgDgfgLIATg2QAQAJAXAEQAYAGAWgBQAYABALgFQALgEAEgKQAEgIgEgFQgDgGgLgCIgigGQgUgEgOgIQgNgHgHgIQgGgKAAgNQAAgNAGgRQAGgRALgMQAKgMAQgHQAQgIAUgDQAVgEAZAAQAUAAAkAFQAXAEAWAIIgSA2QgPgHgUgEQgegGgQAAQgVAAgJAEQgKADgDAIQgDAKACADQADAEAKADIAiAGQAPADAVAIQAOAIAGAJQAGAMgBAOQABAOgHAQIgHARIgLAOQgLAMgQAIQgPAGgVAEQgSADgZAAQgtgBgSgEgAQQB0IA9itIhFAAIAVg6IDgAAIgUA6IhDAAIg+CtgAMvB0IgNipIg8CpIhMAAIBRjnIBfAAQAJAAAGACQAFADAEAEQAEAFABAGQACAHAAAIIAOCHIA8iqIBNAAIhSDngAGfB0IBSjnIDYAAIgTA2IiBAAIgMAjIB0AAIgTA0Ih0AAIgMAkICAAAIgTA2gApqB0IBSjnIDYAAIgTA2IiAAAIgNAjIB0AAIgUA0IhzAAIgMAkIB/AAIgSA2gAuPB0IBSjnIBtAAQAUAAASACQAQADANAEQANAFAJAHQAJAHAGAJQAHAJACALQAEAKAAANQABALgDAOIgIAZQgEAOgHALQgFANgIAJQgIAKgIAIQgJAIgKAGQgJAFgLAEIgXAHQgiAGgTAAgAsjA8IAjAAQAOgBALgDQALgDAIgGQAJgGAGgMQAHgLAGgQQAFgOABgLQAAgMgDgIQgDgIgJgEQgJgEgNgBIghAAgAzfB0IBSjnIDYAAIgTA2IiAAAIgNAjIBzAAIgSA0Ih0AAIgMAkICAAAIgTA2gA4EB0IBSjnIBtAAQAUAAARACQAQADAOAEQAMAFAKAHQAKAHAFAJQAHAJACALQADAKAAANQABALgDAOQgCALgFAOQgEAOgHALQgGANgHAJQgIAKgIAIQgJAIgKAGQgKAFgKAEIgYAHQghAGgUAAgA2YA8IAjAAQAPgBAJgDQALgDAIgGQAJgGAHgMQAHgLAFgQQAFgOACgLQAAgMgDgIQgEgIgIgEQgIgEgOgBIgiAAg");
	this.shape_1.setTransform(-9.8,-0.1);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-165.8,-14.2,310.1,26.4);


(lib._23 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFE600").s().p("AvIDeIAQgtQhFgFg4gWIAchPQAYALAhAIQAkAHAfAAIABAAIAXhBIgUgDQg8gHgUgfQgRgeAQgxQASgxAvgXQAsgWBMABIADAAIAOgoIAoAAIgOAqQA7AEAwAUIgbBOQgxgVg7gCIgUA4IANACQA+AJAUAhQASAhgSAyQgUA0gwAXQgqAUhLAAIgPAsgAtyBfQAWgCALgFQALgGAFgLQAKgbgfgGIgIgBgAtuheQgNAEgDALQgFANAEAGQAEAHAOACIARACIASgzQgZABgLAFgAkVDcIBJiFIBtAAIhlCFgALHB2Qgjg3AghYQAfhVAugiQAwglBWAAQBogBAmA8QAiA2ggBYQgfBWguAjQgvAlhWAAQhpAAglg8gANkhNQgRATgSA1QgSAxAGAYQAHAYAgAAQAbAAARgTQAQgUATg1QARgwgGgXQgGgagfAAQgcABgRATgAFHB2Qgjg3AghYQAfhVAugiQAwglBVAAQBpgBAlA8QAjA2ghBYQgfBWgtAjQgwAlhWAAQhoAAglg8gAHjhNQgQATgSA1QgSAxAGAYQAGAYAhAAQAbAAARgTQAQgUATg1QARgwgGgXQgGgagfAAQgdABgRATgAg4B2Qgjg3AhhYQAfhVArgiQAwglBWAAQBpgBAkA8QAjA2ggBYQgfBWguAjQgvAlhWAAQhnAAglg8gABjhNQgRATgSA1QgSAxAGAYQAGAYAhAAQAbAAARgTQAQgUAUg1QARgwgHgXQgGgagfAAQgdABgQATgApaCpIATg0QAIgVAJgMQAKgMAQgKICJhJQAWgNAKgIQAQgNAFgOQAOgphEAAQg0AAg8ARIAdhTQBAgPA7AAQBfAAAlAhQAjAhgWA7QgOAkghAXQgVAQg/AgIhBAjICmAAIgeBTg");
	this.shape.setTransform(-40.4,0);

	// Layer 1 copy
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AvIDeIAQgtQhFgEg4gXIAchPQAYAMAhAGQAkAIAfAAIABAAIAXhBIgUgCQg8gJgUgfQgRgdAQgxQASgxAvgXQAsgVBMAAIADAAIAOgnIAoAAIgOAoQA7AFAwAUIgbBOQgxgVg7gCIgUA4IANACQA+AIAUAiQASAggSA0QgUAzgwAXQgqAUhLgBIgPAtgAtyBfQAWgCALgFQALgFAFgMQAKgagfgGIgIgCgAtuheQgNAEgDALQgFANAEAGQAEAHAOACIARACIASgzQgZABgLAFgAkVDcIBJiFIBtAAIhlCFgALHB2Qgjg3AghYQAfhUAugkQAwglBWABQBoAAAmA7QAiA2ggBZQgfBVguAjQgvAkhWAAQhpABglg8gANkhMQgRASgSA2QgSAvAGAZQAHAZAgAAQAbgBARgTQAQgUATg1QARgvgGgZQgGgZgfAAQgcAAgRAVgAFHB2Qgjg3AghYQAfhUAugkQAwglBVABQBpAAAlA7QAjA2ghBZQgfBVgtAjQgwAkhWAAQhoABglg8gAHjhMQgQASgSA2QgSAvAGAZQAGAZAhAAQAbgBARgTQAQgUATg1QARgvgGgZQgGgZgfAAQgdAAgRAVgAg4B2Qgjg3AhhYQAfhUArgkQAwglBWABQBpAAAkA7QAjA2ggBZQgfBVguAjQgvAkhWAAQhnABglg8gABjhMQgRASgSA2QgSAvAGAZQAGAZAhAAQAbgBARgTQAQgUAUg1QARgvgHgZQgGgZgfAAQgdAAgQAVgApaCpIATg0QAIgVAJgMQAKgMAQgKICJhJQAWgMAKgJQAQgNAFgOQAOgphEAAQg0AAg8ARIAdhSQBAgRA7ABQBfgBAlAjQAjAggWA7QgOAkghAYQgVAPg/AgIhBAjICmAAIgeBTg");
	this.shape_1.setTransform(-38.4,2);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-148.3,-22.2,217.8,46.4);


(lib._3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIqBGQgLgCgUgGIAMghQAKAFAOADQAPADANAAQAPAAAHgCQAHgCACgGQADgGgDgDQgCgDgGgBIgVgEQgNgCgIgFQgJgDgEgFQgDgGAAgIQAAgIADgJQAEgLAHgHQAGgHAKgEQAJgFANgCQANgCAPAAQANAAAWACQAPADAOAFIgMAgQgJgEgNgDQgSgCgKAAQgNAAgGACQgGABgCAGQgCAFACACQACACAGABIAVAEQAJACANAFQAIAFAEAEQAEAHAAAJQAAAIgEAKIgLASQgHAHgKAFQgKAEgMABQgMACgPAAQgcAAgLgCgAmLBHQgLgBgIgDQgIgDgHgEQgGgEgFgGQgEgFgDgHIgCgOQgBgIACgJQABgHAEgJQADgJAFgIQAEgHAGgGIAKgLIANgIQAKgFAUgGIAjgCQAPAAAPACQAOADAMAFIgMAiQgIgEgMgCQgMgDgLAAQgLAAgHACQgJACgHAEQgHAEgFAHQgGAHgDAKQgEAJAAAIQABAHAFAEQAFAFAIACQAIACALAAIAXgBIAVgEIgOAkIgWAEIgXAAIgXgBgAOpBFIABgYIg6AAIgQAYIg4AAIBch/IAHgFQAEgDAFgBIAJgBIBAAAIAACJgAOGAMIAlAAIABg3gALDBFIAmhmIgqAAIANgjICKAAIgNAjIgpAAIgmBmgAHQBFIAAgYIg5AAIgQAYIg5AAIBdh/IAHgFQADgDAFgBIAKgBIA/AAIAACJgAGsAMIAlAAIABg3gAEIBFIATg0IgwAAIgTA0Ig2AAIAyiJIA3AAIgTA0IAwAAIASg0IA3AAIgyCJgAgtBFIAxiJICGAAIgMAgIhPAAIgIAVIBHAAIgLAeIhHAAIgJAWIBQAAIgMAggAjfBFIAziJIBhAAQAJAAAOAEQAIADAFAGQAFAGABAHQABAHgDAJIgGALIgJAJIgLAFIgOACQAIABAFADQAGAEACAFQAEAFAAAHQAAAHgDAHQgCAIgGAFQgEAGgHADQgIAEgJABQgLACgNAAgAidAlIAiAAQAJAAAEgCQAFgCACgFQADgIgEgEQgDgEgKAAIgeAAgAiKgMIAZAAQAJAAAGgDQAFgCACgGQACgGgCgDQgDgEgJAAIgaAAgAkxBFIAziJIA2AAIgyCJgApqBFIAziJICGAAIgMAgIhPAAIgIAVIBHAAIgLAeIhHAAIgJAWIBQAAIgMAggAqyBFIgPgoIgRAAIgPAoIg2AAIAyiJIBdABQAIABAIADQAGABAFADQAFADADADQAEAEACAFIACAJIgBAMIgDAMQgDAIgEAEQgEAGgGAEQgGAEgIACQgGADgJABIAVAwgArHgBIAdAAIAJgCIAGgFQACgDACgFIACgIQAAgEgCgDQgCgCgEgCIgMgBIgRAAgAvPBFIASgzIgfhWIAzAAIASAzIA1gzIA9AAIhiBaIgSAvg");

	// Layer 1 copy
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AIqBGQgLgCgUgGIAMghQAKAFAOADQAPADANAAQAPAAAHgCQAHgCACgGQADgGgDgDQgCgDgGgBIgVgEQgNgCgIgFQgJgDgEgFQgDgGAAgIQAAgIADgJQAEgLAHgHQAGgHAKgEQAJgFANgCQANgCAPAAQANAAAWACQAPADAOAFIgMAgQgJgEgNgDQgSgCgKAAQgNAAgGACQgGABgCAGQgCAFACACQACACAGABIAVAEQAJACANAFQAIAFAEAEQAEAHAAAJQAAAIgEAKIgLASQgHAHgKAFQgKAEgMABQgMACgPAAQgcAAgLgCgAmLBHQgLgBgIgDQgIgDgHgEQgGgEgFgGQgEgFgDgHIgCgOQgBgIACgJQABgHAEgJQADgJAFgIQAEgHAGgGIAKgLIANgIQAKgFAUgGIAjgCQAPAAAPACQAOADAMAFIgMAiQgIgEgMgCQgMgDgLAAQgLAAgHACQgJACgHAEQgHAEgFAHQgGAHgDAKQgEAJAAAIQABAHAFAEQAFAFAIACQAIACALAAIAXgBIAVgEIgOAkIgWAEIgXAAIgXgBgAOpBFIABgYIg6AAIgQAYIg4AAIBch/IAHgFQAEgDAFgBIAJgBIBAAAIAACJgAOGAMIAlAAIABg3gALDBFIAmhmIgqAAIANgjICKAAIgNAjIgpAAIgmBmgAHQBFIAAgYIg5AAIgQAYIg5AAIBdh/IAHgFQADgDAFgBIAKgBIA/AAIAACJgAGsAMIAlAAIABg3gAEIBFIATg0IgwAAIgTA0Ig2AAIAyiJIA3AAIgTA0IAwAAIASg0IA3AAIgyCJgAgtBFIAxiJICGAAIgMAgIhPAAIgIAVIBHAAIgLAeIhHAAIgJAWIBQAAIgMAggAjfBFIAziJIBhAAQAJAAAOAEQAIADAFAGQAFAGABAHQABAHgDAJIgGALIgJAJIgLAFIgOACQAIABAFADQAGAEACAFQAEAFAAAHQAAAHgDAHQgCAIgGAFQgEAGgHADQgIAEgJABQgLACgNAAgAidAlIAiAAQAJAAAEgCQAFgCACgFQADgIgEgEQgDgEgKAAIgeAAgAiKgMIAZAAQAJAAAGgDQAFgCACgGQACgGgCgDQgDgEgJAAIgaAAgAkxBFIAziJIA2AAIgyCJgApqBFIAziJICGAAIgMAgIhPAAIgIAVIBHAAIgLAeIhHAAIgJAWIBQAAIgMAggAqyBFIgPgoIgRAAIgPAoIg2AAIAyiJIBdABQAIABAIADQAGABAFADQAFADADADQAEAEACAFIACAJIgBAMIgDAMQgDAIgEAEQgEAGgGAEQgGAEgIACQgGADgJABIAVAwgArHgBIAdAAIAJgCIAGgFQACgDACgFIACgIQAAgEgCgDQgCgCgEgCIgMgBIgRAAgAvPBFIASgzIgfhWIAzAAIASAzIA1gzIA9AAIhiBaIgSAvg");
	this.shape_1.setTransform(2,2);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-98.9,-7.2,199.9,16.6);


(lib._1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AVABTQgNgCgYgHIAPgnQALAFARAFQASACAQAAQATAAAIgCQAHgDAEgHQADgGgDgEQgDgDgHgCIgagEQgQgDgKgGQgJgFgEgGQgGgHABgJQAAgJAEgMQAEgMAIgJQAIgJALgFQAMgFAPgDQAQgCATgBQAPABAbADQARADARAGIgOAnQgMgFgOgEQgXgDgMAAQgPAAgHADQgHABgCAHQgDAGACADQACADAIABIAZAFQALACAPAGQAKAFAFAGQAFAIgBAKQAAAKgEAMIgHANIgHAJQgIAJgMAFQgLAFgPADQgOACgTABQghgCgOgDgAzwBWQgLgDgLgDQgKgEgHgFQgIgFgEgHQgFgHgDgHQgCgJAAgJQAAgJACgJQABgJAEgJIAJgTIAJgQQAHgJAGgFQAGgHAIgEQAHgEAJgEIASgFQANgDAfgCQAQAAANACQANADAKADQAKAEAHAEQAHAGAFAHQAFAGADAIQACAHAAAKIgCASQgBAJgFAJIgIAUIgKAQIgMAOQgHAGgIAFIgPAIQgIADgLACQgbAEgQABQgQAAgOgCgAzDgsQgIADgGAFQgHAFgFAHQgFAJgFAMQgEAKAAAKQgBAKADAGQADAGAHAEQAHACAMAAQAKAAAHgBQAIgCAGgGQAHgEAFgIQAFgIAFgNQAEgKABgKQABgJgDgHQgEgGgHgDQgGgEgNABQgJAAgIABgA2oBWIgYgGQgJgEgJgFQgHgFgFgGQgFgHgEgIQgCgHgBgKQAAgKACgKQABgJAEgLIAJgUIAMgQQAHgHAHgGQAHgFAIgFQAMgFAYgHQANgCAdgCQASABASADQARADAPAFIgOApIgZgHQgPgDgNAAQgNAAgJACQgKACgJAFQgIAFgGAIQgIAJgEANQgDALAAAIQAAAIAHAHQAFAEAJAEQALACANABQANgBAPgBIAZgFIgRArIgbAFQgMABgQABQgOAAgMgCgATTBTIABgdIhFAAIgTAdIhEAAIBviaIAIgHIAKgDIAMgBIBMAAIAAClgASpAOIAtAAIABhDgAO/BTIAuh7IgzAAIAPgqICmAAIgPAqIgyAAIgtB7gAMZBTIgKh4IgtB4Ig5AAIA9ilIBHAAQAGAAAEACQAEABADADQADAEABAEQABAFABAGIAJBgIAuh5IA5AAIg8ClgAJeBTIAAgdIhEAAIgUAdIhEAAIBviaIAJgHIAKgDIALgBIBMAAIAAClgAI0AOIAsAAIABhDgAElBTIA9ilIBCAAIgtB7IBVAAIgPAqgAB6BTIA8ilIBDAAIgtB7IBVAAIgPAqgAgqBTIAOgmIhhAAIASgtIBMhDQAIgHAGgEQAIgEAJAAIBPAAIgiBbIAYAAIgOAkIgXAAIgOAmgAhAAJIAwAAIAYhEgAkJBTIABgdIhFAAIgTAdIhFAAIBwiaIAIgHIALgDIALgBIBMAAIAAClgAkzAOIAtAAIABhDgAnuBTIgRgwIgVAAIgRAwIhDAAIA9ilIBxABQAJABAJACQAHADAHAEQAGADAEAEQAEAFACAGQACAEABAHIgBAOIgEAOQgEAJgEAGQgFAHgHAFQgIAEgIADIgTAFIAaA6gAoGgBIAigBQAGgBAFgCQAEgCADgDQADgEADgGIACgKQAAgEgCgDQgCgEgGgBQgFgCgKAAIgUAAgAsyBTIA+ilIBUAAQANAAAMACQAKAAAJADQAJAEAGADQAGAEAFAFQADAFADAHQACAFAAAIIgBAOIgFAQIgHANQgDAGgGAFIgJAJIgMAHQgMAFgQADQgOABgUABIgmAAIgOAngArTAGIARAAQALAAAGgCQAIAAAEgDQAEgBAEgFQADgEACgHIAEgMQAAgGgDgDQgDgDgFgCQgFgCgKAAIgSAAgAuUBTIAsh2IhXB2Ig4AAIAAh6IgtB6Ig4AAIA9ilIBGAAQAHAAAFACQAFABACADQACAEACAFIAAAMIACBHIBFhiIBmAAIg9Clg");

	// Layer 1 copy
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AVBBUQgOgDgYgHIAOgnQANAGAQADQASADAQABQASAAAIgDQAJgCADgIQACgGgCgEQgCgEgJgBIgZgFQgPgCgLgGQgJgFgEgFQgGgHABgKQAAgKAEgLQAEgMAIgJQAIgIALgGQAMgFAPgDQAQgDASAAQAQAAAbAEQARADARAGIgOAmQgMgEgPgEQgWgDgMAAQgPAAgHACQgHADgCAFQgDAGACADQACAEAIABIAZAEQALADAQAGQAJAFAFAGQAFAIAAAKQgBAKgFAMIgGAMIgHAKQgHAJgNAFQgMAFgOADQgOACgTABQghgCgNgCgAzvBWQgNgDgKgEQgKgDgHgGQgIgEgEgHQgFgHgDgIQgCgHAAgKQAAgJABgJQACgJAEgKIAJgSIAKgRQAFgHAHgGQAGgGAIgFQAIgEAIgDIASgGQAOgDAegCQAQABANACQANACAJADQAKAEAIAEQAHAGAFAHQAFAHACAHQACAHABAJIgCATQgCAJgDAJIgJAUIgKAQIgNAOQgFAGgIAFIgQAIQgJADgKACQgbAEgQABQgQgBgNgBgAzCgsQgJADgHAEQgFAGgGAHQgFAJgEAMQgFAKgBAKQAAAJADAHQADAGAHADQAIADALAAQAKAAAHgCQAJgBAFgGQAGgEAGgIQAGgIAEgMQAEgLABgKQABgJgDgHQgDgGgHgDQgIgDgLgBQgLAAgGACgA2pBWQgMgDgLgDQgKgDgHgGQgIgFgGgGQgFgHgDgIQgDgIAAgJQAAgJACgLQABgJAFgLIAJgUIALgQQAGgHAIgGQAIgFAHgFQALgGAZgGQAOgCAcgCQASAAASAEQASADAOAFIgOApIgZgHQgPgDgNAAQgMAAgKACQgLADgIAEQgIAFgGAJQgIAIgEANQgDAKAAAJQAAAJAHAGQAEAEALAEQAJADAOgBQAOAAAOgCIAYgEIgQArIgbAFQgMABgQABQgPgBgMgBgATUBTIAAgdIhFAAIgTAdIhFAAIBwiaQAEgEAFgDIAKgDIALgBIBMAAIAAClgASpAOIAtAAIABhDgAO/BTIAuh7Ig0AAIAQgqICmAAIgPAqIgyAAIgtB7gAMZBTIgKh4IgtB4Ig5AAIA9ilIBHAAQAGAAAEABQAFACACAEQADADABAFQACAEgBAGIAKBgIAuh5IA5AAIg8ClgAJeBTIABgdIhGAAIgTAdIhEAAIBwiaQAEgEAEgDIAKgDIALgBIBMAAIAAClgAI0AOIAsAAIABhDgAElBTIA9ilIBCAAIgtB7IBVAAIgPAqgAB6BTIA9ilIBCAAIgtB7IBVAAIgPAqgAgqBTIAOgmIhhAAIARgtIBOhCQAHgIAGgEQAIgEAIAAIBQAAIgiBbIAYAAIgOAkIgXAAIgOAmgAhAAJIAwAAIAXhEgAkIBTIAAgdIhFAAIgTAdIhFAAIBwiaIAJgHIAKgDIAKgBIBNAAIAAClgAkzAOIAtAAIAAhDgAnuBTIgRgxIgVAAIgSAxIhBAAIA8ilIBxABQAJABAJACQAHADAHADQAFADAFAFQAEAFACAFQACAFABAHIAAAOIgFAPQgEAIgFAGQgFAHgGAFQgIAFgJADIgSAEIAaA6gAoGgBIAigBQAGgBAFgCQAEgCADgDQAEgEACgGIACgKQABgEgDgDQgDgEgFgBQgGgCgJAAIgUAAgAsyBTIA9ilIBVAAQANAAALABQAMABAIAEQAJADAGADQAGAEAEAFQAEAGADAGQACAGAAAGIgBAPIgFAQIgHANQgDAGgFAFIgKAJIgMAHQgMAFgQADQgOACgUgBIgmAAIgOAogArTAGIASAAQAJgBAIgBQAGgBAFgCQAFgBADgEQADgFACgHIAEgMQAAgGgDgDQgCgDgFgCQgGgCgKAAIgSAAgAuUBTIArh3IhVB3Ig5AAIAAh6IgtB6Ig5AAIA+ilIBHAAQAGAAAFABQAEACADAEQACADACAFIAAAMIACBHIBFhiIBmAAIg9Clg");
	this.shape_1.setTransform(2,2);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-151.5,-8.8,305.1,19.6);


// stage content:
(lib._728x90_op = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_139 = function() {
		/* Stop at This Frame
		The  timeline will stop/pause at the frame where you insert this code.
		Can also be used to stop/pause the timeline of movieclips.
		*/
		
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(139).call(this.frame_139).wait(5));

	// FlashAICB
	this.instance = new lib.LOGOO();
	this.instance.setTransform(893.2,42.7);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(120).to({_off:false},0).wait(1).to({regY:2,x:863.7,y:44.7},0).wait(1).to({x:834.3},0).wait(1).to({x:804.8},0).wait(1).to({x:775.4},0).wait(1).to({x:745.9},0).wait(1).to({x:716.5},0).wait(1).to({x:687},0).wait(1).to({x:657.6},0).wait(1).to({x:628.1},0).wait(12).to({_off:true},1).wait(2));

	// FlashAICB
	this.instance_1 = new lib.Más();
	this.instance_1.setTransform(820.2,43,1.397,1.397);
	this.instance_1._off = true;
	new cjs.ButtonHelper(this.instance_1, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(116).to({_off:false},0).wait(1).to({scaleX:1.38,scaleY:1.38,x:785.8},0).wait(1).to({scaleX:1.36,scaleY:1.36,x:751.4},0).wait(1).to({scaleX:1.34,scaleY:1.34,x:717.1},0).wait(1).to({scaleX:1.32,scaleY:1.32,x:682.6},0).wait(1).to({scaleX:1.3,scaleY:1.3,x:648.3},0).wait(1).to({scaleX:1.28,scaleY:1.28,x:613.9},0).wait(1).to({scaleX:1.26,scaleY:1.26,x:579.5},0).wait(1).to({scaleX:1.25,scaleY:1.25,x:545.1},0).wait(1).to({scaleX:1.23,scaleY:1.23,x:510.8},0).wait(1).to({scaleX:1.21,scaleY:1.21,x:476.4},0).wait(1).to({scaleX:1.19,scaleY:1.19,x:442},0).wait(17));

	// de descuento
	this.instance_2 = new lib._24();
	this.instance_2.setTransform(-211.5,71.5);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(107).to({_off:false},0).wait(1).to({regX:-10.8,regY:-1,x:-179.3,y:70.5},0).wait(1).to({x:-136.3},0).wait(1).to({x:-93.3},0).wait(1).to({x:-50.4},0).wait(1).to({x:-7.4},0).wait(1).to({x:35.6},0).wait(1).to({x:78.5},0).wait(1).to({x:121.5},0).wait(1).to({x:164.5},0).wait(1).to({x:207.5},0).wait(27));

	// Layer 12
	this.instance_3 = new lib._23();
	this.instance_3.setTransform(-256.1,31);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(99).to({_off:false},0).wait(1).to({regX:-39.4,regY:1,x:-252.5,y:32},0).wait(1).to({x:-209.5},0).wait(1).to({x:-166.5},0).wait(1).to({x:-123.5},0).wait(1).to({x:-80.5},0).wait(1).to({x:-37.6},0).wait(1).to({x:5.4},0).wait(1).to({x:48.4},0).wait(1).to({x:91.4},0).wait(1).to({x:134.4},0).wait(32).to({_off:true},1).wait(2));

	// y recibe hasta
	this.instance_4 = new lib._3();
	this.instance_4.setTransform(-139.4,57.4);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(55).to({_off:false},0).wait(1).to({regX:1,regY:1,x:-98.8,y:58.4},0).wait(1).to({x:-59.2},0).wait(1).to({x:-19.6},0).wait(1).to({x:19.9},0).wait(1).to({x:59.5},0).wait(1).to({x:99.1},0).wait(1).to({x:138.7},0).wait(1).to({x:178.3},0).wait(1).to({x:217.9},0).wait(1).to({x:257.5},0).wait(34).to({_off:true},1).wait(44));

	// Compra 4 llantas
	this.instance_5 = new lib._1();
	this.instance_5.setTransform(-222.3,34.2);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(48).to({_off:false},0).wait(1).to({regX:1,regY:1,x:-185.3,y:35.2},0).wait(1).to({x:-149.3},0).wait(1).to({x:-113.3},0).wait(1).to({x:-77.3},0).wait(1).to({x:-41.3},0).wait(1).to({x:-5.3},0).wait(1).to({x:30.6},0).wait(1).to({x:66.7},0).wait(1).to({x:102.7},0).wait(1).to({x:138.7},0).wait(1).to({x:174.7},0).wait(40).to({_off:true},1).wait(44));

	// Layer 5
	this.instance_6 = new lib.TROCC();
	this.instance_6.setTransform(-80,195.9);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(25).to({_off:false},0).wait(1).to({regX:-0.1,regY:-0.8,scaleX:0.94,scaleY:0.94,x:-54.5,y:176.5},0).wait(1).to({scaleX:0.88,scaleY:0.88,x:-27.3,y:159.2},0).wait(1).to({scaleX:0.82,scaleY:0.82,x:0.4,y:142.8},0).wait(1).to({scaleX:0.76,scaleY:0.76,x:28.5,y:127.2},0).wait(1).to({scaleX:0.7,scaleY:0.7,x:56.9,y:112.2},0).wait(1).to({scaleX:0.64,scaleY:0.64,x:85.6,y:97.9},0).wait(1).to({scaleX:0.57,scaleY:0.57,x:114.7,y:84.2},0).wait(1).to({scaleX:0.51,scaleY:0.51,x:144.2,y:71.3},0).wait(1).to({scaleX:0.45,scaleY:0.45,x:174.2,y:59.4},0).wait(1).to({scaleX:0.39,scaleY:0.39,x:204.5,y:48.5},0).wait(1).to({scaleX:0.33,scaleY:0.33,x:235.1,y:38.6},0).wait(1).to({scaleX:0.27,scaleY:0.27,x:266.1,y:29.5},0).wait(1).to({scaleX:0.21,scaleY:0.21,x:297.4,y:21.5},0).wait(1).to({scaleX:0.15,scaleY:0.15,x:329.3,y:14.7},0).wait(1).to({scaleX:0.09,scaleY:0.09,x:360,y:10.6},0).wait(51).to({_off:true},1).wait(52));

	// A3.jpg
	this.instance_7 = new lib.Symbolc();
	this.instance_7.setTransform(609.1,-170);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(7).to({_off:false},0).wait(1).to({regX:-2,x:607.1,y:-154.6},0).wait(1).to({y:-139.2},0).wait(1).to({y:-123.9},0).wait(1).to({y:-108.5},0).wait(1).to({y:-93.2},0).wait(1).to({y:-77.8},0).wait(1).to({y:-62.5},0).wait(1).to({y:-47.1},0).wait(1).to({y:-31.7},0).wait(1).to({y:-16.4},0).wait(1).to({y:-1},0).wait(1).to({y:14.3},0).wait(1).to({y:29.6},0).wait(1).to({y:45},0).wait(120).to({_off:true},1).wait(2));

	// A2.jpg
	this.instance_8 = new lib.Symbolb();
	this.instance_8.setTransform(365,215);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(3).to({_off:false},0).wait(1).to({y:201.9},0).wait(1).to({y:188.8},0).wait(1).to({y:175.7},0).wait(1).to({y:162.7},0).wait(1).to({y:149.6},0).wait(1).to({y:136.5},0).wait(1).to({y:123.5},0).wait(1).to({y:110.4},0).wait(1).to({y:97.3},0).wait(1).to({y:84.2},0).wait(1).to({y:71.1},0).wait(1).to({y:58.1},0).wait(1).to({y:45},0).wait(125).to({_off:true},1).wait(2));

	// A1.jpg
	this.instance_9 = new lib.Symbola();
	this.instance_9.setTransform(120.9,-170);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(1).to({y:-150.5},0).wait(1).to({y:-130.9},0).wait(1).to({y:-111.4},0).wait(1).to({y:-91.8},0).wait(1).to({y:-72.3},0).wait(1).to({y:-52.7},0).wait(1).to({y:-33.2},0).wait(1).to({y:-13.6},0).wait(1).to({y:5.9},0).wait(1).to({y:25.5},0).wait(1).to({y:45},0).wait(130).to({_off:true},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(362.9,-170,244.1,90);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;