(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 120,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/1.jpg", id:"_1"},
		{src:"images/2.jpg", id:"_2"},
		{src:"images/3.jpg", id:"_3"},
		{src:"images/Camioneta120.png", id:"Camioneta120"}
	]
};



// symbols:



(lib._1 = function() {
	this.initialize(img._1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,120,200);


(lib._2 = function() {
	this.initialize(img._2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,120,200);


(lib._3 = function() {
	this.initialize(img._3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,120,200);


(lib.Camioneta120 = function() {
	this.initialize(img.Camioneta120);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,464,401);


(lib.Texto_1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEE32B").s().p("AnSBlIAHgVQgRAAgPgDQgOgEgOgEIAOglQALAGAQADQARADAPAAIAAAAIALgdIgJgCQgPgCgJgEQgKgFgEgGQgEgGAAgKQAAgJADgLQAFgKAHgJQAIgIALgFQALgFAOgDQAOgCASAAIACAAIAGgSIATAAIgGATQAOABANACQAMADAMAEIgNAkQgKgEgNgDQgOgDgOAAIgKAaIAGABQAKABAPAGQAJAFAFAGQAEAIAAAJQAAAJgEAMIgGAMIgHAJQgIAIgLAFQgLAEgOADQgNACgSAAIgHAUgAmqAsQALgCAFgCQAFgCACgFQADgHgCgDQgDgFgHgBIgEAAgAmogqQgGACgCAFQgCAFACAEQACACAHABIAHABIAJgXQgMAAgFADgAiJBkIAjg9IAzAAIgvA9gAGFBPQgKgCgJgEQgIgDgGgFQgGgFgFgGQgEgGgCgIQgCgIAAgHIACgSIAFgRQAFgNALgUIAKgMIALgKIAMgIIAPgFQAKgDAagBQANAAALACQAKACAJADQAIADAGAFQAGAGAEAGQAFAGACAHQACAIAAAIIgCASIgFARQgKAYgGAJIgKAMIgLAKQgGAFgGADQgHADgIACQgWAEgOAAQgNAAgLgCgAGtgqQgFADgEAEQgEAFgEAIIgJAVQgEAJgBAJQgCAIACAFQABAHAFACQAEADAIAAQAHAAAFgCQAFgCAEgFQAEgFAEgIIAJgUQAEgJABgJQACgIgCgGQgBgFgFgEQgEgDgIAAQgHAAgFACgADOBPQgKgCgJgEQgIgDgGgFQgGgFgFgGQgEgGgCgIQgCgIAAgHIACgSIAFgRQAFgNALgUIAKgMIALgKIAMgIIAPgFQAKgDAagBQANAAALACQAKACAJADQAIADAGAFQAGAGAEAGQAFAGACAHQACAIAAAIIgCASIgFARQgKAYgGAJIgKAMIgLAKQgGAFgGADQgHADgIACQgWAEgOAAQgNAAgLgCgAD2gqQgFADgEAEQgEAFgEAIIgJAVQgEAJgBAJQgCAIACAFQABAHAFACQAEADAIAAQAHAAAFgCQAFgCAEgFQAEgFAEgIIAJgUQAEgJABgJQACgIgCgGQgBgFgFgEQgEgDgIAAQgHAAgFACgAAXBPQgKgCgJgEQgGgDgGgFQgGgFgFgGQgEgGgCgIQgCgIAAgHIACgSIAFgRQAFgNALgUIAIgMIALgKIAMgIIAPgFQAKgDAagBQANAAALACQAKACAJADQAIADAGAFQAGAGAEAGQAFAGACAHQACAIAAAIIgCASIgFARQgKAYgGAJIgKAMIgLAKQgGAFgGADQgHADgIACQgWAEgOAAQgNAAgLgCgAA/gqQgFADgEAEQgEAFgEAIIgJAVQgEAJgBAJQgCAIACAFQABAHAFACQAEADAIAAQAHAAAFgCQAFgCAEgFQAEgFAEgIIAJgUQAEgJABgJQACgIgCgGQgBgFgFgEQgEgDgIAAQgHAAgFACgAkkBNIAJgYQAEgKAEgFQAFgGAIgEIBBggIAPgKQAIgGACgGIABgIQAAgDgDgDQgDgDgFgBQgGgBgKAAQgPAAgPACIgXAGIAOgmQAPgDAMgCQAPgCAQAAQAPAAAYAEQAIACAGADQAGACAEAEQAEAEADAEIADAKIAAAMIgEAMQgDAJgGAHQgFAHgIADIgSALIg1AbIBOAAIgNAmg");
	this.shape.setTransform(-1.2,24.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACDEUQgKgCgQgFIAKgbQAIADAMADQANADALAAQANAAAGgCQAGgCACgFQACgFgCgDQgCgCgFgBIgSgDQgLgCgIgEQgGgEgEgFQgDgFAAgHQAAgHADgIQADgIAGgGQAFgGAJgEQAIgEALgCQAKgCAOAAQALAAASADQAMACAMAEIgJAbQgIgDgLgCQgQgDgIAAQgLAAgFACQgFABgCAEQgBAFABACQABACAGABIASADQAHACALAEQAHAEAEAGQADAFAAAHQAAAHgDAJIgFAIIgFAHQgGAHgIADQgIAEgLACQgKABgNAAQgXgBgKgBgAHIETIABgUIgxAAIgOAUIgwAAIBPhuQADgDADgBQADgCAEgBIAIgBIA2AAIAAB2gAGqDiIAfAAIACgwgAEFETIAhhYIglAAIALgeIB2AAIgLAeIgjAAIggBYgAA2ETIABgUIgxAAIgMAUIgwAAIBNhuQADgDADgBQADgCAEgBIAIgBIA2AAIAAB2gAAYDiIAfAAIACgwgAhyETIARgsIgpAAIgQAsIguAAIArh2IAuAAIgQAsIAoAAIAQgsIAvAAIgrB2gAl5ETIArh2IByAAIgKAbIhDAAIgHASIA9AAIgKAcIg9AAIgHASIBEAAIgKAbgAoSETIArh2IA5AAIAUABQAJACAGACQAHADAFADQAFAEADAEQAEAFABAFQACAFAAAGQAAAGgBAHIgEAOIgGANIgHALIgJAJIgJAHIgLAFIgMAEQgSACgKAAgAnZD3IASAAQAIAAAFgCQAGgBAEgEQAFgDADgGQAEgFADgJQADgIAAgFQABgGgCgEQgCgEgFgCQgEgCgHAAIgSAAgAG2AsIgNgDIgKgFIgHgHQgDgEgCgFIgBgJIABgLIADgKIAFgLIAGgKIAHgIIAIgGIAKgEIAKgDQAIgCASgBIARABIANADIAKAGIAHAGIAEAJQACAEAAAGIgBAKIgEAKIgFALQgCAGgEAEIgHAIIgIAGIgJAFIgLADQgQACgJAAIgRgBgAHQgeIgIAEQgEADgDAFQgDAFgDAHQgCAGgBAEQAAAGACAEQABADAFACQAEACAHAAIAKgBQAEgBAEgDQAEgDADgFQADgEACgFQADgIAAgFQABgGgCgDQgCgEgEgCQgEgCgHAAIgKABgAgkAsIgLgCIgJgEIgGgFIgEgGIgCgIIAAgIIACgKIAVg1IAmAAIgVA3IgBAIQgBADACACQABADAEABIAHABIAGgBQAEgBACgCIAEgFIAEgJIAUg3IAnAAIgaBBIgFAKIgHAHIgHAGIgJAEIgJADIgWACIgOgBgAiNAsIgOgDIgKgFQgEgDgDgEQgDgDgCgFIgCgKIABgLIADgLIAGgMIAGgJIAIgIIAJgGQAHgDAOgEQAIgBAQgBIAVACIATAFIgJAYQgGgDgIgBQgIgCgIAAQgHAAgGABQgGABgFADQgFADgDAFQgEAFgDAIQgCAFAAAFQABAFADADQADADAGACQAFABAJAAIAQgBIAOgCIgJAZIgQADIgQAAIgQgBgAkSArQgIgBgNgFIAIgWQAHADAKACQAKACAJAAQALAAAFgBQAFgCABgEQACgEgCgCQgBgCgFgBIgOgDQgKgBgFgCQgGgCgDgFQgDgEABgFQAAgGACgGQACgHAFgGQAFgEAHgEQAGgDAJgBQAJgCALAAIAYACQAKACAKADIgIAXQgGgDgJgCQgNgCgHAAQgJAAgEABQgEACgCADQgBAEABABQABACAFABIAOADQAHABAJAEQAGADACAEQADADAAAGQAAAGgDAHIgDAHIgFAFQgEAFgHAEQgHACgJACQgIABgLAAQgTAAgIgCgAE6ArIAbhHIgeAAIAJgYIBhAAIgJAYIgdAAIgaBHgADaArIgGhFIgaBFIghAAIAjhfIApAAIAGABIAEACIADAFIAAAGIAGA4IAbhGIAhAAIgkBfgAAsArIAjhfIBeAAIgIAWIg3AAIgGAPIAyAAIgIAUIgyAAIgGAPIA4AAIgIAXgAmSArIAjhfIBeAAIgIAWIg3AAIgGAPIAyAAIgIAUIgyAAIgGAPIA4AAIgIAXgAoQArIAjhfIAvAAIAQABIANADIAKAFIAGAGIAEAIQACAFAAAFIgBAKIgEAJIgEALIgGAJIgHAIIgIAFIgJAFIgKADIgXACgAniATIAQAAIAKgBQAFgBADgDQAEgDADgFIAFgJIADgLQAAgFgBgDQgCgEgDgBQgEgCgGAAIgOAAgAD5iEIgMgDQgGgBgEgDQgFgCgDgEIgFgHIgCgIIAAgKIADgLIAYhAIArAAIgXBCQgCAFAAAEQgBAEACACQACADADABIAJABIAHgBIAHgDIAFgGQADgEACgGIAYhCIAsAAIgdBNIgGALIgIAJIgIAHIgKAEIgLAEQgRACgKAAIgQgBgAneiEIgPgEQgHgCgFgEIgIgIQgDgEgBgFQgCgFAAgGIABgNIAEgNIAGgNIAGgLIAIgJIAKgHIAKgFIAMgEQAJgCAVAAIATABIAPAEQAGACAFADIAIAIIAFAKQACAFAAAGIgBAMIgEAOIgGANIgHAKIgIAJIgJAHIgLAGIgMADQgSADgLAAQgKAAgJgBgAnAjbQgGACgEADQgEADgDAFQgEAGgDAIQgDAIAAAGQgBAHACAEQACAEAFACQAFADAIAAQAGAAAFgCQAFgBAEgDQAFgEADgFQAEgFADgIQADgJAAgGQABgGgDgEQgCgFgEgCQgFgCgIAAIgLABgAGhiGIgHhRIgeBRIglAAIAohvIAvAAQAEAAADACIAFADIACAFIABAHIAHBBIAehSIAmAAIgpBvgABJiGIgHhRIgdBRIglAAIAnhvIAwAAQAEAAADACIAEADIADAFIABAHIAHBBIAdhSIAmAAIgoBvgAh7iGIAohvIBpAAIgJAaIg9AAIgGARIA3AAIgIAZIg5AAIgGASIA/AAIgJAZgAjUiGIAehTIgiAAIAKgcIBvAAIgLAcIggAAIgfBTgAl8iGIAohvIBNAAQAIAAAKADQAIADAEAEQADAFABAGQABAGgDAHQgBAFgDAEQgDAEgEACQgEADgFACQgFACgGAAQAGABAEADQAEADADAEQACAEAAAGQABAFgDAGQgCAGgEAFQgEAEgFADQgGADgIABQgIABgLAAgAlIifIAbAAQAHAAAEgCQAEgCABgEQACgGgCgDQgDgDgIAAIgYAAgAk5jIIAUAAQAIAAAEgCQAEgCACgFQACgFgDgCQgCgDgHAAIgVAAgAgvj8IAdgZIAnAAIgfAZg");
	this.shape_1.setTransform(0.1,-17.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AnfGQIAIgVQgSgBgOgDQgOgDgOgFIANgkQAMAFAQADQARAEAPgBIAAAAIALgdIgJgBQgPgCgKgFQgJgFgEgHQgFgHAAgJQABgJADgLQAEgLAIgIQAIgJALgFQAKgFAPgDQAOgCASAAIACAAIAGgSIATAAIgGATQAOABANADQALADAMAEIgMAkQgKgEgNgDQgPgDgOgBIgKAaIAHABQAKACAPAGQAJAEAEAIQAFAIAAAJQgBAKgEAMIgFALIgHAJQgIAJgLAEQgLAFgOACQgOACgRAAIgHAVgAm2FWQAKgBAGgCQAFgDACgFQACgGgBgEQgDgEgIgBIgEgBgAm1D/QgFABgCAFQgCAGACADQACADAGABIAIABIAJgYQgMABgGADgAiVGPIAjg9IAzAAIgwA9gAF5F5QgLgCgIgDQgJgDgGgFQgFgGgFgGQgEgGgCgHQgCgIAAgIIABgSIAGgTQAFgMALgVIAKgMIALgKIAMgIIAPgEQAKgEAagBQANABAKABQALACAJAEQAHADAHAFQAGAFAEAGQAEAHACAHQACAIAAAIIgBARIgGATQgJAYgGAJIgKAMIgLALQgGAEgGADQgIADgHADQgXADgOAAQgMAAgLgCgAGhD/QgFADgFAEQgDAFgFAIIgIAUQgEALgBAJQgCAIACAGQABAGAEADQAFACAIAAQAHAAAEgBQAFgDAFgFQAEgFAEgHIAJgVQAEgLABgJQABgIgBgFQgBgGgFgDQgEgDgIAAQgHAAgFACgADCF5QgLgCgIgDQgJgDgFgFQgHgGgEgGQgEgGgCgHQgCgIAAgIIACgSIAFgTQAFgMALgVIAJgMIALgKIANgIIAOgEQALgEAagBQAMABALABQALACAIAEQAJADAGAFQAGAFAEAGQAFAHACAHQACAIAAAIIgCARIgGATQgJAYgHAJIgJAMIgLALQgGAEgGADQgIADgHADQgXADgOAAQgMAAgLgCgADqD/QgFADgEAEQgFAFgDAIIgJAUQgEALgCAJQgBAIABAGQACAGAEADQAFACAIAAQAGAAAGgBQAFgDAEgFQAEgFAEgHIAJgVQAEgLABgJQACgIgCgFQgCgGgEgDQgEgDgIAAQgHAAgFACgAALF5QgKgCgHgDQgIgDgHgFQgFgGgFgGQgEgGgCgHQgCgIAAgIIABgSIAGgTQAFgMALgVIAKgMIAIgKIANgIIAOgEQALgEAagBQANABALABQAKACAJAEQAHADAHAFQAGAFAEAGQAEAHACAHQACAIABAIIgCARIgFATQgLAYgGAJIgJAMIgLALQgGAEgHADQgGADgIADQgWADgOAAQgNAAgLgCgAAzD/QgFADgFAEQgDAFgEAIIgJAUQgEALgBAJQgCAIACAGQABAGAFADQAEACAIAAQAGAAAFgBQAGgDAEgFQAEgFAEgHIAIgVQAFgLABgJQABgIgBgFQgCgGgEgDQgFgDgHAAQgHAAgFACgAkwF4IAJgYQAEgKAEgFQAFgGAHgEIBBgiIAQgKQAHgHACgGIACgHQAAgDgDgDQgDgDgGgBQgGgBgJgBQgPABgPACIgXAFIAOglQAPgEAMgCQAPgCAPAAQAQAAAYAFQAHACAGACQAHADADAEQAFAEACAEIADAKIAAALIgDAMQgEAKgFAGQgGAHgHAGIgSALIg1AbIBOAAIgNAmgACECaQgKgBgQgFIAKgbQAJADALACQANAEAMAAQANAAAFgDQAGgCACgEQACgFgCgDQgBgCgGgCIgSgDQgLgBgHgFQgHgDgDgGQgEgEAAgIQAAgGADgIQAEgJAFgFQAGgHAIgDQAIgFALgBQALgCANAAQALAAASACQAMACANAFIgKAbQgIgEgLgCQgQgCgIAAQgLgBgFACQgFACgBAEQgCAEACADQAAACAGABIASADQAIACAKAEQAIAEADAFQADAGAAAHQAAAHgDAIIgFAJIgFAHQgFAHgJADQgIADgKADQgLABgNAAQgXgBgKgCgAHKCaIAAgVIgxAAIgNAVIgxAAIBPhuQADgDAEgBQADgCADgBIAIgBIA2AAIAAB2gAGrBpIAgAAIABgwgAEGCaIAhhYIgkAAIALgeIB1AAIgKAeIgjAAIghBYgAA3CaIABgVIgxAAIgMAVIgvAAIBMhuQADgDADgBQADgCAEgBIAIgBIA2AAIAAB2gAAaBpIAeAAIACgwgAhxCaIARgtIgpAAIgPAtIgvAAIArh2IAuAAIgQAsIAoAAIARgsIAuAAIgrB2gAl3CaIArh2IBxAAIgKAbIhDAAIgHASIA9AAIgKAbIg8AAIgIATIBEAAIgKAbgAoQCaIArh2IA4AAIAUABQAJABAHADQAGADAFADQAGAEACAEQAEAFACAFQABAFAAAGQAAAGgBAHIgEAOIgFANIgIALIgIAIIgKAHIgLAGIgMADQgSADgKAAgAnYB9IASAAQAIABAGgCQAFgCAFgDQAEgEAEgFQADgFADgJQADgIABgGQAAgFgCgFQgCgDgEgCQgEgCgIgBIgRAAgAG4hLIgOgEIgKgEIgHgIQgDgDgBgFIgCgKIACgKIACgMIAGgMIAFgJIAHgIIAIgGIAKgFIAKgCQAJgCARgBIARABIANADIAKAGIAHAGIAFAIQABAFAAAFIgBALIgEAMIgEALQgDAGgEADIgHAIIgHAHIgKAEIgLAEQgPACgKAAIgQgBgAHRiXIgIAEQgEADgCAFQgEAEgDAIQgCAGAAAGQgBAFACAEQACAEAEACQAEACAHAAIAKgBQAEgCAEgCQAEgDADgFQADgEACgIQADgHABgGQAAgFgBgEQgDgDgDgCQgFgCgGAAIgLABgAgihLIgLgCIgJgEIgHgFIgEgGIgCgIIAAgJIACgJIAVg3IAmAAIgUA4IgCAIQAAAEABACQABACAEABIAHABIAHgBQADAAACgCIAEgGIAEgJIAVg4IAmAAIgaBDIgFAJIgGAIIgIAGIgIAEIgKADIgWACIgNgBgAiMhLIgNgDIgLgFQgEgDgDgEQgDgEgCgFIgCgKIABgLIADgNIAGgLIAHgKIAIgIIAJgFQAGgEAPgDQAHgCARAAIAVACIASAEIgJAZQgFgDgJgCQgIgCgIAAQgHABgGABQgGABgFADQgEADgEAFQgEAFgDAHQgCAIAAAEQABAGADADQAEADAFACQAFABAJAAIAQgBIAOgCIgJAYIgQAEIgQAAIgQgBgAkRhMQgHgBgOgFIAIgWQAHADAKACQAKACAKAAQALAAAEgCQAFgBABgEQACgEgCgCQgBgDgEAAIgPgDQgKgBgFgDQgGgEgDgEQgCgEAAgFQAAgGACgHQADgGAEgGQAFgFAHgDQAHgDAIgBQAKgCAKAAIAYACQALACAJADIgIAXQgGgDgJgCQgNgCgGgBQgKABgEABQgEACgCADQgBADABACQACACAEABIAPADQAGAAAJAEQAGADACAFQAEAEgBAGQAAAGgDAIIgDAHIgFAFQgEAFgHADQgHADgJACQgHABgMAAQgSgBgJgBgAE8hMIAahKIgdAAIAJgXIBgAAIgJAXIgdAAIgaBKgADbhMIgGhHIgaBHIghAAIAjhhIApAAIAGABIAFACIACAFIABAGIAGA6IAahIIAhAAIgkBhgAAuhMIAjhhIBdAAIgIAVIg3AAIgFAQIAxAAIgIAWIgyAAIgGAPIA4AAIgIAXgAmRhMIAjhhIBeAAIgIAVIg3AAIgFAQIAxAAIgIAWIgyAAIgGAPIA4AAIgIAXgAoPhMIAjhhIAvAAIAQABIANACIAKAGIAGAGIAFAIQABAEAAAFIgBALIgEALIgEALIgGAJIgHAIIgIAFIgIAEIgLADIgWADgAnhhkIAQAAIAKgBQAFgBADgEQAEgCADgFIAFgLIADgMQAAgEgBgEQgBgDgEgBQgEgDgFAAIgPAAgAD7j9IgNgDQgGgBgEgDQgEgDgEgDIgEgHIgCgIIAAgKIADgLIAXhAIArAAIgXBCQgCAEAAAFQAAAEACACQABADADABIAJABIAIgBIAGgDIAFgGQAEgFACgFIAYhCIArAAIgdBNIgGALIgHAIIgJAIIgKAEIgLAEQgRACgKAAIgPgBgAncj9IgQgEQgHgCgEgEIgIgIQgDgEgCgFQgCgFAAgGIABgNIAEgNIAGgOIAGgKIAJgJIAJgHIAKgFIAMgEQAKgCAUgBIATABIAPAFQAGACAGADIAIAIIAEAJQACAGAAAFIgBANIgEANIgGAOIgHAKIgHAJIgJAHIgMAFIgMAEQgRADgLAAQgLAAgIgBgAm/lUQgGACgDADQgFADgDAFQgDAGgEAHQgDAJAAAGQgBAHACADQACAFAFACQAFACAIAAQAGAAAGgBQAEgBAFgEQAEgDADgFQAEgGADgHQADgJABgGQAAgHgDgEQgCgEgEgCQgFgCgIAAIgLABgAGij/IgHhRIgeBRIglAAIAohvIAwAAQADAAAEACIAEADIACAFIABAHIAHBBIAehSIAmAAIgpBvgABKj/IgHhRIgdBRIglAAIAnhvIAwAAQAEAAADACIAFADIACAFIABAHIAHBBIAdhSIAnAAIgpBvgAh6j/IAphvIBoAAIgJAZIg9AAIgGARIA3AAIgIAaIg4AAIgHASIA/AAIgJAZgAjTj/IAehTIgiAAIALgcIBuAAIgLAcIggAAIgfBTgAl7j/IAohvIBOAAQAHAAALADQAHACAEAFQAEAEAAAHQABAGgDAGQgBAFgDAEQgDAEgEADQgEADgFABQgFACgGABQAGABAFADQAEADACAEQACAEABAGQAAAFgCAGQgDAGgDAEQgEAFgGACQgGADgIACQgIABgLAAgAlHkYIAbAAQAHgBAEgBQAEgCABgFQACgFgCgEQgDgCgHAAIgZAAgAk4lCIAUAAQAIAAAEgCQAEgCACgEQACgFgDgCQgBgEgIAAIgUAAgAgtl1IAdgZIAmAAIgfAZg");
	this.shape_2.setTransform(0.3,-3.8);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-53.2,-45.1,106.8,81.3);


(lib.LOGO_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("Ag9BwQgFgGAFgGIAJgOIADgFQgGgGAAgGIAAgCQAAgEACgCIADgEQgCgIACgEQADgIAFgDIACgDQgGgNAJgKQgDgIAHgIQgDgGACgIQgCgCgBgFQgJgBgGgIQgGgBgFgEQgEgEgBgHQgHgGAAgKQgCgDABgEQABgEACgBQgHgGgBgEQgCgFABgKQgEgGAEgDQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAQADgCADACQAFgBAFAJIADgCQAEgBADADQABADgBACQgCACADAFIABAHQAGAFAAADQAEACABADIAGACQAFgBAFADQAGgDAHAAQgDgEAAgFQAAgGADgDQgBgGADgFQADgFAGgCQAAgEAGgBQAHAAABAEQALAEAAAMQAEADABAGQAAAGgDAEQAKABAEAEQAGAAAGAFQAGAGgCAIQAFAEABAHIAAABQAAAFgCADQAFAFAAAGQANAHgGAMQAAACAIADQAGAHgDAFQABAEgEACQgEABgDgCIgEADQgCACgDgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQgGgEADgEIgBgCQgIAAgEgEQACAGgEAIQACALgIAIQABAFgBAEQAGAIgJALIAAABQABAEgBAEQgDAHgHADQACAGABABIAAABIAGADQAHAFAAAGIAAAFQgCAEgJACQgIACgEgCQgDgBgCgEIgEgGIgHgHQgBgEAAgEQABgEADgEQgEgEgBgFQgCgEABgEIACgEQgEgHAAgCIgCAFQABAEgBAEQgBAEgEAEIgFADQgBAMgJACIgDABQgDAGAAAEQADAJAAAFQgCAJgQAAQgIgBgGgHgAg5BmQgDAEADAFQAGAHAKgCIAAAAQgKABgFgHIABgBQAKAIAKgGQAAAAABAAQAAAAAAgBQABAAAAgBQAAAAAAAAIgDgMQAAgCADgIQgJAAgDgEIgMATgAAFBVQgCAHAIAHIADAFQACACADACQAEACAGgCQAHgBABgDIgBAAQgDADgFAAQgFABgCgCIAAAAQALAAADgEQAEgDgGgEIgIgFIgHABIgBgDIAGgBIgBgCIgHABIAAgDIAGgBIAAgCQgHABgGgCgAgyBIQADAIAHACQAJAEAFgFQAFgDABgFQgGACgGgCQgKgCgGgLQgEAFACAHgAAEBJQAEAEAHABQAPAAAAgPQgGAEgIAAQgJAAgGgHQgBAIAEAFgAguA5QAEAKAIADQAMAEAIgHQAFgGgBgGQgJAHgLgFQgMgGAAgLQgIAHAEAKgAABA4QAFAIAKABQALAAAFgIQAFgGgDgGQgHAIgMgBQgMgBgDgLQgDAHAEAJgAglAuQADAGAFADQAJADAHgEQAGgEgBgFQgSADgLgOQgDAFADAHgAACAmQABAFAFADQAFAEAFAAQAHAAAEgEQAFgFgBgHQgPAKgNgLgAghAhQAHAKALgBQASAAABgRQgJAGgMgEQgMgEgFgLQgHALAIAKgAAIAXIgCAIQAJAIAMgFQANgFgBgNQgNAMgSgGgAgfAMQAFAKALACQALADAHgEQAHgFAAgHQgcAAgNgPQgFAGAFAKgAAOAKQAAAGgEAEQAMADAKgFQAKgGAAgMQgKAJgSABgABDAQIACAAIADgDIgBgBQgHABADADgABFAIIAEADQAEAFADgCQAAgBABAAQAAAAAAgBQAAAAAAAAQgBgBAAAAIgDgEQgFgFABgCIABABIAHAHQgCgEgDgCIgGgDQgCABgGABIAAADQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIACAAQAAAAABAAQAAAAABABQAAAAABABQAAAAAAABgABAAKQAAAAAAABQAAAAAAABQAAAAAAAAQABABAAAAIADgCQAAgBgBgBQAAAAAAgBQgBAAAAgBQAAAAgBAAIAAAAIgBADgAA9AGQAAAAAAABQgBAAAAABQAAAAABABQAAAAABABQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAAAIgBgBIgBAAgAgRACQANAGAOgBQATAAAJgHQAHgGgBgIQgOALgYgCQgWgBgOgNQgCAPAPAGgAAwgJQgBAFAFADQAFABAHgBQAFgCACgHQAAgHgHgDQgEAJgMACgAgggeQABAJANAGQAOAHAOAAQAZAAAKgMQAIgKgFgJQgKAKgWACQgWACgNgKQgFAEgIABgAA0gcQAAAEgFAGIABAGQAIgBAEgGQAEgHgGgHQgBAEgFABgAgRgmQAJAIAQAAQAVAAALgIQAOgKgKgOQgGAHgSADQgUADgNgGQAAAJgEAIgAAygrQACAEABAGQAKgFgIgNQgCAFgDADgAgdgwQgFAJgMAAQAGAHALgCQAMgDAAgNQABgSgPgEQAIAOgGAKgAgzgrQAKAEAHgJQAGgGgDgKQgDgJgEAAQACALgJAHQgIAHgKgFQADAIAJACgAAthCQAHAGAAAIQADgGgDgGQgDgEgEgBgAg7g2QAIABAFgFQAJgJgFgIIgDgDQgBAIgJAEQgIAEgHgFQACAKAJADgAgVhHQAFAEACAIQAJAFALAAQAPAAAKgEQAKgEABgFQACgHgVgBQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAABAAQAAgBAAAAQADgDgCgCQAFAAAAgIQABgGgFgEIAAgBQABgKgMgDIAAAAIAAgBIgDgBIgFABQAAAAAAAAQAAAAAAAAQAAAAABABQAAAAABAAIAAAAQgEAAgCAEQgFAEAAAHIAEAAIAAABQgGABgBAGQgBAHAHAEIAAAAQAAABgBAAQAAABAAAAQAAABAAAAQABAAAAABIABABQAAAAAAAAQgBABAAAAQAAAAgBgBQAAAAgBAAIgGgBIgJACgAhFhFQAFAFAIgEQAIgEAAgGQABgGgGgDQgBABAAAFQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgCAAQABgCAAgDQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAIABgFIgCgGQgBgFACgEQgBgBgBAAQAAAAgBAAQAAAAgBAAQAAAAAAABQgCAEACAFIgDAEIAAABIgBAAQgBgDACgCIgCgHQgDgJgEAAIAGALQAAAAAAAAQAAABAAAAQAAAAAAAAQAAABgBAAQgFgKgDgDQAAgBgBAAQAAgBgBAAQAAAAgBAAQAAAAgBABIADACIAHANIgBAAQAAAAAAAAQgBAAAAgBQgBAAAAgBQAAgBgBgBIgFgIQAAAAAAAAQgBAAAAAAQgBAAAAAAQAAAAgBAAIACAEQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIABACIADAJIgCAAQgCgCAAgHIgCgBIgBAAQAAAJACAEQABAEAHAFQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQABAEADgBIABABQgEADgCgDIgCgDQgGAGAGAFgAgvBgIAAgCQAFAAAEABIgCACgAguBbIAAgDIAJACIgBACgAAFhTIgEgBIgBABIABgDIAAgBIACABIAFAAIAHAAIABgBIABADIgBAAIgFADIgBAAQgCAAgDgCgAAFhUIADACIADAAIADgDIgCgBIgHACgAAAhbQAAgCAAgEQAAgHADAAQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAAAABQADABAAAFQABAHgGAAIgDgBgAAAhhIAAAEIAAgCQAAgFADAAQADAAAAAFIAAABIAAgDQAAgEgBgBIgCgBQgDAAAAAGgAANhbQgCgBgBgFQAAgGAEgCQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQADACAAADQABAHgFAAgAARhgIgBADIABAAIABgFQAAgDgDgBIgBgBQgEAAABAGQAAgBABgBQAAAAAAgBQABAAAAAAQABAAAAAAQADAAAAAEgAhEhdIgDgBIADgBIACABIAAACIAAAAIgCgBg");
	this.shape.setTransform(-29.3,-0.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FAE22B").s().p("AjTAEQABgEAAgDIIPAAIgDAHgAkCAEQAEgEACgDIAEAAQgBADABAEgAk8AEIAAgHIAQAAQgCADAAACIAAACg");
	this.shape_1.setTransform(-4.7,5.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1960A6").s().p("AkiBBQgBgBgCgGQAHgDADgHIIMAAIAEgIIoQAAIAAgBQAJgLgGgIQABgEgBgFQAIgIgCgJQAEgIgCgIQAEAGAIAAIABACQgDAEAGAEQAAABAAAAQAAABABAAQAAABAAAAQAAAAABAAQAAABAAAAQAAAAAAABQABAAAAABQAAAAABAAQADABACgBIAEgCQADACAEgBQAEgCgBgEQADgFgGgHQgIgFAAgCQAGgMgNgHQAAgGgFgFQACgDAAgFIKEAAIAACBgAgdghQgQADgLAJQgOALABAOQAAAJAKAHQAKAFAOAAQASgBADgCIAIgSQgTADgGgCQgJgDADgGQACgHAIgEQAIgDAHAAQAJAAADAGIAGgVQgHgCgJAAQgKAAgJACgAEvAXIAoAAIAWg5IgYAAIgPAnIABgbQABgFgDgEIgFgDIgiAAIgVA5IAYAAIAPgngADdAXIAcAAIAWg5IgdAAgACdAXIA3AAIAHgUIgcAAIAPglIgcAAgABTAXIA8AAIAFgQIghAAIADgGIAeAAIAGgNIgfAAIACgHIAhAAIAFgPIg7AAgAAvADIgHAUIAaAAIAWg5IgbAAIgIAWIgOAAIAIgWIgbAAIgUA5IAZAAIAHgUgAh3AXIAdAAIAVg5IgcAAgAihAXIAaAAIAWg5IgoAAIgWAgIACgUQACgMgJAAIghAAIgWA5IAaAAIAPgoIgDAoIAXAAIAcgogAlZBBQAJgCABgMIAFgDIAKAAQACAFAFAEQgDAEgBAEgAmFBBIAAgRIAPAAQAAAGAGAGIgDAFgAlFAoQABgEgBgEIACgFQAAACAEAHIgCAEgAmFAoIAAhoIAHAAQAFAEAGABQAGAIAJABQABAFACACQgCAIADAGQgHAIADAKQgJAKAGALIgCADQgFADgDAIQgCAEACAIIgDAEg");
	this.shape_2.setTransform(2.6,1.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ApYEGIC/oLIPyAAIAAILgAk1A+IAAAIIAAARIASAAIgJAOQgFAGAFAGQAGAHAIABQAQAAABgJQABgFgDgJQAAgEADgGIACgBIAdAAQAAAEABAEIAHAHIAEAGQACAEADABQAEACAIgCQAJgCACgEIAAgFQAAgGgIgFIgFgDIAAgBIKnAAIAAiBIqEAAIAAgBQAAgHgFgEQABgIgGgGQgFgFgHAAQgDgEgKgBQADgEAAgGQgBgGgEgDQAAgMgLgEQgCgEgHAAQgGABgCAEQgFACgDAFQgDAFAAAGQgCADAAAGQAAAFACAEQgGAAgGADQgGgDgFABIgFgCQgCgDgDgCQAAgDgGgFIgCgHQgCgFACgCQABgCgCgDQgDgDgDABIgDACQgGgJgFABQgCgCgEACQAAAAgBAAQAAAAgBABQAAAAAAAAQgBABAAAAQgDADADAGQAAAKABAFQACAEAHAGQgDABAAAEQgBAEACADQAAAKAHAGQABAHAEAEIgHAAgAkoBwQgDgFADgEIAMgTQACAEAKAAQgEAIABACIADAMQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAQgJAGgLgIIAAABQAEAHALgBIAAAAIgEABQgHAAgFgGgAkfBhIAIABIABgCQgEgBgFAAgAkeBcIAJABIABgCIgKgCgAjaBtQgDgCgCgCIgDgFQgIgHACgHIADgGQAFACAIgBIAAACIgHABIABADIAHgBIAAACIgFABIAAADIAHgBIAJAFQAGAEgFADQgCAEgLAAIAAAAQABACAGgBQAFAAACgDIACAAQgCADgGABIgGABIgEgBgAkXBTQgIgCgCgIQgCgHAEgFQAFALALACQAGACAFgCQgBAFgEADQgDADgEAAIgHgCgAjfBPQgGgBgEgEQgFgFACgIQAFAHAKAAQAIAAAGgEQgBAPgOAAIgBAAgAkSBHQgHgDgEgKQgEgKAIgHQAAALAMAGQALAFAJgHQABAGgFAGQgGAEgGAAQgEAAgFgBgAjsA5QgGgJAEgHQAEALALABQANABAHgIQADAGgFAGQgFAIgMAAQgJgBgFgIgAkNA4QgEgDgEgGQgDgHAEgFQALAOASgDQABAFgGAEQgFACgEAAIgIgBgAjmAvQgEgDgBgFIACgFQAOALAPgKQABAHgFAFQgFAEgGAAQgFAAgGgEgAATAqQgLgHAAgJQAAgQAOgKQALgIAPgDQAUgEASAEIgIATQgDgGgJAAQgIAAgHADQgIAEgCAHQgDAIAJADQAGACASgDIgHASQgDACgSABQgPAAgJgFgAF/AtIABgpIgPApIgYAAIAVg5IAhAAIAFADQADAEAAAFIgBAbIAPgnIAXAAIgWA5gAEsAtIAWg5IAcAAIgVA5gADsAtIAWg5IAcAAIgPAlIAcAAIgIAUgACiAtIAWg5IA7AAIgGANIggAAIgCAHIAfAAIgGAPIgfAAIgCAGIAhAAIgFAQgAB3AtIAHgUIgOAAIgHAUIgbAAIAVg5IAbAAIgHAUIAOAAIAIgUIAbAAIgWA5gAgnAtIAWg5IAaAAIgTA5gAhRAtIAPgqIgdAqIgWAAIADgqIgQAqIgZAAIAVg5IAiAAQAIAAgBAMIgCASIAWgeIAnAAIgVA5gAkQAiQgJgKAHgLQAGALAMAEQAMAEALgGQgBARgUAAIgBAAQgKAAgHgJgAjoAgIACgIIABgBQARAGAOgMQABANgNAFQgFACgEAAQgHAAgGgFgAj+AZQgMgCgEgKQgGgKAGgGQANAPAeAAQAAAHgHAFQgGACgGAAIgIgBgAjjAVQADgEAAgGQATgBAJgJQABAMgKAGQgGADgHAAIgJgBgAiqARQgDgDAGgBIACABIgEADIgBAAIAAAAgAikAMIgEgDQgCgEgDABQAAAAAAAAQgBgBAAAAQAAAAAAAAQgBAAAAAAIgBgDQAHgCABAAIAHADQADACABAEIgGgHIgBgBQgCACAFAFIADAEQABAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAIgBAAQgCAAgDgDgAitALQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAABIgCACQgBAAAAAAQAAgBAAAAQAAAAAAgBQAAgBAAAAgAiwAHQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAAAABQgBAAAAABQAAgBAAAAQgBgBAAAAQAAgBAAAAQABAAAAgBgAkAADQgPgGACgPQAOANAYABQAYACANgLQACAIgHAFQgJAIgTAAIgCAAQgPAAgMgFgAi6AAQgEgDABgFQAMgCAEgJQAHADgBAHQgBAHgFACIgHAAQgDAAgDAAgAkBgOQgNgGgBgJQAIgBAEgEQANAKAYgCQAXgCAKgKQAEAJgIAKQgJAMgZAAIgCAAQgPAAgNgHgAi+gRQAFgGAAgEQAEgBACgEQAGAHgFAHQgDAGgIABgAjlgdQgSAAgKgIQAFgIAAgJQAOAGAVgDQASgDAFgHQAKAOgNAKQgLAIgTAAIgCAAgAi8gqQADgDADgFQAIANgKAFQgBgGgDgEgAkdgmQAMAAAFgJQAGgKgIgOQAPAEgBASQgBANgLADIgFAAQgIAAgEgFgAkigqQgKgCgCgIQAKAFAIgHQAJgHgCgLQAEAAADAJQADAKgGAGQgFAGgGAAIgGgBgAjAhBIgBgDQAFABACAEQADAGgDAGQAAgIgGgGgAkqg1QgJgDgDgKQAIAFAIgEQAJgEABgIIADADQAFAIgJAJQgEAEgGAAIgDAAgAj9g6QgCgIgFgEQAJgDAGACQABAAAAABQABAAAAAAQAAAAAAAAQABgBAAAAIgBgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBIAAAAQgHgEABgHQABgGAGgBIAAgBIgEAAQAAgHAEgEQAEgEAFAAIAAAAQgBAAgBAAQAAAAAAgBQgBAAAAAAQAAAAABAAIAEgBIAEABIAAABIAAAAQAMADgBAKIAAABQAEAEAAAGQAAAIgFAAQACACgDADQgBAAAAABQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAQAAgBABAAQABAAAAgBQAUABgBAHQgBAFgKAEQgKAEgPAAQgNAAgJgFgAjphSQAFAEACgCIAEgDIACAAIgBgDIgBABIgIAAIgEAAIgCgBIAAABIgCADIACgBgAjqhnQgFAAAAAHQAAAEACACIADABQAGAAgCgHQAAgFgCgBIgBgBIgBAAgAjjhgQABAFACABIABAAQAFAAAAgHQAAgDgDgCQAAgBgBAAQAAAAAAAAQAAgBgBAAQAAAAgBAAQgDACAAAGgAk0hEQgGgFAGgGIACADQABADAEgDIAAgBQgDABgBgEQgBAAAAgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQgHgFgBgEQgCgEAAgJIABAAIACABQAAAHABACIACAAIgCgJIgBgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgBgEQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAIAFAIQAAABABABQAAABABAAQAAABAAAAQABAAAAAAIABAAIgHgNIgDgCQAAgBABAAQAAAAABAAQAAABABAAQAAABABAAQADADAFAKQAAAAABAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIgGgLQAEAAADAJIABAHQgBACAAADIABAAIABgBIADgEQgDgFADgEQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQgBAEABAFIACAGIgBAFQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQABADgBACIABAAQABAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAAAQAAgFABgBQAFADAAAGQAAAGgJAEQgDACgDAAQgEAAgCgDgAk3hdIAEABQAAAAABABQAAAAAAAAQABAAAAAAQAAAAAAAAIAAgCIgCgBgAjlhRIgDgCQAEgCAFABIgDADIgBAAIgCAAgAjdhcIABgDQAAgEgDAAQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABAAABQgBgGAEAAIABABQACABAAADIAAAFgAjuhgQgBgGAFAAIABABQACABAAAEIgBADIAAgBQABgFgDAAQgDAAAAAFIAAACg");
	this.shape_3.setTransform(-5.4,-1);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-65.5,-27.3,120.2,52.6);


(lib.Info_btn = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEE32B").s().p("AgXCGQgdgFALgeQALgdAegBQAUAAAHALQAHAJgGAQQgKAdgdAAQgEAKANAAIAGgBIgEALIgGABQgZAAAIgVgAgZBlQgIAWAWgBQAJAAAEgEQAGgEAEgLQAIgWgUAAQgSAAgHAUgAAnB+QgHgGAGgNIAMgkIARAAIgOAkQgGAPASAAQAOAAAFgPIANgkIAQAAIgMAkQgGAPgJAHQgIAGgQgBQgRAAgGgIgABpCFIAXg+IAQAAIgWA+gAhECFIAAgNIgfAAIgJANIgSAAIArg4QADgGAGAAIASAAIADA+gAhbBsIAWAAIgBgegACCBDIARgPIARAAIgUAPgADjAUQgGgKAGgNQAKgdAgAAQAUgBAHALQAHAJgGAPQgKAdggAAQgVAAgHgLgADygCQgIAVAXgBQARAAAIgSQAHgVgWABQgRAAgIASgACAAVQgIgKAGgPQALgcAhAAQAMAAAMADIgFAMQgJgDgKAAQgVgBgIAUQgGATAYAAQALAAAIgDIgEANQgIACgLABQgUgBgHgJgAjHAUQgGgKAFgNQALgdAgAAQAVgBAHALQAGAJgFAPQgMAdgfAAQgUAAgIgLgAi3gCQgJAVAWgBQASAAAHgSQAIgVgVABQgTAAgGASgAFXAdIgMgwIgSAwIgPAAIAXg8IAQAAQAGgBACAHIALAqIATgwIAOAAIgXA8gAC6AdIAXg8IAQAAIgWA8gABiAdIAAgOIgeAAIgJAOIgSAAIAqg3QAEgFAGAAIATAAIACA8gABNAFIAVAAIgBgcgAAQAdIASgwIgkAwIgQAAIgCgxIgTAxIgPAAIAXg8IARAAQAGgBABAJIADAjIAhgrIAaAAIgXA8gAhTAdIgHgUIgOAAIgHAUIgRAAIAXg8IAcAAQAhAAgKAYQgEAMgQABIAJAXgAhkgBIALAAIANgBQAFgBACgGQAEgLgQAAIgLAAgAkPAdIAXg8IA2AAIgEALIgmAAIgHASIAjAAIgEAIIgiAAIgIAXgAk3AdIgMgwIgSAwIgPAAIAXg8IAQAAQAGgBACAHIAKAqIATgwIAPAAIgXA8gAmEAdIAXg8IAPAAIgVA8gAEKgkIARgNIARAAIgTANgAAyhNIAEgMQAMAGANAAQAOAAADgHQADgGgKgDIgKgCQgTgDAGgRQAGgQAYAAQAOAAANAGIgDALQgMgGgMAAQgMAAgDAHQgCAEAIADIALACQATAEgFASQgHAQgZAAQgRABgNgGgAAehJIAAgNIgeAAIgIANIgRAAIAng4QAEgHAHAAIASAAIACA/gAAHhiIAXAAIgBgegAgzhJIATgzIgnAzIgPAAIgEgzIgSAzIgOAAIAWg/IARAAQAHAAAAAIIADAlIAjgtIAaAAIgXA/gAAZiMIAQgOIASAAIgUAOg");
	this.shape.setTransform(-1,-0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("Am4C4IAAlvINxAAIAAFvgAg0BiQgLAdAdAGQgIAUAZAAIAIAAIAEgLIgIABQgMAAADgKQAdgBAKgcQAGgQgHgJQgHgLgSAAQggAAgLAegAAbBqQgFAMAGAHQAGAIARAAQAQAAAIgGQAJgGAGgPIANgkIgQAAIgOAkQgFAPgOAAQgRAAAGgPIANgkIgRAAgABfCEIAQAAIAWg+IgQAAgAhPB2IAAAOIAPAAIgCg+IgTAAQgGAAgDAFIgqA5IARAAIAKgOgAB3BBIAPAAIATgOIgRAAgADYgFQgGAOAGAJQAHALAVAAQAgAAAKgdQAGgOgGgKQgIgKgUAAQgfAAgLAdgAB0gGQgHAPAIAKQAHAKAUAAQAMAAAHgCIAFgNQgIACgMABQgYgBAHgSQAHgUAVAAQAKAAAKAEIAEgMQgMgEgMAAQghAAgKAcgAjSgFQgGAOAHAJQAHALAUAAQAfAAAMgdQAGgOgHgKQgHgKgVAAQggAAgKAdgAFMAbIAYAAIAWg8IgOAAIgTAxIgLgqQgCgHgGAAIgQAAIgXA8IAPAAIASgvgACvAbIARAAIAWg8IgQAAgABXAOIABANIAPAAIgCg8IgTAAQgGAAgEAGIgpA2IARAAIAJgNgAAFAbIAQAAIAXg8IgaAAIghArIgDgjQAAgIgHAAIgRAAIgWA8IAOAAIATgwIACAwIAQAAIAkgvgAhkAIIAHATIARAAIgJgWQAQgCAFgLQAJgZghAAIgcAAIgWA8IAQAAIAHgTgAkZAbIAQAAIAIgWIAiAAIAFgJIgjAAIAGgRIAnAAIADgMIg2AAgAlCAbIAYAAIAWg8IgOAAIgTAxIgLgqQgCgHgGAAIgQAAIgXA8IAPAAIASgvgAmPAbIARAAIAWg8IgQAAgAD/glIAPAAIATgOIgRAAgAAohPQAMAGASAAQAZAAAGgQQAGgSgUgFIgLgCQgHgCACgFQACgGANAAQALAAAMAFIAEgLQgOgGgNAAQgZABgGAPQgGARAUAEIAKACQAJACgDAHQgCAHgOgBQgOABgMgGgAAThYIAAAOIAPAAIgCg/IgSAAQgHAAgDAGIgoA5IASAAIAJgOgAg+hKIARAAIAWg/IgaAAIgjAtIgDglQAAgIgHAAIgRAAIgWA/IAPAAIASgzIADAzIAPAAIAngzgAAOiOIAOAAIAUgNIgRAAgAgkBjQAIgTASAAQATAAgIAVQgCAMgGADQgGAFgJAAQgWAAAIgWgAhmBrIAVgeIABAegADogDQAHgTASAAQAVAAgHAWQgHARgSAAQgXAAAJgUgAjCgDQAHgTASAAQAWAAgJAWQgHARgSAAQgVAAAIgUgABCADIAVgcIAAAcgAhvgCIAIgUIALAAQAQAAgEAMQgCAFgFACIgMABgAgBhjIATgfIABAfg");

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-44.1,-18.4,88.4,36.9);


(lib.Fondo3_mc = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib._3();
	this.instance.setTransform(-60,-100);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-60,-100,120,200);


(lib.Fondo2_mc = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib._2();
	this.instance.setTransform(-60,-100);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-60,-100,120,200);


(lib.Fondo1_mc = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib._1();
	this.instance.setTransform(-60,-100);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-60,-100,120,200);


(lib.Group = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgYAOIALgbIAmAAIgLAbg");
	this.shape.setTransform(100.2,71);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhKA1IALgcQAUAJAaAAQAMAAAFgCQAGgBACgFQADgKgLgCIgQgDQgqgHANghQAKghA2AAQAgAAAXAJIgKAcQgVgJgWAAQgUAAgBAIQgDAIAHACIASADQAsAHgOAkQgHASgRAIQgPAHgaAAQglAAgYgKg");
	this.shape_1.setTransform(92.1,66.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAiA8IAAgVIgwAAIgOAVIgxAAIBLhoQAIgPARAAIA3AAIAAB3gAADAKIAgAAIABgwg");
	this.shape_2.setTransform(76,66.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag8A8IAhhZIglAAIALgeIB2AAIgLAeIgkAAIgeBZg");
	this.shape_3.setTransform(66.8,66.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgOA8IgIhXIggBXIgpAAIAsh3IAzAAQAPAAAAASIAHBFIAhhXIApAAIgsB3g");
	this.shape_4.setTransform(50.2,66.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAhA8IABgVIgwAAIgOAVIgxAAIBLhoQAJgPAQAAIA3AAIAAB3gAADAKIAfAAIACgwg");
	this.shape_5.setTransform(31.7,66.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag7A8IAsh3IAuAAIgfBYIA8AAIgLAfg");
	this.shape_6.setTransform(18.4,66.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag7A8IAsh3IAuAAIggBYIA9AAIgLAfg");
	this.shape_7.setTransform(6.1,66.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgNA8IAKgbIhGAAIAMghIA4gwQAKgLAKAAIA7AAIgZBBIARAAIgJAbIgRAAIgKAbgAgdAGIAhAAIATgwg");
	this.shape_8.setTransform(66.7,46.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhOA8IAsh3IBxAAIgKAcIhEAAIgFATIA8AAIgKAZIg8AAIgHATIBDAAIgKAcg");
	this.shape_9.setTransform(49.1,46.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhRA8IAsh3IA4AAQAqAAAPAUQAMARgLAdQgKAcgWAOQgTALgeAAgAgXAfIATAAQANgBAIgGQAJgHAGgQQALgfgbAAIgQAAg");
	this.shape_10.setTransform(33.7,46.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAhA8IABgVIgwAAIgOAVIgxAAIBKhnQAJgQARAAIA3AAIAAB3gAADAKIAfAAIACgwg");
	this.shape_11.setTransform(88.6,26.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAGA8IgLgjIgPAAIgMAjIgwAAIAsh3IA/AAQBEAAgSAyQgKAXgeAEIASAqgAgKgBIAMAAQANAAAGgCQAGgDADgIQADgJgDgDQgDgFgNAAIgOAAg");
	this.shape_12.setTransform(74.7,26.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhPA8IAsh3IA7AAQBHAAgTA3QgIAUgTAJQgPAHgdAAIgaAAIgKAcgAgLAEIALAAQAOAAAGgEQAGgBAEgKQAEgLgDgEQgEgFgNAAIgOAAg");
	this.shape_13.setTransform(60,26.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAaA8IAghVIg9BVIgpAAIABhXIghBXIgpAAIAsh3IAzAAQAKAAAEAFQADAFAAAKIABAzIAwhHIBKAAIgsB3g");
	this.shape_14.setTransform(42.1,26.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhHArQgOgTAMgeQALgeAVgNQAVgNAiAAQAsAAAPAVQANASgMAeQgLAegWANQgUANgiAAQgsAAgOgUgAgMgaQgJAHgGARQgNAjAgAAQAMAAAIgGQAKgHAGgRQANgjggAAQgMAAgJAGg");
	this.shape_15.setTransform(23.2,26.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag/ArQgQgTANggQATg2BGAAQAZAAAZAIIgLAeQgQgHgWAAQgSAAgJAHQgNAHgGARQgLAgAnAAQAXAAAPgEIgMAfQgOAEgXAAQgrAAgPgUg");
	this.shape_16.setTransform(9.1,26.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAhA8IABgVIgwAAIgOAVIgxAAIBLhoQAIgPARAAIA3AAIAAB3gAADAKIAgAAIABgvg");
	this.shape_17.setTransform(72,6.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag7A8IAsh3IAuAAIggBZIA9AAIgLAeg");
	this.shape_18.setTransform(58.7,6.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgOA8IgHhXIghBXIgpAAIAsh3IAzAAQAOAAAAATIAIBEIAhhXIApAAIgsB3g");
	this.shape_19.setTransform(40.4,6.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AhOA8IAsh3IBxAAIgKAcIhEAAIgFATIA8AAIgKAaIg8AAIgHASIBDAAIgKAcg");
	this.shape_20.setTransform(25.3,6.1);

	this.addChild(this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,102.8,72.8);


(lib.Camioneta120_mc = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.Camioneta120();
	this.instance.setTransform(-232,-200.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-232,-200.5,464,401);


(lib.Azul = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(22,97,167,0)","#1661A7"],[0,0.396],-63.6,0,53.3,0).s().p("ApHCPIAAkeISPAAIibEeg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-58.4,-14.4,116.9,28.8);


(lib.Texto_2 = function() {
	this.initialize();

	// Layer 1 copy
	this.instance = new lib.Group();
	this.instance.setTransform(0.1,-11.9,1,1,0,0,0,51.4,36.4);

	// Layer 1
	this.instance_1 = new lib.Group();
	this.instance_1.setTransform(2.1,-9.9,1,1,0,0,0,51.4,36.4);
	this.instance_1.filters = [new cjs.ColorFilter(0.06, 0.06, 0.06, 1, 0, 0, 0, 0)];
	this.instance_1.cache(-2,-2,107,77);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-51.3,-48.3,104.8,74.8);


// stage content:
(lib._120x600_op = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_163 = function() {
		/* Stop at This Frame
		The  timeline will stop/pause at the frame where you insert this code.
		Can also be used to stop/pause the timeline of movieclips.
		*/
		
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(163).call(this.frame_163).wait(10));

	// FlashAICB
	this.instance = new lib.LOGO_mc();
	this.instance.setTransform(186.1,534.4);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(20).to({_off:false},0).wait(1).to({regX:-5.4,regY:-1,x:165.7,y:533.4},0).wait(1).to({x:150.7},0).wait(1).to({x:135.7},0).wait(1).to({x:120.7},0).wait(1).to({x:105.7},0).wait(1).to({x:90.7},0).wait(1).to({x:75.7},0).wait(1).to({x:60.7},0).wait(142).to({_off:true},1).wait(2));

	// PlecaAzul
	this.instance_1 = new lib.Azul();
	this.instance_1.setTransform(-69.2,563.7);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(20).to({_off:false},0).wait(1).to({x:-53.3},0).wait(1).to({x:-37.3},0).wait(1).to({x:-21.4},0).wait(1).to({x:-5.4},0).wait(1).to({x:10.5},0).wait(1).to({x:26.5},0).wait(1).to({x:42.4},0).wait(1).to({x:58.4},0).wait(142).to({_off:true},1).wait(2));

	// BTN
	this.instance_2 = new lib.Info_btn();
	this.instance_2.setTransform(-135.4,178.4);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;
	new cjs.ButtonHelper(this.instance_2, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(108).to({_off:false},0).wait(1).to({x:-120.5,alpha:0.077},0).wait(1).to({x:-105.7,alpha:0.154},0).wait(1).to({x:-90.8,alpha:0.231},0).wait(1).to({x:-75.9,alpha:0.308},0).wait(1).to({x:-61.1,alpha:0.385},0).wait(1).to({x:-46.2,alpha:0.462},0).wait(1).to({x:-31.3,alpha:0.538},0).wait(1).to({x:-16.4,alpha:0.615},0).wait(1).to({x:-1.6,alpha:0.692},0).wait(1).to({x:13.3,alpha:0.769},0).wait(1).to({x:28.2,alpha:0.846},0).wait(1).to({x:43,alpha:0.923},0).wait(1).to({x:57.9,alpha:1},0).wait(47).to({_off:true},1).wait(4));

	// Texto_2
	this.instance_3 = new lib.Texto_2();
	this.instance_3.setTransform(-125.1,87.9);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(98).to({_off:false},0).wait(1).to({regX:1,regY:-11,x:-107.3,y:76.9,alpha:0.091},0).wait(1).to({x:-90.5,alpha:0.182},0).wait(1).to({x:-73.7,alpha:0.273},0).wait(1).to({x:-56.9,alpha:0.364},0).wait(1).to({x:-40.1,alpha:0.455},0).wait(1).to({x:-23.3,alpha:0.545},0).wait(1).to({x:-6.5,alpha:0.636},0).wait(1).to({x:10.3,alpha:0.727},0).wait(1).to({x:27.1,alpha:0.818},0).wait(1).to({x:43.9,alpha:0.909},0).wait(1).to({x:60.7,alpha:1},0).wait(55).to({_off:true},1).wait(8));

	// Texto_1
	this.instance_4 = new lib.Texto_1();
	this.instance_4.setTransform(-124.7,82.4);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(34).to({_off:false},0).wait(1).to({regX:0.1,regY:-4.5,scaleX:1,scaleY:1,x:-106.1,y:77.9,alpha:0.1},0).wait(1).to({scaleX:1.01,scaleY:1.01,x:-87.7,y:77.8,alpha:0.2},0).wait(1).to({scaleX:1.01,scaleY:1.01,x:-69.3,alpha:0.3},0).wait(1).to({scaleX:1.02,scaleY:1.02,x:-50.9,alpha:0.4},0).wait(1).to({scaleX:1.02,scaleY:1.02,x:-32.4,alpha:0.5},0).wait(1).to({scaleX:1.03,scaleY:1.03,x:-14,y:77.7,alpha:0.6},0).wait(1).to({scaleX:1.03,scaleY:1.03,x:4.4,alpha:0.7},0).wait(1).to({scaleX:1.04,scaleY:1.04,x:22.8,alpha:0.8},0).wait(1).to({scaleX:1.05,scaleY:1.05,x:41.2,alpha:0.9},0).wait(1).to({scaleX:1.05,scaleY:1.05,x:59.7,alpha:1},0).wait(57).to({_off:true},1).wait(71));

	// Camioneta
	this.instance_5 = new lib.Camioneta120_mc();
	this.instance_5.setTransform(-293.7,637.2,1.266,1.266);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(13).to({_off:false},0).wait(1).to({scaleX:1.2,scaleY:1.2,x:-266.5,y:617.7},0).wait(1).to({scaleX:1.13,scaleY:1.13,x:-239.3,y:598.2},0).wait(1).to({scaleX:1.07,scaleY:1.07,x:-212,y:578.7},0).wait(1).to({scaleX:1,scaleY:1,x:-184.8,y:559.1},0).wait(1).to({scaleX:0.93,scaleY:0.93,x:-157.5,y:539.6},0).wait(1).to({scaleX:0.87,scaleY:0.87,x:-130.3,y:520.1},0).wait(1).to({scaleX:0.8,scaleY:0.8,x:-103.1,y:500.6},0).wait(1).to({scaleX:0.73,scaleY:0.73,x:-75.8,y:481.1},0).wait(1).to({scaleX:0.67,scaleY:0.67,x:-48.5,y:461.6},0).wait(1).to({scaleX:0.6,scaleY:0.6,x:-21.3,y:442.1},0).wait(1).to({scaleX:0.53,scaleY:0.53,x:6,y:422.6},0).wait(146).to({_off:true},1).wait(2));

	// 3.jpg
	this.instance_6 = new lib.Fondo3_mc();
	this.instance_6.setTransform(-181.9,500);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(6).to({_off:false},0).wait(1).to({x:-147.3},0).wait(1).to({x:-112.8},0).wait(1).to({x:-78.2},0).wait(1).to({x:-43.7},0).wait(1).to({x:-9.1},0).wait(1).to({x:25.4},0).wait(1).to({x:60},0).wait(157).to({_off:true},1).wait(2));

	// 2.jpg
	this.instance_7 = new lib.Fondo2_mc();
	this.instance_7.setTransform(344,300);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(3).to({_off:false},0).wait(1).to({x:308.5},0).wait(1).to({x:273},0).wait(1).to({x:237.5},0).wait(1).to({x:202},0).wait(1).to({x:166.5},0).wait(1).to({x:131},0).wait(1).to({x:95.5},0).wait(1).to({x:60},0).wait(159).to({_off:true},1).wait(2));

	// 1.jpg
	this.instance_8 = new lib.Fondo1_mc();
	this.instance_8.setTransform(-181.9,100);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(1).to({x:-155},0).wait(1).to({x:-128.1},0).wait(1).to({x:-101.3},0).wait(1).to({x:-74.4},0).wait(1).to({x:-47.5},0).wait(1).to({x:-20.6},0).wait(1).to({x:6.2},0).wait(1).to({x:33.1},0).wait(1).to({x:60},0).wait(161).to({_off:true},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-183.9,298,132,212);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;