/*
 * Banner objects list
 */
var banners = {

  'Campaña Acura MDX':{
    'id':'HHplc',
    'name':'Campaña Acura MDX',
    'title':'Campaña Acura MDX - Banner Display - 300x250',
    'image':'recursos/images/display-acura-mdx.png',
    'position':'iframe-300x250',
    'size':'iframe-300x250',
    'source':'proyectos/cerebrosm/displayads/acura/acura_MDX_300x250/index.html',
    'format':'box',
    'platform':'Mobile | Desktop | Tablet',
    'keywords':'Mobile, Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña de Acura.',
  },
  'Campaña Acura NSX':{
    'id':'8Kvoz',
    'name':'Campaña Acura NSX',
    'title':'Campaña Acura NSX - Banner Display - 300x250',
    'image':'recursos/images/display-acura-nsx.png',
    'position':'iframe-300x250',
    'size':'iframe-300x250',
    'source':'proyectos/cerebrosm/displayads/acura/acura_NSX_300x250/index.html',
    'format':'box',
    'platform':'Mobile | Desktop | Tablet',
    'keywords':'Mobile, Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña de Acura.',
  },
  'Campaña Adidas':{
    'id':'R6gGz',
    'name':'Campaña Adidas',
    'title':'Campaña Adidas - Banner Display - 160x600',
    'image':'recursos/images/display-adidas.png',
    'position':'iframe-160x600',
    'size':'iframe-160x600',
    'source':'proyectos/cerebrosm/displayads/adidas/adidas_160x600/index.html',
    'format':'Skyscrape',
    'platform':'Desktop | Tablet',
    'keywords':'Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña de Adidas',
  },
  'Campaña Adidas Freddy Yoga':{
    'id':'FAZ6X',
    'name':'Campaña Adidas Freddy Yoga',
    'title':'Campaña Adidas Freddy Yoga - Banner Display - 160x600',
    'image':'recursos/images/display-adidas-yoga.png',
    'position':'iframe-160x600',
    'size':'iframe-160x600',
    'source':'proyectos/cerebrosm/displayads/adidas/freddy_yoga_160x600/index.html',
    'format':'Skyscrape',
    'platform':'Desktop | Tablet',
    'keywords':'Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña Adidas',
  },
  'Campaña Adidas Nike Running':{
    'id':'UlVPB',
    'name':'Campaña Adidas Nike Running',
    'title':'Campaña Adidas Nike Running - Banner Display - 160x600',
    'image':'recursos/images/display-adidas-running.png',
    'position':'iframe-160x600',
    'size':'iframe-160x600',
    'source':'proyectos/cerebrosm/displayads/adidas/nike_running_160x600/index.html',
    'format':'Skyscrape',
    'platform':'Desktop | Tablet',
    'keywords':'Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña Adidas',
  },
  'Campaña Adidas Reebook Crossfit':{
    'id':'Lgw1p',
    'name':'Campaña Adidas Reebook Crossfit',
    'title':'Campaña Adidas Reebook Crossfit - Banner Display - 160x600',
    'image':'recursos/images/display-adidas-crossfit.png',
    'position':'iframe-160x600',
    'size':'iframe-160x600',
    'source':'proyectos/cerebrosm/displayads/adidas/reebook_crossfit_160x600/index.html',
    'format':'Skyscrape',
    'platform':'Desktop | Tablet',
    'keywords':'Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña Adidas',
  },
  'Campaña Adidas Under Armour':{
    'id':'LJpK6',
    'name':'Campaña Adidas Under Armour',
    'title':'Campaña Adidas Under Armour - Banner Display - 160x600',
    'image':'recursos/images/display-adidas-under-armour.png',
    'position':'iframe-160x600',
    'size':'iframe-160x600',
    'source':'proyectos/cerebrosm/displayads/adidas/under_armour_160x600/index.html',
    'format':'Skyscrape',
    'platform':'Desktop | Tablet',
    'keywords':'Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña Adidas',
  },
  'Campaña Anahuac Empresarial':{
    'id':'V1UGF',
    'name':'Campaña Anahuac Empresarial',
    'title':'Campaña Anahuac Empresarial - Banner Display - 300x250',
    'image':'recursos/images/display-anahuac.png',
    'position':'iframe-300x250',
    'size':'iframe-300x250',
    'source':'proyectos/cerebrosm/displayads/anahuac/anahuac_Empresarial_300x250/index.html',
    'format':'box',
    'platform':'Mobile | Desktop | Tablet',
    'keywords':'Mobile, Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña Anahuac',
  },
  'Campaña Cerebro Smart Media':{
    'id':'4hdPL',
    'name':'Campaña Cerebro Smart Media',
    'title':'Campaña Cerebro Smart Media - Banner Display - 300x250',
    'image':'recursos/images/display-cerebrosm.png',
    'position':'iframe-300x250',
    'size':'iframe-300x250',
    'source':'proyectos/cerebrosm/displayads/cerebrosm/cerebro/index.html',
    'format':'box',
    'platform':'Mobile | Desktop | Tablet',
    'keywords':'Mobile, Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña Cerebro Smart Media',
  },
  'Campaña COMEPESCA Estado de México':{
    'id':'PmFH0',
    'name':'Campaña COMEPESCA Estado de México',
    'title':'Campaña COMEPESCA Estado de México - Banner Display - 120x600',
    'image':'recursos/images/display-estado-de-mexico.png',
    'position':'iframe-120x600',
    'size':'iframe-120x600',
    'source':'proyectos/cerebrosm/displayads/comepesca/estado_de_mexico_120x600/index.html',
    'format':'Skyscrape',
    'platform':'Desktop | Tablet',
    'keywords':'Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña COMEPESCA',
  },
  'Campaña Martí Aparatos':{
    'id':'mKL8I',
    'name':'Campaña Martí Aparatos',
    'title':'Campaña Martí Aparatos - Banner Display - 300x250',
    'image':'recursos/images/display-marti-aparatos.png',
    'position':'iframe-300x250',
    'size':'iframe-300x250',
    'source':'proyectos/cerebrosm/displayads/marti/aparatos_300x250/index.html',
    'format':'box',
    'platform':'Mobile | Desktop | Tablet',
    'keywords':'Mobile, Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña Martí',
  },
  'Campaña Martí Wereables':{
    'id':'o0VnV',
    'name':'Campaña Martí Wereables',
    'title':'Campaña Martí Wereables - Banner Display - 300x250',
    'image':'recursos/images/display-marti-wereables.png',
    'position':'iframe-300x250',
    'size':'iframe-300x250',
    'source':'proyectos/cerebrosm/displayads/marti/wereables_300x250/index.html',
    'format':'box',
    'platform':'Mobile | Desktop | Tablet',
    'keywords':'Mobile, Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña Martí',
  },
  'Campaña NH Hoteles Colección':{
    'id':'UDcqT',
    'name':'Campaña NH Hoteles Colección',
    'title':'Campaña NH Hoteles Colección - Banner Display - 120x600',
    'image':'recursos/images/display-nh-hoteles-collection.png',
    'position':'iframe-120x600',
    'size':'iframe-120x600',
    'source':'proyectos/cerebrosm/displayads/nhhoteles/collection_120x600/index.html',
    'format':'Skyscrape',
    'platform':'Desktop | Tablet',
    'keywords':'Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña NH Hoteles',
  },
  'Campaña NH Hoteles':{
    'id':'wD4gh',
    'name':'Campaña NH Hoteles',
    'title':'Campaña NH Hoteles - Banner Display - 120x600',
    'image':'recursos/images/display-nh-hoteles.png',
    'position':'iframe-120x600',
    'size':'iframe-120x600',
    'source':'proyectos/cerebrosm/displayads/nhhoteles/es_120x600/index.html',
    'format':'Skyscrape',
    'platform':'Desktop | Tablet',
    'keywords':'Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña NH',
  },
  'Campaña Anahuac Orientación Vocacional':{
    'id':'2hSit',
    'name':'Campaña Anahuac Orientación Vocacional',
    'title':'Campaña Anahuac Orientación Vocacional - Banner Display - 300x250',
    'image':'recursos/images/display-anahuac-orientacion.png',
    'position':'iframe-300x250',
    'size':'iframe-300x250',
    'source':'proyectos/cerebrosm/displayads/anahuac/anahuac_Orientacion_300x250/index.html',
    'format':'box',
    'platform':'Mobile | Desktop | Tablet',
    'keywords':'Mobile, Desktop, Tablet, GWD, DoubleClick, Animaciones',
    'description':'Campaña Anahuac',
  },
  'Campaña Del Valle Limon&nada Canvas':{
    'id':'aC0Bq',
    'name':'Campaña Del Valle Limon&nada Canvas',
    'title':'Campaña Del Valle Limon&nada Canvas - Banner Display - 300x600',
    'image':'recursos/images/rich-delvalle-blur.png',
    'position':'iframe-300x600',
    'size':'iframe-300x600',
    'source':'proyectos/cerebrosm/richmediaads/delvalle/responsive_canvas_blur_100percent/index.html',
    'format':'box',
    'platform':'Mobile | Desktop | Tablet',
    'keywords':'Mobile, Desktop, Tablet, GWD, DoubleClick, Animaciones, Canvas, HTML5, Juego, Responsivo',
    'description':'Campaña Del Valle',
  },
  'Campaña Del Valle Limon&nada Basket Game':{
    'id':'1E2JB',
    'name':'Campaña Del Valle Limon&nada Basket Game',
    'title':'Campaña Del Valle Limon&nada Basket Game - Banner Display - 300x600',
    'image':'recursos/images/rich-delvalle-basket.png',
    'position':'iframe-300x600',
    'size':'iframe-300x600',
    'source':'proyectos/cerebrosm/richmediaads/delvalle/basket_game_100percent/index.html',
    'format':'box',
    'platform':'Mobile | Desktop | Tablet',
    'keywords':'Mobile, Desktop, Tablet, GWD, DoubleClick, Animaciones, Canvas, HTML5, Juego, Responsivo',
    'description':'Campaña Del Valle',
  },
  'Campaña ADIDAS':{
    'id':'7vIyD',
    'name':'Campaña ADIDAS',
    'title':'Campaña ADIDAS - Banner Display - 300x250',
    'image':'recursos/images/rich-adidas.png',
    'position':'iframe-300x250',
    'size':'iframe-300x250',
    'source':'proyectos/cerebrosm/richmediaads/adidas/cube_300x250/index.html',
    'format':'box',
    'platform':'Mobile | Desktop | Tablet',
    'keywords':'Mobile, Desktop, Tablet, GWD, DoubleClick, Animaciones, HTML5',
    'description':'Campaña ADIDAS',
  },
  'Campaña Amore Mio':{
    'id':'ushDo',
    'name':'Campaña Amore Mio',
    'title':'Campaña Amore Mio - Banner Display - 336x280',
    'image':'recursos/images/display-amoremio.png',
    'position':'iframe-336x280',
    'size':'iframe-336x280',
    'source':'proyectos/cerebrosm/richmediaads/amoremio/336x280/index.html',
    'format':'box',
    'platform':'Desktop | Tablet',
    'keywords':'Desktop, Tablet, GWD, DoubleClick, Animaciones, Video',
    'description':'Campaña Amore mio',
  },
  'Campaña Buick':{
    'id':'0j4S8',
    'name':'Campaña Buick',
    'title':'Campaña Buick - Banner Display - 300x250',
    'image':'recursos/images/display-buick.png',
    'position':'iframe-300x250',
    'size':'iframe-300x250',
    'source':'proyectos/cerebrosm/richmediaads/buick/300x250/index.html',
    'format':'box',
    'platform':'Mobile | Desktop | Tablet',
    'keywords':'Mobile, Desktop, Tablet, GWD, DoubleClick, Animaciones, Video',
    'description':'Campaña Buick',
  },
  'Campaña Fanta Halloween':{
    'id':'s0F8D',
    'name':'Campaña Fanta Halloween',
    'title':'Campaña Fanta Halloween - Banner Display - 300x600',
    'image':'recursos/images/display-fanta-candy.png',
    'position':'iframe-300x600',
    'size':'iframe-300x600',
    'source':'proyectos/cerebrosm/richmediaads/fanta/fanta_Candy_300x600/index.html',
    'format':'Skyscrape',
    'platform':'Desktop | Tablet',
    'keywords':'Desktop, Tablet, GWD, DoubleClick, Animaciones, Canvas, HTML5, Juego, Responsivo',
    'description':'Campaña Fanta',
  }

};
