(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 160,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/Camioneta120.png", id:"Camioneta120"},
		{src:"images/F1.jpg", id:"F1"},
		{src:"images/F22.jpg", id:"F22"},
		{src:"images/F3.jpg", id:"F3"}
	]
};



// symbols:



(lib.Camioneta120 = function() {
	this.initialize(img.Camioneta120);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,464,401);


(lib.F1 = function() {
	this.initialize(img.F1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,200);


(lib.F22 = function() {
	this.initialize(img.F22);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,200);


(lib.F3 = function() {
	this.initialize(img.F3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,200);


(lib.Symbol13 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.F3();
	this.instance.setTransform(-79,-100);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-79,-100,160,200);


(lib.Symbol12 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.F22();
	this.instance.setTransform(-81,-100,1.012,1);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-81,-100,162,200);


(lib.Symbol11 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.F1();
	this.instance.setTransform(-80,-100);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-80,-100,160,200);


(lib.RECI = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEE32B").s().p("ApzCIIAKgcQgYgBgUgEQgTgEgRgHIARgxQAQAHAVAFQAXAEAUAAIABAAIAOgnIgMgCQgUgDgNgGQgMgGgHgIQgFgKAAgMQAAgMAFgPQAGgPAKgLQAKgLAPgHQAPgHATgDQATgDAYAAIACAAIAJgYIAaAAIgJAZQATABARAEQAQAEAQAGIgRAwQgNgFgRgEQgUgFgTAAIgNAjIAIABQAOACAUAIQAMAGAHAJQAFAKAAANQAAANgGAPIgHAPIgKANQgKALgPAHQgPAGgTADQgSADgXAAIgKAbgAo9A7QAOgCAIgDQAHgEADgGQADgJgDgFQgEgFgJgBIgGgBgAo6g5QgIADgCAGQgDAIACAEQADAEAJABIAKACIAMggQgQABgHADgAi6CHIAvhSIBGAAIhBBSgAIKBqQgOgCgLgFQgLgEgJgHQgIgHgGgIQgFgJgDgKQgDgKAAgLQAAgMACgMQADgKAFgOQAGgRAPgaQAGgKAHgHQAHgIAIgFQAIgGAJgFIATgHQAPgDAigCQARAAAPACQAOADALAEQALAFAJAHQAIAHAGAIQAFAIADALQADAKAAALQAAALgCANQgDALgFAMQgNAggIAMQgGAKgHAHIgPANQgIAGgJAEQgJAFgKADQgeAFgTAAQgRAAgPgDgAJAg4QgHADgFAGQgGAHgGALIgLAbQgFANgCALQgCAMACAHQACAIAGAEQAGAEALAAQAIAAAHgDQAHgDAGgGQAFgHAGgLIALgbQAGgNABgMQACgLgCgIQgCgHgGgEQgGgEgKAAQgJAAgHADgAEUBqQgOgCgLgFQgLgEgJgHQgIgHgGgIQgFgJgDgKQgDgKAAgLQAAgMACgMQADgKAFgOQAGgRAPgaQAGgKAHgHQAHgIAIgFQAIgGAJgFIATgHQAPgDAigCQARAAAPACQAOADALAEQALAFAJAHQAIAHAGAIQAFAIADALQADAKAAALQAAALgCANQgDALgFAMQgNAggIAMQgGAKgHAHIgPANQgIAGgJAEQgJAFgKADQgeAFgTAAQgRAAgPgDgAFKg4QgHADgFAGQgGAHgGALIgLAbQgFANgCALQgCAMACAHQACAIAGAEQAGAEALAAQAIAAAHgDQAHgDAGgGQAFgHAGgLIALgbQAGgNABgMQACgLgCgIQgCgHgGgEQgGgEgKAAQgJAAgHADgAAeBqQgOgCgLgFQgJgEgJgHQgIgHgGgIQgFgJgDgKQgDgKAAgLQAAgMACgMQADgKAFgOQAGgRAPgaQAGgKAFgHQAHgIAIgFQAIgGAJgFIATgHQAPgDAigCQARAAAPACQAOADALAEQALAFAJAHQAIAHAGAIQAFAIADALQADAKAAALQAAALgCANQgDALgFAMQgNAggIAMQgGAKgHAHIgPANQgIAGgJAEQgJAFgKADQgeAFgTAAQgRAAgPgDgABUg4QgHADgFAGQgGAHgGALIgLAbQgFANgCALQgCAMACAHQACAIAGAEQAGAEALAAQAIAAAHgDQAHgDAGgGQAFgHAGgLIALgbQAGgNABgMQACgLgCgIQgCgHgGgEQgGgEgKAAQgJAAgHADgAmJBoIAMggQAFgNAGgIQAGgHALgGIBXgsQAOgIAHgFQAKgIADgJQACgFgBgFQAAgFgEgDQgDgDgIgCQgIgCgNAAQgUAAgVADIgeAHIATgyQAUgFAQgCQAUgDAVAAQAVAAAgAFIASAHQAIAEAGAFQAGAFADAGQADAGABAHQABAHgBAIIgEARQgFAMgIAJQgHAJgKAGQgKAHgOAHIhIAlIBqAAIgTAzg");
	this.shape.setTransform(-2.5,5.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AJcGYIgOgEIgLgFIgHgIQgDgEgCgFQgBgFAAgFIABgMIADgMIAGgMIAGgLIAIgIIAIgGIAKgFIAMgEQAIgCATAAIASABQAIABAGACQAGACAFAEQAEADADAEQADAEACAFIACAKIgCAMIgDANIgGAMIgGAKIgHAIQgEAEgFADIgKAFIgLADQgSADgKAAIgSgBgAJ4FHQgFABgEADQgEADgDAFQgDAFgDAHQgDAIAAAGQgBAGACAEQACAEAFACQAEACAHAAQAHAAAEgBQAFgBAEgDQAEgDADgFIAGgNQADgIAAgGQABgGgCgEQgCgEgEgCQgFgCgHAAQgGAAgFACgABgGYIgMgDIgKgEIgHgFIgEgHIgCgIQgBgEABgFIADgKIAWg8IApAAIgWA9QgCAFAAAEQgBAEACACQACACADABQADACAFAAIAHgBIAGgDIAFgGIAFgKIAWg9IApAAIgbBJIgGAKIgHAIIgIAGIgJAFIgKADIgaACIgOgBgAgPGYQgIgBgGgDIgLgFQgFgDgDgEIgFgJQgCgFAAgGQgBgGABgGIAEgOQADgHADgFIAHgKIAJgIIAJgHQAHgDAOgEQAIgCARAAQAMAAALACQALABAJAEIgJAaQgHgDgIgCQgKgCgIAAIgNABQgHACgFADQgDADgEAFQgFAGgCAIQgDAHABAGQAAAFAEAEQADADAGACQAEABAJAAIARgBIAPgDIgKAbIgRADIgRABIgPgBgAicGXQgJgCgPgEIAJgYQAIADAKACQALACALAAQALAAAFgBQAFgCACgEQABgEgBgDQgCgCgFgBIgPgDQgKgBgGgEQgGgDgDgFQgDgEAAgGQAAgGACgHQADgIAFgFQAFgFAIgEQAHgDAJgCQAKgBALAAQAKAAAQACQALACALADIgJAYQgHgDgJgCIgWgCIgOABQgEACgCAEQgBADABACQABACAFABIAQADQAHABAJAEQAHAEADAFQACAEAAAHQAAAGgDAHIgDAIIgFAGQgFAFgIAEQgHADgJABQgJACgLAAQgVgBgIgBgAHZGWIAchOIggAAIAKgaIBnAAIgJAaIgfAAIgdBOgAFxGWIgHhMIgbBMIgkAAIAmhoIAsAAIAHABIAEADIACAFIABAHIAHA9IAchNIAjAAIgmBogAC3GWIAmhoIBkAAIgJAYIg7AAIgGAQIA2AAIgJAYIg1AAIgGAQIA7AAIgJAYgAklGWIAlhoIBlAAIgJAYIg7AAIgGAQIA1AAIgJAYIg1AAIgGAQIA7AAIgIAYgAmsGWIAlhoIAzAAIARABIAOAEQAGACAEADIAHAHQADAEACAFQABAEAAAGIgBALIgDAMIgGAMIgGAJIgHAIIgJAGIgJAFIgLADQgQACgIAAgAl6F9IAQAAQAGAAAFgBQAFgCAEgDQAEgDADgFQADgEADgIIADgMQAAgFgBgEQgCgDgEgCQgEgCgGAAIgQAAgApIGWIAmhoIBkAAIgJAYIg7AAIgGAQIA2AAIgJAYIg1AAIgGAQIA7AAIgJAYgArPGWIAmhoIAyAAIASABIANAEQAGACAFADIAHAHQADAEABAFQACAEAAAGIgBALIgEAMIgFAMIgGAJIgIAIIgIAGIgKAFIgKADQgQACgJAAgAqdF9IAQAAQAHAAAFgBQAFgCADgDQAEgDAEgFQADgEACgIIADgMQABgFgCgEQgCgDgDgCQgEgCgHAAIgPAAgAgfhdIgWgGIAJgWIAQAFQALACAJAAQAJAAAEgCQAFgCACgDQABgEgBgDQgCgCgEAAIgNgDQgJgCgFgDQgHgCgCgFQgDgEAAgGQAAgFADgHQACgHAFgFQAEgFAIgDQAGgDAHgBQAJgCAKAAIAYACQAKABAKAEIgHAWIgQgEQgNgDgHAAQgJAAgDACQgFABgBAEQgBADABACIAFADIAPACQAGABAJAEQAGADADAFQACAEAAAGQAAAGgCAHIgEAHIgEAGQgFAFgHADQgGADgJABIgRABIgbgBgADpheIABgRIgoAAIgMARIgnAAIA8hUIAFgGIAFgEIAGgCIAGgBIAsAAIAABhgADRiGIAZAAIABgngABKheIAahIIgeAAIAJgZIBhAAIgJAZIgdAAIgaBIgAheheIAAgRIgoAAIgLARIgnAAIA8hUIAFgGIAEgEIAGgCIAGgBIAtAAIAABhgAh2iGIAZAAIABgngAjpheIANgkIghAAIgNAkIgmAAIAjhhIAmAAIgNAlIAhAAIANglIAmAAIgjBhgAA3jlQgNgCgLgDQgKgEgIgFQgIgFgFgHQgEgHgDgIQgDgIAAgKQgBgJACgLQACgLAFgMQACgLAFgJQAFgKAHgHQAGgIAIgGQAHgFAJgFQALgGAagGQAOgDAdgBQATAAASADQASADAPAGIgPArQgLgFgOgDQgPgDgOAAQgNAAgJACQgLACgJAFQgJAGgGAIQgHAJgFAOQgEAMABAJQABAJAFAGQAGAFAKADQAKADAPAAIAcgCIAZgEIgQAsQgNADgPACQgNABgQAAQgPAAgNgCgAHrjnIA/itICmAAIgOAoIhjAAIgJAaIBYAAIgPAoIhYAAIgKAbIBjAAIgPAogAENjnIA/itIB4AAQAMAAAQAEQALAEAHAIQAGAHABAJQABAKgEAKQgDAIgEAGQgFAGgGAFIgOAHQgIACgJABQAJACAHAEQAHAFADAGQAEAHAAAIQABAIgEAKQgDAJgGAHQgGAHgJAEQgJAFgNACQgMACgQAAgAFfkPIApAAQAMAAAFgCQAHgDACgHQADgJgEgFQgEgFgNAAIglAAgAF3lPIAeAAQAMAAAHgDQAGgDADgHQACgIgDgEQgDgEgLAAIghAAgACnjnIA+itIBEAAIg/CtgAjbjnIA+itICkAAIgMAoIhiAAIgKAaIBZAAIgPAoIhYAAIgKAbIBiAAIgOAogAk2jnIgSgyIgVAAIgTAyIhDAAIA+itIB0ACQAKABAJACIAOAGQAGAEAFAEQAEAFACAGQADAFAAAHQABAGgCAIQgBAHgDAIQgDAKgGAHQgFAHgHAFQgHAFgKADQgIADgLACIAaA8gAlPlBIAjAAIALgDQAFgCADgEQADgDADgHQACgGAAgEQAAgFgCgDQgDgDgFgBQgGgCgKAAIgUAAgAqYjnIAXhAIgnhtIBAAAIAWBAIBBhAIBMAAIh6ByIgVA7g");
	this.shape_1.setTransform(0.3,-4.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AJfGYIgOgEIgLgFIgHgIQgDgEgCgFQgBgFAAgFIABgMIADgMIAGgMIAGgLIAIgIQAEgEAEgCIAKgFIAMgEQAIgCATAAIASABQAIABAGACQAGACAFAEQAEADADAEQADAEACAFIACAKIgCAMIgDANIgGAMIgGAKIgHAIQgEAEgFADIgKAFIgLADQgSADgKAAIgSgBgAJ7FHQgFABgEADQgEADgDAFQgDAFgDAHQgDAIAAAGQgBAGACAEQACAEAFACQAEACAHAAQAHAAAEgBQAFgBAEgDQAEgDADgFIAGgNQADgIAAgGQABgGgCgEQgCgEgEgCQgFgCgHAAQgGAAgFACgABjGYIgMgDIgKgEIgHgFIgEgHIgCgIQgBgEABgFIADgKIAWg8IApAAIgWA9QgCAFAAAEQgBAEACACQACACADABQADACAFAAIAHgBIAGgDIAFgGIAFgKIAWg9IApAAIgbBJIgGAKIgHAIIgIAGIgJAFIgKADIgaACIgOgBgAgMGYQgIgBgGgDIgLgFQgFgDgDgEIgFgJQgCgFAAgGIAAgMIAEgOQADgHADgFIAHgKIAJgIIAJgHQAHgDAOgEQAIgCARAAQAMAAALACQALABAJAEIgJAaQgHgDgIgCQgKgCgIAAIgNABQgHACgFADQgFADgCAFQgFAGgCAIQgDAHABAGQAAAFAEAEQADADAEACQAGABAJAAIARgBIAPgDIgKAbIgRADIgRABIgPgBgAiZGXQgJgCgPgEIAJgYQAIADAKACQALACALAAQALAAAFgBQAFgCACgEQABgEgBgDQgCgCgFgBIgPgDQgKgBgGgEQgGgDgDgFQgDgEAAgGQAAgGACgHQADgIAFgFQAFgFAIgEQAHgDAJgCQAKgBALAAQAKAAAQACQALACALADIgJAYQgHgDgJgCIgWgCIgOABQgEACgCAEQgBADABACQABACAFABIAQADQAHABAJAEQAHAEADAFQACAEAAAHQAAAGgDAHIgDAIIgFAGQgFAFgIAEQgHADgJABQgJACgLAAQgVgBgIgBgAHcGWIAchOIggAAIAKgaIBnAAIgJAaIgfAAIgdBOgAF0GWIgHhMIgbBMIgkAAIAmhoIAsAAIAHABIAEADIACAFIABAHIAHA9IAchNIAjAAIgmBogAC6GWIAmhoIBkAAIgJAYIg7AAIgGAQIA2AAIgJAYIg1AAIgGAQIA7AAIgJAYgAkiGWIAlhoIBlAAIgJAYIg7AAIgGAQIA1AAIgJAYIg1AAIgGAQIA7AAIgIAYgAmpGWIAlhoIAzAAIARABIAOAEQAGACAEADIAHAHQADAEACAFQABAEAAAGIgBALIgDAMIgGAMIgGAJIgHAIIgJAGIgJAFIgLADQgQACgIAAgAl3F9IAQAAQAGAAAFgBQAFgCAEgDQAEgDADgFQADgEADgIIADgMQAAgFgBgEQgCgDgEgCQgEgCgGAAIgQAAgApFGWIAmhoIBkAAIgJAYIg7AAIgGAQIA2AAIgJAYIg1AAIgGAQIA7AAIgJAYgArMGWIAmhoIAyAAIASABIANAEQAGACAFADIAHAHQADAEABAFQACAEAAAGIgBALIgEAMIgFAMIgGAJIgIAIIgIAGIgKAFIgKADQgQACgJAAgAqaF9IAQAAQAHAAAFgBQAFgCADgDQAEgDAEgFQADgEACgIIADgMQABgFgCgEQgCgDgDgCQgEgCgHAAIgPAAgAqMDoIAKgcQgXgBgUgEQgTgEgSgHIASgxQAPAHAWAFQAWAEAVAAIAAAAIAPgnIgNgCQgUgDgMgGQgNgGgGgKQgGgKAAgMQAAgMAGgPQAFgPAKgLQALgLAPgFQAOgHAUgDQATgDAXAAIADAAIAJgYIAZAAIgJAZQATABASAEQAQAEAQAFIgRAvQgOgFgRgEQgUgFgTAAIgMAjIAIABQAOACATAIQANAGAGALQAGAKAAANQgBANgFAPIgIAPIgJANQgLALgPAHQgOAGgUADQgRADgYAAIgKAbgApVCbQAOgCAHgDQAHgEADgGQADgJgDgFQgDgFgKgBIgFgBgApTAlQgIADgCAGQgDAIADAEQACAEAKABIAKACIALggQgPABgIADgAjSDnIAvhSIBFAAIhABSgAHyDKQgOgCgMgFQgLgEgIgHQgJgHgFgIQgGgJgDgKQgCgKAAgLQgBgMADgMQACgMAFgOQAHgRAPgaQAGgKAHgHQAGgIAIgFQAIgGAJgDIAUgHQAOgDAjgCQARAAAOACQAOADAMAEQALAFAIAFQAJAHAFAIQAGAIADALQACAKAAALQABALgDANQgCAMgFANQgOAggIAMQgGAKgGAHIgPANQgIAGgJAEQgJAFgLADQgeAFgSAAQgSAAgOgDgAIoAmQgHADgGAGQgGAHgFALIgLAbQgGAPgCALQgCAMACAHQACAIAGAEQAHAEAKAAQAJAAAHgDQAGgDAGgGQAGgHAFgLIAMgbQAFgPACgMQACgLgCgIQgCgHgGgEQgGgEgKAAQgJAAgHADgAD8DKQgOgCgMgFQgLgEgIgHQgJgHgFgIQgGgJgDgKQgCgKAAgLQgBgMADgMQACgMAFgOQAHgRAPgaQAGgKAHgHQAGgIAIgFQAIgGAJgDIAUgHQAOgDAjgCQARAAAOACQAOADAMAEQALAFAIAFQAJAHAFAIQAGAIADALQACAKAAALQABALgDANQgCAMgFANQgOAggIAMQgGAKgGAHIgPANQgIAGgJAEQgJAFgLADQgeAFgSAAQgSAAgOgDgAEyAmQgHADgGAGQgGAHgFALIgLAbQgGAPgCALQgCAMACAHQACAIAGAEQAHAEAKAAQAJAAAHgDQAGgDAGgGQAGgHAFgLIAMgbQAFgPACgMQACgLgCgIQgCgHgGgEQgGgEgKAAQgJAAgHADgAAGDKQgMgCgMgFQgLgEgIgHQgJgHgFgIQgGgJgDgKQgCgKAAgLQgBgMADgMQACgMAFgOQAHgRAPgaQAGgKAHgHQAGgIAIgFQAGgGAJgDIAUgHQAOgDAjgCQARAAAOACQAOADAMAEQALAFAIAFQAJAHAFAIQAGAIADALQACAKAAALQABALgDANQgCAMgFANQgOAggIAMQgGAKgGAHIgPANQgIAGgJAEQgJAFgLADQgeAFgSAAQgSAAgOgDgAA8AmQgHADgGAGQgGAHgFALIgLAbQgGAPgCALQgCAMACAHQACAIAGAEQAHAEAKAAQAJAAAHgDQAGgDAGgGQAGgHAFgLIAMgbQAFgPACgMQACgLgCgIQgCgHgGgEQgGgEgKAAQgJAAgHADgAmiDIIAMggQAFgNAGgIQAGgHALgGIBXguQAPgIAGgFQAKgIADgJQACgFAAgFQgBgFgDgDQgEgDgIgCQgIgCgMAAQgVAAgUADIgeAHIASgwQAUgFARgCQAUgDAVAAQAVAAAfAFIATAHQAIADAGAEQAFAFAEAGQADAGABAHQABAHgBAIIgFARQgFAMgHAJQgHAJgLAIQgJAHgPAHIhHAlIBpAAIgSAzgAgchdIgWgGIAJgWIAQAFQALACAJAAQAJAAAEgCQAFgCACgDQABgEgBgDQgCgCgEAAIgNgDQgJgCgFgDQgHgCgCgFQgDgEAAgGQAAgFADgHQACgHAFgFQAEgFAIgDQAGgDAHgBQAJgCAKAAIAYACQAKABAKAEIgHAWIgQgEQgNgDgHAAQgJAAgDACQgFABgBAEQgBADABACIAFADIAPACQAGABAJAEQAGADADAFQACAEAAAGQAAAGgCAHIgEAHIgEAGQgFAFgHADQgGADgJABIgRABIgbgBgADsheIABgRIgoAAIgMARIgnAAIA8hUIAFgGIAFgEIAGgCIAGgBIAsAAIAABhgADUiGIAZAAIABgngABNheIAahIIgeAAIAJgZIBhAAIgJAZIgdAAIgaBIgAhbheIAAgRIgoAAIgLARIgnAAIA8hUIAFgGIAEgEIAGgCIAGgBIAtAAIAABhgAhziGIAZAAIABgngAjmheIANgkIghAAIgNAkIgmAAIAjhhIAmAAIgNAlIAhAAIANglIAmAAIgjBhgAA6jlQgNgCgLgDQgKgEgIgFQgIgFgFgHQgEgHgDgIQgDgIAAgKQgBgJACgLQACgLAEgMQADgLAFgJQAFgKAHgHQAGgIAIgGQAHgFAJgFQALgGAagGQAOgDAdgBQATAAASADQASADAPAGIgPArQgLgFgOgDQgPgDgOAAQgNAAgJACQgLACgJAFQgJAGgGAIQgHAJgFAOQgEAMABAJQABAJAFAGQAGAFAKADQAKADAPAAIAcgCIAZgEIgQAsQgNADgPACQgNABgQAAQgPAAgNgCgAHujnIA/itICmAAIgOAoIhjAAIgJAaIBYAAIgPAoIhYAAIgKAbIBjAAIgPAogAEQjnIA/itIB4AAQAMAAAQAEQALAEAHAIQAGAHABAJQABAKgEAKQgDAIgEAGQgFAGgGAFIgOAHQgIACgJABQAJACAHAEQAHAFADAGQAEAHAAAIQABAIgEAKQgDAJgGAHQgGAHgJAEQgJAFgNACQgMACgQAAgAFikPIApAAQAMAAAFgCQAHgDACgHQADgJgEgFQgEgFgNAAIglAAgAF6lPIAeAAQAMAAAHgDQAGgDADgHQACgIgDgEQgDgEgLAAIghAAgACqjnIA+itIBEAAIg/CtgAjYjnIA+itICkAAIgMAoIhiAAIgKAaIBZAAIgPAoIhYAAIgKAbIBiAAIgOAogAkzjnIgSgyIgVAAIgTAyIhDAAIA+itIB0ACQAKABAJACQAIADAGADQAGAEAFAEQAEAFACAGQADAFAAAHQABAGgCAIQgBAHgDAIQgDAKgGAHQgFAHgHAFQgHAFgKADQgIADgLACIAaA8gAlMlBIAjAAIALgDQAFgCADgEQADgDADgHQACgGAAgEQAAgFgCgDQgDgDgFgBQgGgCgKAAIgUAAgAqVjnIAXhAIgnhtIBAAAIAWBAIBBhAIBMAAIh6ByIgVA7g");
	this.shape_2.setTransform(-1,-3.9);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-73.3,-45.3,145.6,82.4);


(lib.LOGO_mc = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("Ag9BwQgFgGAFgGIAJgOIADgFQgGgGAAgGIAAgCQAAgEACgCIADgEQgCgIACgEQADgIAFgDIACgDQgGgNAJgKQgDgIAHgIQgDgGACgIQgCgCgBgFQgJgBgGgIQgGgBgFgEQgEgEgBgHQgHgGAAgKQgCgDABgEQABgEACgBQgHgGgBgEQgCgFABgKQgEgGAEgDQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAQADgCADACQAFgBAFAJIADgCQAEgBADADQABADgBACQgCACADAFIABAHQAGAFAAADQAEACABADIAGACQAFgBAFADQAGgDAHAAQgDgEAAgFQAAgGADgDQgBgGADgFQADgFAGgCQAAgEAGgBQAHAAABAEQALAEAAAMQAEADABAGQAAAGgDAEQAKABAEAEQAGAAAGAFQAGAGgCAIQAFAEABAHIAAABQAAAFgCADQAFAFAAAGQANAHgGAMQAAACAIADQAGAHgDAFQABAEgEACQgEABgDgCIgEADQgCACgDgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQgGgEADgEIgBgCQgIAAgEgEQACAGgEAIQACALgIAIQABAFgBAEQAGAIgJALIAAABQABAEgBAEQgDAHgHADQACAGABABIAAABIAGADQAHAFAAAGIAAAFQgCAEgJACQgIACgEgCQgDgBgCgEIgEgGIgHgHQgBgEAAgEQABgEADgEQgEgEgBgFQgCgEABgEIACgEQgEgHAAgCIgCAFQABAEgBAEQgBAEgEAEIgFADQgBAMgJACIgDABQgDAGAAAEQADAJAAAFQgCAJgQAAQgIgBgGgHgAg5BmQgDAEADAFQAGAHAKgCIAAAAQgKABgFgHIABgBQAKAIAKgGQAAAAABAAQAAAAAAgBQABAAAAgBQAAAAAAAAIgDgMQAAgCADgIQgJAAgDgEIgMATgAAFBVQgCAHAIAHIADAFQACACADACQAEACAGgCQAHgBABgDIgBAAQgDADgFAAQgFABgCgCIAAAAQALAAADgEQAEgDgGgEIgIgFIgHABIgBgDIAGgBIgBgCIgHABIAAgDIAGgBIAAgCQgHABgGgCgAgyBIQADAIAHACQAJAEAFgFQAFgDABgFQgGACgGgCQgKgCgGgLQgEAFACAHgAAEBJQAEAEAHABQAPAAAAgPQgGAEgIAAQgJAAgGgHQgBAIAEAFgAguA5QAEAKAIADQAMAEAIgHQAFgGgBgGQgJAHgLgFQgMgGAAgLQgIAHAEAKgAABA4QAFAIAKABQALAAAFgIQAFgGgDgGQgHAIgMgBQgMgBgDgLQgDAHAEAJgAglAuQADAGAFADQAJADAHgEQAGgEgBgFQgSADgLgOQgDAFADAHgAACAmQABAFAFADQAFAEAFAAQAHAAAEgEQAFgFgBgHQgPAKgNgLgAghAhQAHAKALgBQASAAABgRQgJAGgMgEQgMgEgFgLQgHALAIAKgAAIAXIgCAIQAJAIAMgFQANgFgBgNQgNAMgSgGgAgfAMQAFAKALACQALADAHgEQAHgFAAgHQgcAAgNgPQgFAGAFAKgAAOAKQAAAGgEAEQAMADAKgFQAKgGAAgMQgKAJgSABgABDAQIACAAIADgDIgBgBQgHABADADgABFAIIAEADQAEAFADgCQAAgBABAAQAAAAAAgBQAAAAAAAAQgBgBAAAAIgDgEQgFgFABgCIABABIAHAHQgCgEgDgCIgGgDQgCABgGABIAAADQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIACAAQAAAAABAAQAAAAABABQAAAAABABQAAAAAAABgABAAKQAAAAAAABQAAAAAAABQAAAAAAAAQABABAAAAIADgCQAAgBgBgBQAAAAAAgBQgBAAAAgBQAAAAgBAAIAAAAIgBADgAA9AGQAAAAAAABQgBAAAAABQAAAAABABQAAAAABABQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAAAIgBgBIgBAAgAgRACQANAGAOgBQATAAAJgHQAHgGgBgIQgOALgYgCQgWgBgOgNQgCAPAPAGgAAwgJQgBAFAFADQAFABAHgBQAFgCACgHQAAgHgHgDQgEAJgMACgAgggeQABAJANAGQAOAHAOAAQAZAAAKgMQAIgKgFgJQgKAKgWACQgWACgNgKQgFAEgIABgAA0gcQAAAEgFAGIABAGQAIgBAEgGQAEgHgGgHQgBAEgFABgAgRgmQAJAIAQAAQAVAAALgIQAOgKgKgOQgGAHgSADQgUADgNgGQAAAJgEAIgAAygrQACAEABAGQAKgFgIgNQgCAFgDADgAgdgwQgFAJgMAAQAGAHALgCQAMgDAAgNQABgSgPgEQAIAOgGAKgAgzgrQAKAEAHgJQAGgGgDgKQgDgJgEAAQACALgJAHQgIAHgKgFQADAIAJACgAAthCQAHAGAAAIQADgGgDgGQgDgEgEgBgAg7g2QAIABAFgFQAJgJgFgIIgDgDQgBAIgJAEQgIAEgHgFQACAKAJADgAgVhHQAFAEACAIQAJAFALAAQAPAAAKgEQAKgEABgFQACgHgVgBQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAABAAQAAgBAAAAQADgDgCgCQAFAAAAgIQABgGgFgEIAAgBQABgKgMgDIAAAAIAAgBIgDgBIgFABQAAAAAAAAQAAAAAAAAQAAAAABABQAAAAABAAIAAAAQgEAAgCAEQgFAEAAAHIAEAAIAAABQgGABgBAGQgBAHAHAEIAAAAQAAABgBAAQAAABAAAAQAAABAAAAQABAAAAABIABABQAAAAAAAAQgBABAAAAQAAAAgBgBQAAAAgBAAIgGgBIgJACgAhFhFQAFAFAIgEQAIgEAAgGQABgGgGgDQgBABAAAFQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgCAAQABgCAAgDQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAIABgFIgCgGQgBgFACgEQgBgBgBAAQAAAAgBAAQAAAAgBAAQAAAAAAABQgCAEACAFIgDAEIAAABIgBAAQgBgDACgCIgCgHQgDgJgEAAIAGALQAAAAAAAAQAAABAAAAQAAAAAAAAQAAABgBAAQgFgKgDgDQAAgBgBAAQAAgBgBAAQAAAAgBAAQAAAAgBABIADACIAHANIgBAAQAAAAAAAAQgBAAAAgBQgBAAAAgBQAAgBgBgBIgFgIQAAAAAAAAQgBAAAAAAQgBAAAAAAQAAAAgBAAIACAEQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIABACIADAJIgCAAQgCgCAAgHIgCgBIgBAAQAAAJACAEQABAEAHAFQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQABAEADgBIABABQgEADgCgDIgCgDQgGAGAGAFgAgvBgIAAgCQAFAAAEABIgCACgAguBbIAAgDIAJACIgBACgAAFhTIgEgBIgBABIABgDIAAgBIACABIAFAAIAHAAIABgBIABADIgBAAIgFADIgBAAQgCAAgDgCgAAFhUIADACIADAAIADgDIgCgBIgHACgAAAhbQAAgCAAgEQAAgHADAAQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAAAABQADABAAAFQABAHgGAAIgDgBgAAAhhIAAAEIAAgCQAAgFADAAQADAAAAAFIAAABIAAgDQAAgEgBgBIgCgBQgDAAAAAGgAANhbQgCgBgBgFQAAgGAEgCQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQADACAAADQABAHgFAAgAARhgIgBADIABAAIABgFQAAgDgDgBIgBgBQgEAAABAGQAAgBABgBQAAAAAAgBQABAAAAAAQABAAAAAAQADAAAAAEgAhEhdIgDgBIADgBIACABIAAACIAAAAIgCgBg");
	this.shape.setTransform(-29.3,-0.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FAE22B").s().p("AjTAEQABgEAAgDIIPAAIgDAHgAkCAEQAEgEACgDIAEAAQgBADABAEgAk8AEIAAgHIAQAAQgCADAAACIAAACg");
	this.shape_1.setTransform(-4.7,5.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1960A6").s().p("AkiBBQgBgBgCgGQAHgDADgHIIMAAIAEgIIoQAAIAAgBQAJgLgGgIQABgEgBgFQAIgIgCgJQAEgIgCgIQAEAGAIAAIABACQgDAEAGAEQAAABAAAAQAAABABAAQAAABAAAAQAAAAABAAQAAABAAAAQAAAAAAABQABAAAAABQAAAAABAAQADABACgBIAEgCQADACAEgBQAEgCgBgEQADgFgGgHQgIgFAAgCQAGgMgNgHQAAgGgFgFQACgDAAgFIKEAAIAACBgAgdghQgQADgLAJQgOALABAOQAAAJAKAHQAKAFAOAAQASgBADgCIAIgSQgTADgGgCQgJgDADgGQACgHAIgEQAIgDAHAAQAJAAADAGIAGgVQgHgCgJAAQgKAAgJACgAEvAXIAoAAIAWg5IgYAAIgPAnIABgbQABgFgDgEIgFgDIgiAAIgVA5IAYAAIAPgngADdAXIAcAAIAWg5IgdAAgACdAXIA3AAIAHgUIgcAAIAPglIgcAAgABTAXIA8AAIAFgQIghAAIADgGIAeAAIAGgNIgfAAIACgHIAhAAIAFgPIg7AAgAAvADIgHAUIAaAAIAWg5IgbAAIgIAWIgOAAIAIgWIgbAAIgUA5IAZAAIAHgUgAh3AXIAdAAIAVg5IgcAAgAihAXIAaAAIAWg5IgoAAIgWAgIACgUQACgMgJAAIghAAIgWA5IAaAAIAPgoIgDAoIAXAAIAcgogAlZBBQAJgCABgMIAFgDIAKAAQACAFAFAEQgDAEgBAEgAmFBBIAAgRIAPAAQAAAGAGAGIgDAFgAlFAoQABgEgBgEIACgFQAAACAEAHIgCAEgAmFAoIAAhoIAHAAQAFAEAGABQAGAIAJABQABAFACACQgCAIADAGQgHAIADAKQgJAKAGALIgCADQgFADgDAIQgCAEACAIIgDAEg");
	this.shape_2.setTransform(2.6,1.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ApYEGIC/oLIPyAAIAAILgAk1A+IAAAIIAAARIASAAIgJAOQgFAGAFAGQAGAHAIABQAQAAABgJQABgFgDgJQAAgEADgGIACgBIAdAAQAAAEABAEIAHAHIAEAGQACAEADABQAEACAIgCQAJgCACgEIAAgFQAAgGgIgFIgFgDIAAgBIKnAAIAAiBIqEAAIAAgBQAAgHgFgEQABgIgGgGQgFgFgHAAQgDgEgKgBQADgEAAgGQgBgGgEgDQAAgMgLgEQgCgEgHAAQgGABgCAEQgFACgDAFQgDAFAAAGQgCADAAAGQAAAFACAEQgGAAgGADQgGgDgFABIgFgCQgCgDgDgCQAAgDgGgFIgCgHQgCgFACgCQABgCgCgDQgDgDgDABIgDACQgGgJgFABQgCgCgEACQAAAAgBAAQAAAAgBABQAAAAAAAAQgBABAAAAQgDADADAGQAAAKABAFQACAEAHAGQgDABAAAEQgBAEACADQAAAKAHAGQABAHAEAEIgHAAgAkoBwQgDgFADgEIAMgTQACAEAKAAQgEAIABACIADAMQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAQgJAGgLgIIAAABQAEAHALgBIAAAAIgEABQgHAAgFgGgAkfBhIAIABIABgCQgEgBgFAAgAkeBcIAJABIABgCIgKgCgAjaBtQgDgCgCgCIgDgFQgIgHACgHIADgGQAFACAIgBIAAACIgHABIABADIAHgBIAAACIgFABIAAADIAHgBIAJAFQAGAEgFADQgCAEgLAAIAAAAQABACAGgBQAFAAACgDIACAAQgCADgGABIgGABIgEgBgAkXBTQgIgCgCgIQgCgHAEgFQAFALALACQAGACAFgCQgBAFgEADQgDADgEAAIgHgCgAjfBPQgGgBgEgEQgFgFACgIQAFAHAKAAQAIAAAGgEQgBAPgOAAIgBAAgAkSBHQgHgDgEgKQgEgKAIgHQAAALAMAGQALAFAJgHQABAGgFAGQgGAEgGAAQgEAAgFgBgAjsA5QgGgJAEgHQAEALALABQANABAHgIQADAGgFAGQgFAIgMAAQgJgBgFgIgAkNA4QgEgDgEgGQgDgHAEgFQALAOASgDQABAFgGAEQgFACgEAAIgIgBgAjmAvQgEgDgBgFIACgFQAOALAPgKQABAHgFAFQgFAEgGAAQgFAAgGgEgAATAqQgLgHAAgJQAAgQAOgKQALgIAPgDQAUgEASAEIgIATQgDgGgJAAQgIAAgHADQgIAEgCAHQgDAIAJADQAGACASgDIgHASQgDACgSABQgPAAgJgFgAF/AtIABgpIgPApIgYAAIAVg5IAhAAIAFADQADAEAAAFIgBAbIAPgnIAXAAIgWA5gAEsAtIAWg5IAcAAIgVA5gADsAtIAWg5IAcAAIgPAlIAcAAIgIAUgACiAtIAWg5IA7AAIgGANIggAAIgCAHIAfAAIgGAPIgfAAIgCAGIAhAAIgFAQgAB3AtIAHgUIgOAAIgHAUIgbAAIAVg5IAbAAIgHAUIAOAAIAIgUIAbAAIgWA5gAgnAtIAWg5IAaAAIgTA5gAhRAtIAPgqIgdAqIgWAAIADgqIgQAqIgZAAIAVg5IAiAAQAIAAgBAMIgCASIAWgeIAnAAIgVA5gAkQAiQgJgKAHgLQAGALAMAEQAMAEALgGQgBARgUAAIgBAAQgKAAgHgJgAjoAgIACgIIABgBQARAGAOgMQABANgNAFQgFACgEAAQgHAAgGgFgAj+AZQgMgCgEgKQgGgKAGgGQANAPAeAAQAAAHgHAFQgGACgGAAIgIgBgAjjAVQADgEAAgGQATgBAJgJQABAMgKAGQgGADgHAAIgJgBgAiqARQgDgDAGgBIACABIgEADIgBAAIAAAAgAikAMIgEgDQgCgEgDABQAAAAAAAAQgBgBAAAAQAAAAAAAAQgBAAAAAAIgBgDQAHgCABAAIAHADQADACABAEIgGgHIgBgBQgCACAFAFIADAEQABAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAIgBAAQgCAAgDgDgAitALQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAABIgCACQgBAAAAAAQAAgBAAAAQAAAAAAgBQAAgBAAAAgAiwAHQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAAAABQgBAAAAABQAAgBAAAAQgBgBAAAAQAAgBAAAAQABAAAAgBgAkAADQgPgGACgPQAOANAYABQAYACANgLQACAIgHAFQgJAIgTAAIgCAAQgPAAgMgFgAi6AAQgEgDABgFQAMgCAEgJQAHADgBAHQgBAHgFACIgHAAQgDAAgDAAgAkBgOQgNgGgBgJQAIgBAEgEQANAKAYgCQAXgCAKgKQAEAJgIAKQgJAMgZAAIgCAAQgPAAgNgHgAi+gRQAFgGAAgEQAEgBACgEQAGAHgFAHQgDAGgIABgAjlgdQgSAAgKgIQAFgIAAgJQAOAGAVgDQASgDAFgHQAKAOgNAKQgLAIgTAAIgCAAgAi8gqQADgDADgFQAIANgKAFQgBgGgDgEgAkdgmQAMAAAFgJQAGgKgIgOQAPAEgBASQgBANgLADIgFAAQgIAAgEgFgAkigqQgKgCgCgIQAKAFAIgHQAJgHgCgLQAEAAADAJQADAKgGAGQgFAGgGAAIgGgBgAjAhBIgBgDQAFABACAEQADAGgDAGQAAgIgGgGgAkqg1QgJgDgDgKQAIAFAIgEQAJgEABgIIADADQAFAIgJAJQgEAEgGAAIgDAAgAj9g6QgCgIgFgEQAJgDAGACQABAAAAABQABAAAAAAQAAAAAAAAQABgBAAAAIgBgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBIAAAAQgHgEABgHQABgGAGgBIAAgBIgEAAQAAgHAEgEQAEgEAFAAIAAAAQgBAAgBAAQAAAAAAgBQgBAAAAAAQAAAAABAAIAEgBIAEABIAAABIAAAAQAMADgBAKIAAABQAEAEAAAGQAAAIgFAAQACACgDADQgBAAAAABQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAQAAgBABAAQABAAAAgBQAUABgBAHQgBAFgKAEQgKAEgPAAQgNAAgJgFgAjphSQAFAEACgCIAEgDIACAAIgBgDIgBABIgIAAIgEAAIgCgBIAAABIgCADIACgBgAjqhnQgFAAAAAHQAAAEACACIADABQAGAAgCgHQAAgFgCgBIgBgBIgBAAgAjjhgQABAFACABIABAAQAFAAAAgHQAAgDgDgCQAAgBgBAAQAAAAAAAAQAAgBgBAAQAAAAgBAAQgDACAAAGgAk0hEQgGgFAGgGIACADQABADAEgDIAAgBQgDABgBgEQgBAAAAgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQgHgFgBgEQgCgEAAgJIABAAIACABQAAAHABACIACAAIgCgJIgBgCQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgBgEQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAIAFAIQAAABABABQAAABABAAQAAABAAAAQABAAAAAAIABAAIgHgNIgDgCQAAgBABAAQAAAAABAAQAAABABAAQAAABABAAQADADAFAKQAAAAABAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIgGgLQAEAAADAJIABAHQgBACAAADIABAAIABgBIADgEQgDgFADgEQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQgBAEABAFIACAGIgBAFQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQABADgBACIABAAQABAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAAAQAAgFABgBQAFADAAAGQAAAGgJAEQgDACgDAAQgEAAgCgDgAk3hdIAEABQAAAAABABQAAAAAAAAQABAAAAAAQAAAAAAAAIAAgCIgCgBgAjlhRIgDgCQAEgCAFABIgDADIgBAAIgCAAgAjdhcIABgDQAAgEgDAAQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABAAABQgBgGAEAAIABABQACABAAADIAAAFgAjuhgQgBgGAFAAIABABQACABAAAEIgBADIAAgBQABgFgDAAQgDAAAAAFIAAACg");
	this.shape_3.setTransform(-5.4,-1);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-65.5,-27.3,120.2,52.6);


(lib.Info_btn = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEE32B").s().p("AgXCGQgdgFALgeQALgdAegBQAUAAAHALQAHAJgGAQQgKAdgdAAQgEAKANAAIAGgBIgEALIgGABQgZAAAIgVgAgZBlQgIAWAWgBQAJAAAEgEQAGgEAEgLQAIgWgUAAQgSAAgHAUgAAnB+QgHgGAGgNIAMgkIARAAIgOAkQgGAPASAAQAOAAAFgPIANgkIAQAAIgMAkQgGAPgJAHQgIAGgQgBQgRAAgGgIgABpCFIAXg+IAQAAIgWA+gAhECFIAAgNIgfAAIgJANIgSAAIArg4QADgGAGAAIASAAIADA+gAhbBsIAWAAIgBgegACCBDIARgPIARAAIgUAPgADjAUQgGgKAGgNQAKgdAgAAQAUgBAHALQAHAJgGAPQgKAdggAAQgVAAgHgLgADygCQgIAVAXgBQARAAAIgSQAHgVgWABQgRAAgIASgACAAVQgIgKAGgPQALgcAhAAQAMAAAMADIgFAMQgJgDgKAAQgVgBgIAUQgGATAYAAQALAAAIgDIgEANQgIACgLABQgUgBgHgJgAjHAUQgGgKAFgNQALgdAgAAQAVgBAHALQAGAJgFAPQgMAdgfAAQgUAAgIgLgAi3gCQgJAVAWgBQASAAAHgSQAIgVgVABQgTAAgGASgAFXAdIgMgwIgSAwIgPAAIAXg8IAQAAQAGgBACAHIALAqIATgwIAOAAIgXA8gAC6AdIAXg8IAQAAIgWA8gABiAdIAAgOIgeAAIgJAOIgSAAIAqg3QAEgFAGAAIATAAIACA8gABNAFIAVAAIgBgcgAAQAdIASgwIgkAwIgQAAIgCgxIgTAxIgPAAIAXg8IARAAQAGgBABAJIADAjIAhgrIAaAAIgXA8gAhTAdIgHgUIgOAAIgHAUIgRAAIAXg8IAcAAQAhAAgKAYQgEAMgQABIAJAXgAhkgBIALAAIANgBQAFgBACgGQAEgLgQAAIgLAAgAkPAdIAXg8IA2AAIgEALIgmAAIgHASIAjAAIgEAIIgiAAIgIAXgAk3AdIgMgwIgSAwIgPAAIAXg8IAQAAQAGgBACAHIAKAqIATgwIAPAAIgXA8gAmEAdIAXg8IAPAAIgVA8gAEKgkIARgNIARAAIgTANgAAyhNIAEgMQAMAGANAAQAOAAADgHQADgGgKgDIgKgCQgTgDAGgRQAGgQAYAAQAOAAANAGIgDALQgMgGgMAAQgMAAgDAHQgCAEAIADIALACQATAEgFASQgHAQgZAAQgRABgNgGgAAehJIAAgNIgeAAIgIANIgRAAIAng4QAEgHAHAAIASAAIACA/gAAHhiIAXAAIgBgegAgzhJIATgzIgnAzIgPAAIgEgzIgSAzIgOAAIAWg/IARAAQAHAAAAAIIADAlIAjgtIAaAAIgXA/gAAZiMIAQgOIASAAIgUAOg");
	this.shape.setTransform(-1,-0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("Am4C4IAAlvINxAAIAAFvgAg0BiQgLAdAdAGQgIAUAZAAIAIAAIAEgLIgIABQgMAAADgKQAdgBAKgcQAGgQgHgJQgHgLgSAAQggAAgLAegAAbBqQgFAMAGAHQAGAIARAAQAQAAAIgGQAJgGAGgPIANgkIgQAAIgOAkQgFAPgOAAQgRAAAGgPIANgkIgRAAgABfCEIAQAAIAWg+IgQAAgAhPB2IAAAOIAPAAIgCg+IgTAAQgGAAgDAFIgqA5IARAAIAKgOgAB3BBIAPAAIATgOIgRAAgADYgFQgGAOAGAJQAHALAVAAQAgAAAKgdQAGgOgGgKQgIgKgUAAQgfAAgLAdgAB0gGQgHAPAIAKQAHAKAUAAQAMAAAHgCIAFgNQgIACgMABQgYgBAHgSQAHgUAVAAQAKAAAKAEIAEgMQgMgEgMAAQghAAgKAcgAjSgFQgGAOAHAJQAHALAUAAQAfAAAMgdQAGgOgHgKQgHgKgVAAQggAAgKAdgAFMAbIAYAAIAWg8IgOAAIgTAxIgLgqQgCgHgGAAIgQAAIgXA8IAPAAIASgvgACvAbIARAAIAWg8IgQAAgABXAOIABANIAPAAIgCg8IgTAAQgGAAgEAGIgpA2IARAAIAJgNgAAFAbIAQAAIAXg8IgaAAIghArIgDgjQAAgIgHAAIgRAAIgWA8IAOAAIATgwIACAwIAQAAIAkgvgAhkAIIAHATIARAAIgJgWQAQgCAFgLQAJgZghAAIgcAAIgWA8IAQAAIAHgTgAkZAbIAQAAIAIgWIAiAAIAFgJIgjAAIAGgRIAnAAIADgMIg2AAgAlCAbIAYAAIAWg8IgOAAIgTAxIgLgqQgCgHgGAAIgQAAIgXA8IAPAAIASgvgAmPAbIARAAIAWg8IgQAAgAD/glIAPAAIATgOIgRAAgAAohPQAMAGASAAQAZAAAGgQQAGgSgUgFIgLgCQgHgCACgFQACgGANAAQALAAAMAFIAEgLQgOgGgNAAQgZABgGAPQgGARAUAEIAKACQAJACgDAHQgCAHgOgBQgOABgMgGgAAThYIAAAOIAPAAIgCg/IgSAAQgHAAgDAGIgoA5IASAAIAJgOgAg+hKIARAAIAWg/IgaAAIgjAtIgDglQAAgIgHAAIgRAAIgWA/IAPAAIASgzIADAzIAPAAIAngzgAAOiOIAOAAIAUgNIgRAAgAgkBjQAIgTASAAQATAAgIAVQgCAMgGADQgGAFgJAAQgWAAAIgWgAhmBrIAVgeIABAegADogDQAHgTASAAQAVAAgHAWQgHARgSAAQgXAAAJgUgAjCgDQAHgTASAAQAWAAgJAWQgHARgSAAQgVAAAIgUgABCADIAVgcIAAAcgAhvgCIAIgUIALAAQAQAAgEAMQgCAFgFACIgMABgAgBhjIATgfIABAfg");

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-44.1,-18.4,88.4,36.9);


(lib.COM = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIzC1QgNgCgUgHIANghQAKAEAOADQAQADAOAAQAQAAAHgCQAHgCACgGQADgGgDgDQgBgEgIgBIgVgEQgOgCgJgFQgIgEgEgHQgEgGAAgIQAAgIAEgKQAEgLAGgHQAIgIAJgEQALgFANgCQANgDAQAAQAOAAAWADQAPADAPAFIgMAhQgKgEgNgCQgTgEgKAAQgOAAgGACQgGACgCAGQgCAFACACQABADAHACIAWADQAJACAOAGQAIAEAEAHQAFAHAAAJQgBAIgEALIgFAKIgGAJQgIAHgKAFQgJAEgOACQgMACgQAAQgdgBgLgBgAHUC0IABgZIg8AAIgRAZIg7AAIBhiHQAEgEAEgCIAIgDIAKgBIBBAAIAACRgAGvB4IAmAAIACg7gADmC0IAnhtIgtAAIAOgkICQAAIgNAkIgrAAIgoBtgABWC0IgJhqIgnBqIgvAAIAziRIA9AAQAFAAAEACQAEABACADQADADABAEIABAJIAJBVIAmhrIAyAAIg1CRgAhKC0IABgZIg9AAIgRAZIg6AAIBhiHQADgEAEgCIAIgDIAKgBIBCAAIAACRgAhvB4IAmAAIABg7gAlZC0IA1iRIA5AAIgoBsIBLAAIgOAlgAnuC0IA1iRIA5AAIgoBsIBLAAIgNAlgAp+C0IAMghIhTAAIAPgnIBCg7QAHgHAGgDQAGgEAHAAIBHAAIgdBRIAUAAIgLAfIgVAAIgMAhgAqRB0IArAAIAVg9gAm1AAQgNgCgLgEQgLgEgHgFQgIgGgFgHQgFgHgCgIQgEgIAAgKQAAgJACgKIAGgVQAEgLAFgJQAFgKAGgIQAGgIAHgGQAHgGAHgFIARgIQAKgEAJgCQAOgCAhgCQAQAAAOACQANACAKAEQALADAIAGQAHAGAGAGQAFAHACAJQACAHAAAKIgBATQgCALgEALIgJAUIgLARQgGAIgHAGQgHAHgHAEQgIAFgJAEIgTAFQgdADgRAAQgRAAgNAAgAmGiJQgJADgHAEQgGAGgGAIQgFAJgEAMQgGANAAAKQgBAKADAHQADAGAIAEQAHAEANAAQAKAAAIgDQAJgCAFgFQAIgFAFgIQAGgJAFgMQAEgOAAgJQACgLgEgGQgDgHgHgDQgJgEgLAAQgLAAgHACgAp4AAQgNgCgLgEQgLgDgHgGQgIgFgGgHQgFgGgDgJQgEgIAAgKIABgVQADgLAEgMQAEgLAFgKQAGgJAHgIIAOgNQAHgGAJgFQALgGAagHQAPgCAdgBQATAAATADQASADAQAGIgQArQgLgEgPgDQgPgDgOAAQgMAAgKACQgLACgJAFQgJAGgGAIQgIAJgFAOQgEANABAJQABAJAGAGQAGAFAJADQALADAOAAIAdgCQAPgCALgDIgRAuQgNADgPABQgNAAgRAAQgPAAgNAAgAJfgDIABgeIhJAAIgVAeIhGAAIB1ijQADgEAGgDIAKgDIALgCIBQAAIAACvgAIzhLIAuAAIABhIgAFvgDIgSgyIgWAAIgSAyIhFAAIA/ivIBeAAIAXACIATADQAJADAGADQAHAEAEAFQAEAEADAGQACAGAAAGQABAHgBAIIgFAQQgDAJgGAHQgGAIgGAFQgIAFgJADQgJADgLACIAbA8gAFVhdIAjgBIAMgCQAFgDADgDQAEgEACgHIACgKQABgFgDgDQgDgDgGgCQgFgBgKAAIgUAAgAAcgDIBAivIBYAAQAOAAALACQAMACAJADQAJACAHAEQAGAFAEAFQAFAFACAHQACAGAAAHQABAIgCAHIgEARIgHAQIgJAMQgFAFgGAEIgMAHQgNAGgRACQgOACgVAAIgoAAIgQApgAB+hUIATAAIARgBQAIgBAGgDQAEgDADgEIAGgMIADgNQAAgGgCgDQgCgEgHgCQgGgBgJAAIgVAAgAhKgDIAuh+IhaB+Ig8AAIABiBIgwCBIg6AAIA/ivIBKAAQAHAAAFACQAFACACADQADAEABAFIACANIABBNIBJhqIBoAAIg+Cvg");
	this.shape.setTransform(0.7,-11.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AIzC1QgNgCgUgHIAMghQALAEAOADQAQADAOAAQAQAAAHgCQAHgCACgGQADgGgDgDQgBgEgIgBIgVgEQgOgCgJgFQgIgEgEgHQgEgGAAgIQAAgIAEgKQADgLAHgHQAIgIAKgEQAKgFANgCQANgDAQAAQAOAAAWADQAPADAPAFIgMAhQgKgEgNgCQgTgEgKAAQgOAAgGACQgGACgCAGQgCAFACACQABADAHACIAWADQAJACAOAGQAIAEAEAHQAEAHABAJQgBAIgEALIgFAKIgGAJQgIAHgKAFQgJAEgOACQgMACgQAAQgdgBgLgBgAHUC0IABgZIg8AAIgRAZIg7AAIBhiHQADgEAFgCIAIgDIAKgBIBBAAIAACRgAGvB4IAmAAIACg7gADmC0IAnhtIgtAAIAOgkICQAAIgNAkIgrAAIgnBtgABWC0IgJhqIgnBqIgvAAIAziRIA9AAQAFAAAEACQAEABACADQADADABAEIABAJIAJBVIAmhrIAyAAIg1CRgAhKC0IABgZIg9AAIgRAZIg6AAIBgiHQAEgEAEgCIAIgDIAKgBIBCAAIAACRgAhvB4IAmAAIABg7gAlZC0IA0iRIA6AAIgoBsIBLAAIgOAlgAnuC0IA1iRIA5AAIgnBsIBKAAIgNAlgAp+C0IAMghIhTAAIAPgnIBCg7QAHgHAGgDQAGgEAHAAIBHAAIgdBRIAUAAIgLAfIgVAAIgMAhgAqRB0IArAAIAVg9gAmwAAQgNgCgMgEQgKgEgIgFQgHgGgFgHQgFgHgDgIQgCgIAAgKIABgTIAHgVQADgLAGgJQAEgKAGgIQAGgIAHgGQAGgGAJgEQAHgFAKgEQAJgEAJgCQAOgCAhgCQAQAAANACQAOACAKAEQALADAIAGQAHAGAFAGQAFAHACAJQADAHAAAKIgBATQgCALgEALIgJAUQgFAJgGAIIgNAOQgGAHgJAFQgHAEgKAEIgTAFQgcADgRAAQgQAAgOAAgAmCiJQgIADgHAEQgHAGgFAIQgGAJgEAMQgEANgCAKQAAAKADAHQADAGAIAEQAHAEAMAAQALAAAIgDQAIgCAHgFQAGgFAGgIQAGgJAEgMQAFgOAAgJQACgLgFgGQgCgHgIgDQgHgEgNAAQgKAAgIACgApzAAQgNgCgLgEQgLgDgHgGQgJgFgFgHQgGgGgDgJQgCgIgBgKQAAgKACgLQACgKAEgNQAEgLAFgKQAGgJAGgIQAHgHAIgGQAHgGAJgFQAMgGAagHQAOgCAcgBQAUAAAUADQARADAPAGIgPArQgLgEgOgDQgPgDgOAAQgNAAgLACQgLACgIAFQgJAGgHAIQgHAJgFAOQgEANAAAJQACAJAFAGQAHAFAKADQAKADAPAAIAdgCQAOgCALgDIgQAuQgOADgPABQgNAAgRAAQgPAAgNAAgAJkgDIAAgeIhIAAIgUAeIhIAAIB2ijQAEgEAEgDIAKgDIAMgCIBQAAIAACvgAI3hLIAuAAIAChIgAF1gDIgUgyIgVAAIgTAyIhEAAIA/ivIB1ACIAUADQAIADAGAEQAHADAEAFQAEAEACAGQADAGAAAGQABAHgCAIIgEAQQgDAJgGAIQgFAHgIAFQgHAFgJADQgJADgLACIAbA8gAFbhdIAjgBIALgCQAFgDAEgDQADgEACgHIADgKQAAgFgDgDQgCgDgHgCQgFgBgJAAIgWAAgAAhgDIBAivIBYAAQAOAAAMACQALACAJADQAJACAHAEQAGAFAFAFQAEAFACAHQACAGAAAHQAAAIgBAIIgFAQIgHAQIgJAMQgFAFgFAEIgMAHQgNAGgQACQgQACgUAAIgpAAIgPApgACDhUIATAAIASgBQAGgBAGgDQAEgCAEgFIAGgMIADgNQAAgGgCgDQgCgEgHgCQgGgBgKAAIgTAAgAhGgDIAvh+IhbB+Ig7AAIABiBIgvCBIg8AAIBAivIBJAAQAIAAAFACQAEACADADQADAEABAFQABAGAAAHIABBNIBJhqIBoAAIg9Cvg");
	this.shape_1.setTransform(-0.3,-11.1);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-71.4,-30,143.1,37.3);


(lib.Camioneta120_mc = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.Camioneta120();
	this.instance.setTransform(-232,-200.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-232,-200.5,464,401);


(lib.Azul = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(22,97,167,0)","#1661A7"],[0,0.396],-63.6,0,53.3,0).s().p("ApHCPIAAkeISPAAIibEeg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-58.4,-14.4,116.9,28.8);


// stage content:
(lib._160x600_opp = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_148 = function() {
		/* Stop at This Frame
		The  timeline will stop/pause at the frame where you insert this code.
		Can also be used to stop/pause the timeline of movieclips.
		*/
		
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(148).call(this.frame_148).wait(1));

	// LOGO
	this.instance = new lib.LOGO_mc();
	this.instance.setTransform(260.1,534.4);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(20).to({_off:false},0).wait(1).to({regX:-5.4,regY:-1,scaleX:1.03,scaleY:1.03,x:233.5,y:533.4},0).wait(1).to({scaleX:1.06,scaleY:1.06,x:212.4},0).wait(1).to({scaleX:1.09,scaleY:1.09,x:191.2,y:533.3},0).wait(1).to({scaleX:1.12,scaleY:1.12,x:170.1},0).wait(1).to({scaleX:1.15,scaleY:1.15,x:149},0).wait(1).to({scaleX:1.18,scaleY:1.18,x:127.9,y:533.2},0).wait(1).to({scaleX:1.21,scaleY:1.21,x:106.8},0).wait(1).to({scaleX:1.24,scaleY:1.24,x:85.6},0).wait(121));

	// PlecaAzul
	this.instance_1 = new lib.Azul();
	this.instance_1.setTransform(-69.2,563.7,1.185,1.185);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(20).to({_off:false},0).wait(1).to({scaleX:1.19,scaleY:1.19,x:-52.3},0).wait(1).to({scaleX:1.19,scaleY:1.19,x:-35.3},0).wait(1).to({scaleX:1.2,scaleY:1.2,x:-18.4},0).wait(1).to({scaleX:1.2,scaleY:1.2,x:-1.4},0).wait(1).to({scaleX:1.21,scaleY:1.21,x:15.5},0).wait(1).to({scaleX:1.21,scaleY:1.21,x:32.5},0).wait(1).to({scaleX:1.22,scaleY:1.22,x:49.4},0).wait(1).to({scaleX:1.22,scaleY:1.22,x:66.4},0).wait(121));

	// BTN
	this.instance_2 = new lib.Info_btn();
	this.instance_2.setTransform(-135.4,194.4);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(78).to({_off:false},0).wait(1).to({scaleX:1.04,scaleY:1.04,x:-99.1,alpha:0.167},0).wait(1).to({scaleX:1.08,scaleY:1.08,x:-62.7,alpha:0.333},0).wait(1).to({scaleX:1.12,scaleY:1.12,x:-26.4,alpha:0.5},0).wait(1).to({scaleX:1.17,scaleY:1.17,x:10,alpha:0.667},0).wait(1).to({scaleX:1.21,scaleY:1.21,x:46.3,alpha:0.833},0).wait(1).to({scaleX:1.25,scaleY:1.25,x:82.7,alpha:1},0).wait(65));

	// FlashAICB
	this.instance_3 = new lib.RECI();
	this.instance_3.setTransform(-178.4,103.7,0.592,0.592,0,0,0,-0.1,0);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(72).to({_off:false},0).wait(1).to({regX:-0.5,regY:-4.1,scaleX:0.63,scaleY:0.63,x:-155,y:101,alpha:0.091},0).wait(1).to({scaleX:0.67,scaleY:0.67,x:-131.5,y:100.7,alpha:0.182},0).wait(1).to({scaleX:0.71,scaleY:0.71,x:-108,y:100.5,alpha:0.273},0).wait(1).to({scaleX:0.75,scaleY:0.75,x:-84.4,y:100.2,alpha:0.364},0).wait(1).to({scaleX:0.79,scaleY:0.79,x:-60.9,y:99.9,alpha:0.455},0).wait(1).to({scaleX:0.83,scaleY:0.83,x:-37.4,y:99.7,alpha:0.545},0).wait(1).to({scaleX:0.87,scaleY:0.87,x:-13.9,y:99.5,alpha:0.636},0).wait(1).to({scaleX:0.9,scaleY:0.9,x:9.7,y:99.2,alpha:0.727},0).wait(1).to({scaleX:0.94,scaleY:0.94,x:33.2,y:99,alpha:0.818},0).wait(1).to({scaleX:0.98,scaleY:0.98,x:56.7,y:98.7,alpha:0.909},0).wait(1).to({scaleX:1.02,scaleY:1.02,x:80.3,y:98.5,alpha:1},0).wait(66));

	// Text1
	this.instance_4 = new lib.COM();
	this.instance_4.setTransform(-180,104.6,0.658,0.658);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(32).to({_off:false},0).wait(1).to({regX:0.1,regY:-11.4,scaleX:0.7,scaleY:0.7,x:-151,y:96.6,alpha:0.111},0).wait(1).to({scaleX:0.74,scaleY:0.74,x:-122.1,y:96.1,alpha:0.222},0).wait(1).to({scaleX:0.77,scaleY:0.77,x:-93.1,y:95.7,alpha:0.333},0).wait(1).to({scaleX:0.81,scaleY:0.81,x:-64.2,y:95.2,alpha:0.444},0).wait(1).to({scaleX:0.85,scaleY:0.85,x:-35.3,y:94.7,alpha:0.556},0).wait(1).to({scaleX:0.89,scaleY:0.89,x:-6.4,y:94.3,alpha:0.667},0).wait(1).to({scaleX:0.93,scaleY:0.93,x:22.5,y:93.8,alpha:0.778},0).wait(1).to({scaleX:0.97,scaleY:0.97,x:51.4,y:93.3,alpha:0.889},0).wait(1).to({scaleX:1,scaleY:1,x:80.3,y:92.9,alpha:1},0).wait(36).to({_off:true},1).wait(71));

	// Camioneta
	this.instance_5 = new lib.Camioneta120_mc();
	this.instance_5.setTransform(-323.7,587.2,1.266,1.266);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(13).to({_off:false},0).wait(1).to({scaleX:1.18,scaleY:1.18,x:-288.7,y:567.3},0).wait(1).to({scaleX:1.08,scaleY:1.08,x:-253.7,y:547.4},0).wait(1).to({scaleX:0.99,scaleY:0.99,x:-218.6,y:527.6},0).wait(1).to({scaleX:0.9,scaleY:0.9,x:-183.6,y:507.7},0).wait(1).to({scaleX:0.81,scaleY:0.81,x:-148.5,y:487.8},0).wait(1).to({scaleX:0.72,scaleY:0.72,x:-113.5,y:468},0).wait(1).to({scaleX:0.63,scaleY:0.63,x:-78.5,y:448.1},0).wait(1).to({scaleX:0.54,scaleY:0.54,x:-43.4,y:428.2},0).wait(1).to({scaleX:0.45,scaleY:0.45,x:-8.3,y:408.3},0).wait(1).to({scaleX:0.36,scaleY:0.36,x:26.7,y:388.4},0).wait(1).to({scaleX:0.27,scaleY:0.27,x:61.8,y:368.6},0).wait(125));

	// F3
	this.instance_6 = new lib.Symbol13();
	this.instance_6.setTransform(-209.9,500);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(6).to({_off:false},0).wait(1).to({regX:1,x:-151.1},0).wait(1).to({x:-93.3},0).wait(1).to({x:-35.5},0).wait(1).to({x:22.2},0).wait(1).to({x:80},0).wait(138));

	// F2
	this.instance_7 = new lib.Symbol12();
	this.instance_7.setTransform(334,300);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(2).to({_off:false},0).wait(1).to({x:297.7},0).wait(1).to({x:261.4},0).wait(1).to({x:225.1},0).wait(1).to({x:188.9},0).wait(1).to({x:152.6},0).wait(1).to({x:116.3},0).wait(1).to({x:80},0).wait(140));

	// F1
	this.instance_8 = new lib.Symbol11();
	this.instance_8.setTransform(-209.9,100);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(1).to({x:-168.5},0).wait(1).to({x:-127.1},0).wait(1).to({x:-85.7},0).wait(1).to({x:-44.3},0).wait(1).to({x:-2.8},0).wait(1).to({x:38.6},0).wait(1).to({x:80},0).wait(142));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-209.9,300,160,200);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;